// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: models/model_ip_library.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPLibrary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	File          *File                  `protobuf:"bytes,30,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPLibrary) Reset() {
	*x = IPLibrary{}
	mi := &file_models_model_ip_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPLibrary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPLibrary) ProtoMessage() {}

func (x *IPLibrary) ProtoReflect() protoreflect.Message {
	mi := &file_models_model_ip_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPLibrary.ProtoReflect.Descriptor instead.
func (*IPLibrary) Descriptor() ([]byte, []int) {
	return file_models_model_ip_library_proto_rawDescGZIP(), []int{0}
}

func (x *IPLibrary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IPLibrary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IPLibrary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *IPLibrary) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

var File_models_model_ip_library_proto protoreflect.FileDescriptor

const file_models_model_ip_library_proto_rawDesc = "" +
	"\n" +
	"\x1dmodels/model_ip_library.proto\x12\x02pb\x1a\x17models/model_file.proto\"k\n" +
	"\tIPLibrary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\x04file\x18\x1e \x01(\v2\b.pb.FileR\x04fileB\x06Z\x04./pbb\x06proto3"

var (
	file_models_model_ip_library_proto_rawDescOnce sync.Once
	file_models_model_ip_library_proto_rawDescData []byte
)

func file_models_model_ip_library_proto_rawDescGZIP() []byte {
	file_models_model_ip_library_proto_rawDescOnce.Do(func() {
		file_models_model_ip_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_model_ip_library_proto_rawDesc), len(file_models_model_ip_library_proto_rawDesc)))
	})
	return file_models_model_ip_library_proto_rawDescData
}

var file_models_model_ip_library_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_model_ip_library_proto_goTypes = []any{
	(*IPLibrary)(nil), // 0: pb.IPLibrary
	(*File)(nil),      // 1: pb.File
}
var file_models_model_ip_library_proto_depIdxs = []int32{
	1, // 0: pb.IPLibrary.file:type_name -> pb.File
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_model_ip_library_proto_init() }
func file_models_model_ip_library_proto_init() {
	if File_models_model_ip_library_proto != nil {
		return
	}
	file_models_model_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_model_ip_library_proto_rawDesc), len(file_models_model_ip_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_model_ip_library_proto_goTypes,
		DependencyIndexes: file_models_model_ip_library_proto_depIdxs,
		MessageInfos:      file_models_model_ip_library_proto_msgTypes,
	}.Build()
	File_models_model_ip_library_proto = out.File
	file_models_model_ip_library_proto_goTypes = nil
	file_models_model_ip_library_proto_depIdxs = nil
}
