// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: models/model_metric_stat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统计数据
type MetricStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ServerId      int64                  `protobuf:"varint,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	ItemId        int64                  `protobuf:"varint,4,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Keys          []string               `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	Value         float32                `protobuf:"fixed32,6,opt,name=value,proto3" json:"value,omitempty"`
	Time          string                 `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	NodeCluster   *NodeCluster           `protobuf:"bytes,30,opt,name=nodeCluster,proto3" json:"nodeCluster,omitempty"`
	Node          *Node                  `protobuf:"bytes,31,opt,name=node,proto3" json:"node,omitempty"`
	Server        *Server                `protobuf:"bytes,32,opt,name=server,proto3" json:"server,omitempty"`
	SumCount      int64                  `protobuf:"varint,40,opt,name=sumCount,proto3" json:"sumCount,omitempty"`
	SumTotal      float32                `protobuf:"fixed32,41,opt,name=sumTotal,proto3" json:"sumTotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricStat) Reset() {
	*x = MetricStat{}
	mi := &file_models_model_metric_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStat) ProtoMessage() {}

func (x *MetricStat) ProtoReflect() protoreflect.Message {
	mi := &file_models_model_metric_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStat.ProtoReflect.Descriptor instead.
func (*MetricStat) Descriptor() ([]byte, []int) {
	return file_models_model_metric_stat_proto_rawDescGZIP(), []int{0}
}

func (x *MetricStat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MetricStat) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MetricStat) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *MetricStat) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MetricStat) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MetricStat) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricStat) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *MetricStat) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MetricStat) GetNodeCluster() *NodeCluster {
	if x != nil {
		return x.NodeCluster
	}
	return nil
}

func (x *MetricStat) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *MetricStat) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *MetricStat) GetSumCount() int64 {
	if x != nil {
		return x.SumCount
	}
	return 0
}

func (x *MetricStat) GetSumTotal() float32 {
	if x != nil {
		return x.SumTotal
	}
	return 0
}

// 需要上传的统计数据
type UploadingMetricStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Keys          []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	Value         float32                `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadingMetricStat) Reset() {
	*x = UploadingMetricStat{}
	mi := &file_models_model_metric_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadingMetricStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadingMetricStat) ProtoMessage() {}

func (x *UploadingMetricStat) ProtoReflect() protoreflect.Message {
	mi := &file_models_model_metric_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadingMetricStat.ProtoReflect.Descriptor instead.
func (*UploadingMetricStat) Descriptor() ([]byte, []int) {
	return file_models_model_metric_stat_proto_rawDescGZIP(), []int{1}
}

func (x *UploadingMetricStat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UploadingMetricStat) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UploadingMetricStat) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *UploadingMetricStat) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_models_model_metric_stat_proto protoreflect.FileDescriptor

const file_models_model_metric_stat_proto_rawDesc = "" +
	"\n" +
	"\x1emodels/model_metric_stat.proto\x12\x02pb\x1a\x1fmodels/model_node_cluster.proto\x1a\x17models/model_node.proto\x1a\x19models/model_server.proto\"\xe9\x02\n" +
	"\n" +
	"MetricStat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1a\n" +
	"\bserverId\x18\x03 \x01(\x03R\bserverId\x12\x16\n" +
	"\x06itemId\x18\x04 \x01(\x03R\x06itemId\x12\x12\n" +
	"\x04keys\x18\x05 \x03(\tR\x04keys\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x02R\x05value\x12\x12\n" +
	"\x04time\x18\a \x01(\tR\x04time\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x121\n" +
	"\vnodeCluster\x18\x1e \x01(\v2\x0f.pb.NodeClusterR\vnodeCluster\x12\x1c\n" +
	"\x04node\x18\x1f \x01(\v2\b.pb.NodeR\x04node\x12\"\n" +
	"\x06server\x18  \x01(\v2\n" +
	".pb.ServerR\x06server\x12\x1a\n" +
	"\bsumCount\x18( \x01(\x03R\bsumCount\x12\x1a\n" +
	"\bsumTotal\x18) \x01(\x02R\bsumTotal\"c\n" +
	"\x13UploadingMetricStat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x02R\x05valueB\x06Z\x04./pbb\x06proto3"

var (
	file_models_model_metric_stat_proto_rawDescOnce sync.Once
	file_models_model_metric_stat_proto_rawDescData []byte
)

func file_models_model_metric_stat_proto_rawDescGZIP() []byte {
	file_models_model_metric_stat_proto_rawDescOnce.Do(func() {
		file_models_model_metric_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_model_metric_stat_proto_rawDesc), len(file_models_model_metric_stat_proto_rawDesc)))
	})
	return file_models_model_metric_stat_proto_rawDescData
}

var file_models_model_metric_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_model_metric_stat_proto_goTypes = []any{
	(*MetricStat)(nil),          // 0: pb.MetricStat
	(*UploadingMetricStat)(nil), // 1: pb.UploadingMetricStat
	(*NodeCluster)(nil),         // 2: pb.NodeCluster
	(*Node)(nil),                // 3: pb.Node
	(*Server)(nil),              // 4: pb.Server
}
var file_models_model_metric_stat_proto_depIdxs = []int32{
	2, // 0: pb.MetricStat.nodeCluster:type_name -> pb.NodeCluster
	3, // 1: pb.MetricStat.node:type_name -> pb.Node
	4, // 2: pb.MetricStat.server:type_name -> pb.Server
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_model_metric_stat_proto_init() }
func file_models_model_metric_stat_proto_init() {
	if File_models_model_metric_stat_proto != nil {
		return
	}
	file_models_model_node_cluster_proto_init()
	file_models_model_node_proto_init()
	file_models_model_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_model_metric_stat_proto_rawDesc), len(file_models_model_metric_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_model_metric_stat_proto_goTypes,
		DependencyIndexes: file_models_model_metric_stat_proto_depIdxs,
		MessageInfos:      file_models_model_metric_stat_proto_msgTypes,
	}.Build()
	File_models_model_metric_stat_proto = out.File
	file_models_model_metric_stat_proto_goTypes = nil
	file_models_model_metric_stat_proto_depIdxs = nil
}
