// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: models/model_ns_user_plan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NSUserPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NsPlanId      int64                  `protobuf:"varint,2,opt,name=nsPlanId,proto3" json:"nsPlanId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	DayFrom       string                 `protobuf:"bytes,4,opt,name=dayFrom,proto3" json:"dayFrom,omitempty"`
	DayTo         string                 `protobuf:"bytes,5,opt,name=dayTo,proto3" json:"dayTo,omitempty"`
	PeriodUnit    string                 `protobuf:"bytes,6,opt,name=periodUnit,proto3" json:"periodUnit,omitempty"`
	NsPlan        *NSPlan                `protobuf:"bytes,30,opt,name=nsPlan,proto3" json:"nsPlan,omitempty"`
	User          *User                  `protobuf:"bytes,31,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSUserPlan) Reset() {
	*x = NSUserPlan{}
	mi := &file_models_model_ns_user_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSUserPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSUserPlan) ProtoMessage() {}

func (x *NSUserPlan) ProtoReflect() protoreflect.Message {
	mi := &file_models_model_ns_user_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSUserPlan.ProtoReflect.Descriptor instead.
func (*NSUserPlan) Descriptor() ([]byte, []int) {
	return file_models_model_ns_user_plan_proto_rawDescGZIP(), []int{0}
}

func (x *NSUserPlan) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NSUserPlan) GetNsPlanId() int64 {
	if x != nil {
		return x.NsPlanId
	}
	return 0
}

func (x *NSUserPlan) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NSUserPlan) GetDayFrom() string {
	if x != nil {
		return x.DayFrom
	}
	return ""
}

func (x *NSUserPlan) GetDayTo() string {
	if x != nil {
		return x.DayTo
	}
	return ""
}

func (x *NSUserPlan) GetPeriodUnit() string {
	if x != nil {
		return x.PeriodUnit
	}
	return ""
}

func (x *NSUserPlan) GetNsPlan() *NSPlan {
	if x != nil {
		return x.NsPlan
	}
	return nil
}

func (x *NSUserPlan) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_models_model_ns_user_plan_proto protoreflect.FileDescriptor

const file_models_model_ns_user_plan_proto_rawDesc = "" +
	"\n" +
	"\x1fmodels/model_ns_user_plan.proto\x12\x02pb\x1a\x1amodels/model_ns_plan.proto\x1a\x17models/model_user.proto\"\xe2\x01\n" +
	"\n" +
	"NSUserPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnsPlanId\x18\x02 \x01(\x03R\bnsPlanId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\adayFrom\x18\x04 \x01(\tR\adayFrom\x12\x14\n" +
	"\x05dayTo\x18\x05 \x01(\tR\x05dayTo\x12\x1e\n" +
	"\n" +
	"periodUnit\x18\x06 \x01(\tR\n" +
	"periodUnit\x12\"\n" +
	"\x06nsPlan\x18\x1e \x01(\v2\n" +
	".pb.NSPlanR\x06nsPlan\x12\x1c\n" +
	"\x04user\x18\x1f \x01(\v2\b.pb.UserR\x04userB\x06Z\x04./pbb\x06proto3"

var (
	file_models_model_ns_user_plan_proto_rawDescOnce sync.Once
	file_models_model_ns_user_plan_proto_rawDescData []byte
)

func file_models_model_ns_user_plan_proto_rawDescGZIP() []byte {
	file_models_model_ns_user_plan_proto_rawDescOnce.Do(func() {
		file_models_model_ns_user_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_model_ns_user_plan_proto_rawDesc), len(file_models_model_ns_user_plan_proto_rawDesc)))
	})
	return file_models_model_ns_user_plan_proto_rawDescData
}

var file_models_model_ns_user_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_model_ns_user_plan_proto_goTypes = []any{
	(*NSUserPlan)(nil), // 0: pb.NSUserPlan
	(*NSPlan)(nil),     // 1: pb.NSPlan
	(*User)(nil),       // 2: pb.User
}
var file_models_model_ns_user_plan_proto_depIdxs = []int32{
	1, // 0: pb.NSUserPlan.nsPlan:type_name -> pb.NSPlan
	2, // 1: pb.NSUserPlan.user:type_name -> pb.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_models_model_ns_user_plan_proto_init() }
func file_models_model_ns_user_plan_proto_init() {
	if File_models_model_ns_user_plan_proto != nil {
		return
	}
	file_models_model_ns_plan_proto_init()
	file_models_model_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_model_ns_user_plan_proto_rawDesc), len(file_models_model_ns_user_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_model_ns_user_plan_proto_goTypes,
		DependencyIndexes: file_models_model_ns_user_plan_proto_depIdxs,
		MessageInfos:      file_models_model_ns_user_plan_proto_msgTypes,
	}.Build()
	File_models_model_ns_user_plan_proto = out.File
	file_models_model_ns_user_plan_proto_goTypes = nil
	file_models_model_ns_user_plan_proto_depIdxs = nil
}
