// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: models/model_node_ip_address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点地址
type NodeIPAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	State         int64                  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	Order         int64                  `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	CanAccess     bool                   `protobuf:"varint,8,opt,name=canAccess,proto3" json:"canAccess,omitempty"`
	IsOn          bool                   `protobuf:"varint,9,opt,name=isOn,proto3" json:"isOn,omitempty"`
	IsUp          bool                   `protobuf:"varint,10,opt,name=isUp,proto3" json:"isUp,omitempty"`
	Role          string                 `protobuf:"bytes,12,opt,name=role,proto3" json:"role,omitempty"`
	BackupIP      string                 `protobuf:"bytes,13,opt,name=backupIP,proto3" json:"backupIP,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,14,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	NodeClusters  []*NodeCluster         `protobuf:"bytes,30,rep,name=nodeClusters,proto3" json:"nodeClusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIPAddress) Reset() {
	*x = NodeIPAddress{}
	mi := &file_models_model_node_ip_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIPAddress) ProtoMessage() {}

func (x *NodeIPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_models_model_node_ip_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIPAddress.ProtoReflect.Descriptor instead.
func (*NodeIPAddress) Descriptor() ([]byte, []int) {
	return file_models_model_node_ip_address_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIPAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeIPAddress) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeIPAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeIPAddress) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeIPAddress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NodeIPAddress) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *NodeIPAddress) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *NodeIPAddress) GetCanAccess() bool {
	if x != nil {
		return x.CanAccess
	}
	return false
}

func (x *NodeIPAddress) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *NodeIPAddress) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *NodeIPAddress) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeIPAddress) GetBackupIP() string {
	if x != nil {
		return x.BackupIP
	}
	return ""
}

func (x *NodeIPAddress) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *NodeIPAddress) GetNodeClusters() []*NodeCluster {
	if x != nil {
		return x.NodeClusters
	}
	return nil
}

var File_models_model_node_ip_address_proto protoreflect.FileDescriptor

const file_models_model_node_ip_address_proto_rawDesc = "" +
	"\n" +
	"\"models/model_node_ip_address.proto\x12\x02pb\x1a\x1fmodels/model_node_cluster.proto\"\xf2\x02\n" +
	"\rNodeIPAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x06 \x01(\x03R\x05state\x12\x14\n" +
	"\x05order\x18\a \x01(\x03R\x05order\x12\x1c\n" +
	"\tcanAccess\x18\b \x01(\bR\tcanAccess\x12\x12\n" +
	"\x04isOn\x18\t \x01(\bR\x04isOn\x12\x12\n" +
	"\x04isUp\x18\n" +
	" \x01(\bR\x04isUp\x12\x12\n" +
	"\x04role\x18\f \x01(\tR\x04role\x12\x1a\n" +
	"\bbackupIP\x18\r \x01(\tR\bbackupIP\x12\x1c\n" +
	"\tisHealthy\x18\x0e \x01(\bR\tisHealthy\x123\n" +
	"\fnodeClusters\x18\x1e \x03(\v2\x0f.pb.NodeClusterR\fnodeClustersB\x06Z\x04./pbb\x06proto3"

var (
	file_models_model_node_ip_address_proto_rawDescOnce sync.Once
	file_models_model_node_ip_address_proto_rawDescData []byte
)

func file_models_model_node_ip_address_proto_rawDescGZIP() []byte {
	file_models_model_node_ip_address_proto_rawDescOnce.Do(func() {
		file_models_model_node_ip_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_model_node_ip_address_proto_rawDesc), len(file_models_model_node_ip_address_proto_rawDesc)))
	})
	return file_models_model_node_ip_address_proto_rawDescData
}

var file_models_model_node_ip_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_model_node_ip_address_proto_goTypes = []any{
	(*NodeIPAddress)(nil), // 0: pb.NodeIPAddress
	(*NodeCluster)(nil),   // 1: pb.NodeCluster
}
var file_models_model_node_ip_address_proto_depIdxs = []int32{
	1, // 0: pb.NodeIPAddress.nodeClusters:type_name -> pb.NodeCluster
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_model_node_ip_address_proto_init() }
func file_models_model_node_ip_address_proto_init() {
	if File_models_model_node_ip_address_proto != nil {
		return
	}
	file_models_model_node_cluster_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_model_node_ip_address_proto_rawDesc), len(file_models_model_node_ip_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_model_node_ip_address_proto_goTypes,
		DependencyIndexes: file_models_model_node_ip_address_proto_depIdxs,
		MessageInfos:      file_models_model_node_ip_address_proto_msgTypes,
	}.Build()
	File_models_model_node_ip_address_proto = out.File
	file_models_model_node_ip_address_proto_goTypes = nil
	file_models_model_node_ip_address_proto_depIdxs = nil
}
