// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_ns_record_hourly_stat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传统计
type UploadNSRecordHourlyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*NSRecordHourlyStat  `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadNSRecordHourlyStatsRequest) Reset() {
	*x = UploadNSRecordHourlyStatsRequest{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadNSRecordHourlyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadNSRecordHourlyStatsRequest) ProtoMessage() {}

func (x *UploadNSRecordHourlyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadNSRecordHourlyStatsRequest.ProtoReflect.Descriptor instead.
func (*UploadNSRecordHourlyStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{0}
}

func (x *UploadNSRecordHourlyStatsRequest) GetStats() []*NSRecordHourlyStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 获取单个记录单个小时的统计
type FindNSRecordHourlyStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsRecordId    int64                  `protobuf:"varint,1,opt,name=nsRecordId,proto3" json:"nsRecordId,omitempty"` // 记录ID
	Hour          string                 `protobuf:"bytes,2,opt,name=hour,proto3" json:"hour,omitempty"`              // YYYYMMDDHH
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNSRecordHourlyStatRequest) Reset() {
	*x = FindNSRecordHourlyStatRequest{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSRecordHourlyStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSRecordHourlyStatRequest) ProtoMessage() {}

func (x *FindNSRecordHourlyStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSRecordHourlyStatRequest.ProtoReflect.Descriptor instead.
func (*FindNSRecordHourlyStatRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{1}
}

func (x *FindNSRecordHourlyStatRequest) GetNsRecordId() int64 {
	if x != nil {
		return x.NsRecordId
	}
	return 0
}

func (x *FindNSRecordHourlyStatRequest) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

type FindNSRecordHourlyStatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NsRecordHourlyStat *NSRecordHourlyStat    `protobuf:"bytes,1,opt,name=nsRecordHourlyStat,proto3" json:"nsRecordHourlyStat,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FindNSRecordHourlyStatResponse) Reset() {
	*x = FindNSRecordHourlyStatResponse{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSRecordHourlyStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSRecordHourlyStatResponse) ProtoMessage() {}

func (x *FindNSRecordHourlyStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSRecordHourlyStatResponse.ProtoReflect.Descriptor instead.
func (*FindNSRecordHourlyStatResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{2}
}

func (x *FindNSRecordHourlyStatResponse) GetNsRecordHourlyStat() *NSRecordHourlyStat {
	if x != nil {
		return x.NsRecordHourlyStat
	}
	return nil
}

// 获取单个记录24小时内的统计
type FindLatestNSRecordsHourlyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsRecordId    int64                  `protobuf:"varint,1,opt,name=nsRecordId,proto3" json:"nsRecordId,omitempty"` // 记录ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLatestNSRecordsHourlyStatsRequest) Reset() {
	*x = FindLatestNSRecordsHourlyStatsRequest{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLatestNSRecordsHourlyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLatestNSRecordsHourlyStatsRequest) ProtoMessage() {}

func (x *FindLatestNSRecordsHourlyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLatestNSRecordsHourlyStatsRequest.ProtoReflect.Descriptor instead.
func (*FindLatestNSRecordsHourlyStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{3}
}

func (x *FindLatestNSRecordsHourlyStatsRequest) GetNsRecordId() int64 {
	if x != nil {
		return x.NsRecordId
	}
	return 0
}

type FindLatestNSRecordsHourlyStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NsRecordHourlyStats []*NSRecordHourlyStat  `protobuf:"bytes,2,rep,name=nsRecordHourlyStats,proto3" json:"nsRecordHourlyStats,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindLatestNSRecordsHourlyStatsResponse) Reset() {
	*x = FindLatestNSRecordsHourlyStatsResponse{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLatestNSRecordsHourlyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLatestNSRecordsHourlyStatsResponse) ProtoMessage() {}

func (x *FindLatestNSRecordsHourlyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLatestNSRecordsHourlyStatsResponse.ProtoReflect.Descriptor instead.
func (*FindLatestNSRecordsHourlyStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{4}
}

func (x *FindLatestNSRecordsHourlyStatsResponse) GetNsRecordHourlyStats() []*NSRecordHourlyStat {
	if x != nil {
		return x.NsRecordHourlyStats
	}
	return nil
}

// 批量获取一组记录的统计
type FindNSRecordHourlyStatWithRecordIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsRecordIds   []int64                `protobuf:"varint,1,rep,packed,name=nsRecordIds,proto3" json:"nsRecordIds,omitempty"`
	Hour          string                 `protobuf:"bytes,2,opt,name=hour,proto3" json:"hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNSRecordHourlyStatWithRecordIdsRequest) Reset() {
	*x = FindNSRecordHourlyStatWithRecordIdsRequest{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSRecordHourlyStatWithRecordIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSRecordHourlyStatWithRecordIdsRequest) ProtoMessage() {}

func (x *FindNSRecordHourlyStatWithRecordIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSRecordHourlyStatWithRecordIdsRequest.ProtoReflect.Descriptor instead.
func (*FindNSRecordHourlyStatWithRecordIdsRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{5}
}

func (x *FindNSRecordHourlyStatWithRecordIdsRequest) GetNsRecordIds() []int64 {
	if x != nil {
		return x.NsRecordIds
	}
	return nil
}

func (x *FindNSRecordHourlyStatWithRecordIdsRequest) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

type FindNSRecordHourlyStatWithRecordIdsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NsRecordHourlyStats []*NSRecordHourlyStat  `protobuf:"bytes,1,rep,name=nsRecordHourlyStats,proto3" json:"nsRecordHourlyStats,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindNSRecordHourlyStatWithRecordIdsResponse) Reset() {
	*x = FindNSRecordHourlyStatWithRecordIdsResponse{}
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSRecordHourlyStatWithRecordIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSRecordHourlyStatWithRecordIdsResponse) ProtoMessage() {}

func (x *FindNSRecordHourlyStatWithRecordIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_record_hourly_stat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSRecordHourlyStatWithRecordIdsResponse.ProtoReflect.Descriptor instead.
func (*FindNSRecordHourlyStatWithRecordIdsResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_record_hourly_stat_proto_rawDescGZIP(), []int{6}
}

func (x *FindNSRecordHourlyStatWithRecordIdsResponse) GetNsRecordHourlyStats() []*NSRecordHourlyStat {
	if x != nil {
		return x.NsRecordHourlyStats
	}
	return nil
}

var File_service_ns_record_hourly_stat_proto protoreflect.FileDescriptor

const file_service_ns_record_hourly_stat_proto_rawDesc = "" +
	"\n" +
	"#service_ns_record_hourly_stat.proto\x12\x02pb\x1a(models/model_ns_record_hourly_stat.proto\x1a\x19models/rpc_messages.proto\"P\n" +
	" UploadNSRecordHourlyStatsRequest\x12,\n" +
	"\x05stats\x18\x01 \x03(\v2\x16.pb.NSRecordHourlyStatR\x05stats\"S\n" +
	"\x1dFindNSRecordHourlyStatRequest\x12\x1e\n" +
	"\n" +
	"nsRecordId\x18\x01 \x01(\x03R\n" +
	"nsRecordId\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\tR\x04hour\"h\n" +
	"\x1eFindNSRecordHourlyStatResponse\x12F\n" +
	"\x12nsRecordHourlyStat\x18\x01 \x01(\v2\x16.pb.NSRecordHourlyStatR\x12nsRecordHourlyStat\"G\n" +
	"%FindLatestNSRecordsHourlyStatsRequest\x12\x1e\n" +
	"\n" +
	"nsRecordId\x18\x01 \x01(\x03R\n" +
	"nsRecordId\"r\n" +
	"&FindLatestNSRecordsHourlyStatsResponse\x12H\n" +
	"\x13nsRecordHourlyStats\x18\x02 \x03(\v2\x16.pb.NSRecordHourlyStatR\x13nsRecordHourlyStats\"b\n" +
	"*FindNSRecordHourlyStatWithRecordIdsRequest\x12 \n" +
	"\vnsRecordIds\x18\x01 \x03(\x03R\vnsRecordIds\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\tR\x04hour\"w\n" +
	"+FindNSRecordHourlyStatWithRecordIdsResponse\x12H\n" +
	"\x13nsRecordHourlyStats\x18\x01 \x03(\v2\x16.pb.NSRecordHourlyStatR\x13nsRecordHourlyStats2\xd1\x03\n" +
	"\x19NSRecordHourlyStatService\x12Q\n" +
	"\x19uploadNSRecordHourlyStats\x12$.pb.UploadNSRecordHourlyStatsRequest\x1a\x0e.pb.RPCSuccess\x12_\n" +
	"\x16findNSRecordHourlyStat\x12!.pb.FindNSRecordHourlyStatRequest\x1a\".pb.FindNSRecordHourlyStatResponse\x12w\n" +
	"\x1efindLatestNSRecordsHourlyStats\x12).pb.FindLatestNSRecordsHourlyStatsRequest\x1a*.pb.FindLatestNSRecordsHourlyStatsResponse\x12\x86\x01\n" +
	"#findNSRecordHourlyStatWithRecordIds\x12..pb.FindNSRecordHourlyStatWithRecordIdsRequest\x1a/.pb.FindNSRecordHourlyStatWithRecordIdsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_ns_record_hourly_stat_proto_rawDescOnce sync.Once
	file_service_ns_record_hourly_stat_proto_rawDescData []byte
)

func file_service_ns_record_hourly_stat_proto_rawDescGZIP() []byte {
	file_service_ns_record_hourly_stat_proto_rawDescOnce.Do(func() {
		file_service_ns_record_hourly_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_ns_record_hourly_stat_proto_rawDesc), len(file_service_ns_record_hourly_stat_proto_rawDesc)))
	})
	return file_service_ns_record_hourly_stat_proto_rawDescData
}

var file_service_ns_record_hourly_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_ns_record_hourly_stat_proto_goTypes = []any{
	(*UploadNSRecordHourlyStatsRequest)(nil),            // 0: pb.UploadNSRecordHourlyStatsRequest
	(*FindNSRecordHourlyStatRequest)(nil),               // 1: pb.FindNSRecordHourlyStatRequest
	(*FindNSRecordHourlyStatResponse)(nil),              // 2: pb.FindNSRecordHourlyStatResponse
	(*FindLatestNSRecordsHourlyStatsRequest)(nil),       // 3: pb.FindLatestNSRecordsHourlyStatsRequest
	(*FindLatestNSRecordsHourlyStatsResponse)(nil),      // 4: pb.FindLatestNSRecordsHourlyStatsResponse
	(*FindNSRecordHourlyStatWithRecordIdsRequest)(nil),  // 5: pb.FindNSRecordHourlyStatWithRecordIdsRequest
	(*FindNSRecordHourlyStatWithRecordIdsResponse)(nil), // 6: pb.FindNSRecordHourlyStatWithRecordIdsResponse
	(*NSRecordHourlyStat)(nil),                          // 7: pb.NSRecordHourlyStat
	(*RPCSuccess)(nil),                                  // 8: pb.RPCSuccess
}
var file_service_ns_record_hourly_stat_proto_depIdxs = []int32{
	7, // 0: pb.UploadNSRecordHourlyStatsRequest.stats:type_name -> pb.NSRecordHourlyStat
	7, // 1: pb.FindNSRecordHourlyStatResponse.nsRecordHourlyStat:type_name -> pb.NSRecordHourlyStat
	7, // 2: pb.FindLatestNSRecordsHourlyStatsResponse.nsRecordHourlyStats:type_name -> pb.NSRecordHourlyStat
	7, // 3: pb.FindNSRecordHourlyStatWithRecordIdsResponse.nsRecordHourlyStats:type_name -> pb.NSRecordHourlyStat
	0, // 4: pb.NSRecordHourlyStatService.uploadNSRecordHourlyStats:input_type -> pb.UploadNSRecordHourlyStatsRequest
	1, // 5: pb.NSRecordHourlyStatService.findNSRecordHourlyStat:input_type -> pb.FindNSRecordHourlyStatRequest
	3, // 6: pb.NSRecordHourlyStatService.findLatestNSRecordsHourlyStats:input_type -> pb.FindLatestNSRecordsHourlyStatsRequest
	5, // 7: pb.NSRecordHourlyStatService.findNSRecordHourlyStatWithRecordIds:input_type -> pb.FindNSRecordHourlyStatWithRecordIdsRequest
	8, // 8: pb.NSRecordHourlyStatService.uploadNSRecordHourlyStats:output_type -> pb.RPCSuccess
	2, // 9: pb.NSRecordHourlyStatService.findNSRecordHourlyStat:output_type -> pb.FindNSRecordHourlyStatResponse
	4, // 10: pb.NSRecordHourlyStatService.findLatestNSRecordsHourlyStats:output_type -> pb.FindLatestNSRecordsHourlyStatsResponse
	6, // 11: pb.NSRecordHourlyStatService.findNSRecordHourlyStatWithRecordIds:output_type -> pb.FindNSRecordHourlyStatWithRecordIdsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_ns_record_hourly_stat_proto_init() }
func file_service_ns_record_hourly_stat_proto_init() {
	if File_service_ns_record_hourly_stat_proto != nil {
		return
	}
	file_models_model_ns_record_hourly_stat_proto_init()
	file_models_rpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_ns_record_hourly_stat_proto_rawDesc), len(file_service_ns_record_hourly_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_ns_record_hourly_stat_proto_goTypes,
		DependencyIndexes: file_service_ns_record_hourly_stat_proto_depIdxs,
		MessageInfos:      file_service_ns_record_hourly_stat_proto_msgTypes,
	}.Build()
	File_service_ns_record_hourly_stat_proto = out.File
	file_service_ns_record_hourly_stat_proto_goTypes = nil
	file_service_ns_record_hourly_stat_proto_depIdxs = nil
}
