// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: service_latest_item.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LatestItemService_IncreaseLatestItem_FullMethodName = "/pb.LatestItemService/increaseLatestItem"
)

// LatestItemServiceClient is the client API for LatestItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 最近使用的条目服务
type LatestItemServiceClient interface {
	// 记录最近使用的条目
	IncreaseLatestItem(ctx context.Context, in *IncreaseLatestItemRequest, opts ...grpc.CallOption) (*RPCSuccess, error)
}

type latestItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLatestItemServiceClient(cc grpc.ClientConnInterface) LatestItemServiceClient {
	return &latestItemServiceClient{cc}
}

func (c *latestItemServiceClient) IncreaseLatestItem(ctx context.Context, in *IncreaseLatestItemRequest, opts ...grpc.CallOption) (*RPCSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RPCSuccess)
	err := c.cc.Invoke(ctx, LatestItemService_IncreaseLatestItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LatestItemServiceServer is the server API for LatestItemService service.
// All implementations should embed UnimplementedLatestItemServiceServer
// for forward compatibility.
//
// 最近使用的条目服务
type LatestItemServiceServer interface {
	// 记录最近使用的条目
	IncreaseLatestItem(context.Context, *IncreaseLatestItemRequest) (*RPCSuccess, error)
}

// UnimplementedLatestItemServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLatestItemServiceServer struct{}

func (UnimplementedLatestItemServiceServer) IncreaseLatestItem(context.Context, *IncreaseLatestItemRequest) (*RPCSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseLatestItem not implemented")
}
func (UnimplementedLatestItemServiceServer) testEmbeddedByValue() {}

// UnsafeLatestItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LatestItemServiceServer will
// result in compilation errors.
type UnsafeLatestItemServiceServer interface {
	mustEmbedUnimplementedLatestItemServiceServer()
}

func RegisterLatestItemServiceServer(s grpc.ServiceRegistrar, srv LatestItemServiceServer) {
	// If the following call pancis, it indicates UnimplementedLatestItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LatestItemService_ServiceDesc, srv)
}

func _LatestItemService_IncreaseLatestItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseLatestItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LatestItemServiceServer).IncreaseLatestItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LatestItemService_IncreaseLatestItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LatestItemServiceServer).IncreaseLatestItem(ctx, req.(*IncreaseLatestItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LatestItemService_ServiceDesc is the grpc.ServiceDesc for LatestItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LatestItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LatestItemService",
	HandlerType: (*LatestItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "increaseLatestItem",
			Handler:    _LatestItemService_IncreaseLatestItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_latest_item.proto",
}
