// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_ns_key.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建密钥
type CreateNSKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsDomainId    int64                  `protobuf:"varint,1,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`
	NsZoneId      int64                  `protobuf:"varint,2,opt,name=nsZoneId,proto3" json:"nsZoneId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Algo          string                 `protobuf:"bytes,4,opt,name=algo,proto3" json:"algo,omitempty"`
	Secret        string                 `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	SecretType    string                 `protobuf:"bytes,6,opt,name=secretType,proto3" json:"secretType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNSKeyRequest) Reset() {
	*x = CreateNSKeyRequest{}
	mi := &file_service_ns_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNSKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNSKeyRequest) ProtoMessage() {}

func (x *CreateNSKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNSKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateNSKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNSKeyRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *CreateNSKeyRequest) GetNsZoneId() int64 {
	if x != nil {
		return x.NsZoneId
	}
	return 0
}

func (x *CreateNSKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNSKeyRequest) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *CreateNSKeyRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateNSKeyRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

type CreateNSKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKeyId       int64                  `protobuf:"varint,1,opt,name=nsKeyId,proto3" json:"nsKeyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNSKeyResponse) Reset() {
	*x = CreateNSKeyResponse{}
	mi := &file_service_ns_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNSKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNSKeyResponse) ProtoMessage() {}

func (x *CreateNSKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNSKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateNSKeyResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNSKeyResponse) GetNsKeyId() int64 {
	if x != nil {
		return x.NsKeyId
	}
	return 0
}

// 修改密钥
type UpdateNSKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKeyId       int64                  `protobuf:"varint,1,opt,name=nsKeyId,proto3" json:"nsKeyId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Algo          string                 `protobuf:"bytes,3,opt,name=algo,proto3" json:"algo,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	SecretType    string                 `protobuf:"bytes,5,opt,name=secretType,proto3" json:"secretType,omitempty"`
	IsOn          bool                   `protobuf:"varint,6,opt,name=isOn,proto3" json:"isOn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNSKeyRequest) Reset() {
	*x = UpdateNSKeyRequest{}
	mi := &file_service_ns_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNSKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNSKeyRequest) ProtoMessage() {}

func (x *UpdateNSKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNSKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateNSKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNSKeyRequest) GetNsKeyId() int64 {
	if x != nil {
		return x.NsKeyId
	}
	return 0
}

func (x *UpdateNSKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNSKeyRequest) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *UpdateNSKeyRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateNSKeyRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *UpdateNSKeyRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

// 删除密钥
type DeleteNSKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKeyId       int64                  `protobuf:"varint,1,opt,name=nsKeyId,proto3" json:"nsKeyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNSKeyRequest) Reset() {
	*x = DeleteNSKeyRequest{}
	mi := &file_service_ns_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNSKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNSKeyRequest) ProtoMessage() {}

func (x *DeleteNSKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNSKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteNSKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNSKeyRequest) GetNsKeyId() int64 {
	if x != nil {
		return x.NsKeyId
	}
	return 0
}

// 查找单个密钥
type FindNSKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKeyId       int64                  `protobuf:"varint,1,opt,name=nsKeyId,proto3" json:"nsKeyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNSKeyRequest) Reset() {
	*x = FindNSKeyRequest{}
	mi := &file_service_ns_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSKeyRequest) ProtoMessage() {}

func (x *FindNSKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSKeyRequest.ProtoReflect.Descriptor instead.
func (*FindNSKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{4}
}

func (x *FindNSKeyRequest) GetNsKeyId() int64 {
	if x != nil {
		return x.NsKeyId
	}
	return 0
}

type FindNSKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKey         *NSKey                 `protobuf:"bytes,1,opt,name=nsKey,proto3" json:"nsKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNSKeyResponse) Reset() {
	*x = FindNSKeyResponse{}
	mi := &file_service_ns_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSKeyResponse) ProtoMessage() {}

func (x *FindNSKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSKeyResponse.ProtoReflect.Descriptor instead.
func (*FindNSKeyResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{5}
}

func (x *FindNSKeyResponse) GetNsKey() *NSKey {
	if x != nil {
		return x.NsKey
	}
	return nil
}

// 计算密钥数量
type CountAllNSKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsDomainId    int64                  `protobuf:"varint,1,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`
	NsZoneId      int64                  `protobuf:"varint,2,opt,name=nsZoneId,proto3" json:"nsZoneId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountAllNSKeysRequest) Reset() {
	*x = CountAllNSKeysRequest{}
	mi := &file_service_ns_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountAllNSKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountAllNSKeysRequest) ProtoMessage() {}

func (x *CountAllNSKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountAllNSKeysRequest.ProtoReflect.Descriptor instead.
func (*CountAllNSKeysRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{6}
}

func (x *CountAllNSKeysRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *CountAllNSKeysRequest) GetNsZoneId() int64 {
	if x != nil {
		return x.NsZoneId
	}
	return 0
}

// 列出单页密钥
type ListNSKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsDomainId    int64                  `protobuf:"varint,1,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`
	NsZoneId      int64                  `protobuf:"varint,2,opt,name=nsZoneId,proto3" json:"nsZoneId,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNSKeysRequest) Reset() {
	*x = ListNSKeysRequest{}
	mi := &file_service_ns_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNSKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSKeysRequest) ProtoMessage() {}

func (x *ListNSKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSKeysRequest.ProtoReflect.Descriptor instead.
func (*ListNSKeysRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{7}
}

func (x *ListNSKeysRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *ListNSKeysRequest) GetNsZoneId() int64 {
	if x != nil {
		return x.NsZoneId
	}
	return 0
}

func (x *ListNSKeysRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListNSKeysRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListNSKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKeys        []*NSKey               `protobuf:"bytes,1,rep,name=nsKeys,proto3" json:"nsKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNSKeysResponse) Reset() {
	*x = ListNSKeysResponse{}
	mi := &file_service_ns_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNSKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSKeysResponse) ProtoMessage() {}

func (x *ListNSKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSKeysResponse.ProtoReflect.Descriptor instead.
func (*ListNSKeysResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{8}
}

func (x *ListNSKeysResponse) GetNsKeys() []*NSKey {
	if x != nil {
		return x.NsKeys
	}
	return nil
}

// 根据版本列出一组密钥
type ListNSKeysAfterVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNSKeysAfterVersionRequest) Reset() {
	*x = ListNSKeysAfterVersionRequest{}
	mi := &file_service_ns_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNSKeysAfterVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSKeysAfterVersionRequest) ProtoMessage() {}

func (x *ListNSKeysAfterVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSKeysAfterVersionRequest.ProtoReflect.Descriptor instead.
func (*ListNSKeysAfterVersionRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{9}
}

func (x *ListNSKeysAfterVersionRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListNSKeysAfterVersionRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListNSKeysAfterVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsKeys        []*NSKey               `protobuf:"bytes,1,rep,name=nsKeys,proto3" json:"nsKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNSKeysAfterVersionResponse) Reset() {
	*x = ListNSKeysAfterVersionResponse{}
	mi := &file_service_ns_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNSKeysAfterVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSKeysAfterVersionResponse) ProtoMessage() {}

func (x *ListNSKeysAfterVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSKeysAfterVersionResponse.ProtoReflect.Descriptor instead.
func (*ListNSKeysAfterVersionResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_key_proto_rawDescGZIP(), []int{10}
}

func (x *ListNSKeysAfterVersionResponse) GetNsKeys() []*NSKey {
	if x != nil {
		return x.NsKeys
	}
	return nil
}

var File_service_ns_key_proto protoreflect.FileDescriptor

const file_service_ns_key_proto_rawDesc = "" +
	"\n" +
	"\x14service_ns_key.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\x1a\x19models/model_ns_key.proto\"\xb0\x01\n" +
	"\x12CreateNSKeyRequest\x12\x1e\n" +
	"\n" +
	"nsDomainId\x18\x01 \x01(\x03R\n" +
	"nsDomainId\x12\x1a\n" +
	"\bnsZoneId\x18\x02 \x01(\x03R\bnsZoneId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04algo\x18\x04 \x01(\tR\x04algo\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\tR\x06secret\x12\x1e\n" +
	"\n" +
	"secretType\x18\x06 \x01(\tR\n" +
	"secretType\"/\n" +
	"\x13CreateNSKeyResponse\x12\x18\n" +
	"\ansKeyId\x18\x01 \x01(\x03R\ansKeyId\"\xa2\x01\n" +
	"\x12UpdateNSKeyRequest\x12\x18\n" +
	"\ansKeyId\x18\x01 \x01(\x03R\ansKeyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04algo\x18\x03 \x01(\tR\x04algo\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x1e\n" +
	"\n" +
	"secretType\x18\x05 \x01(\tR\n" +
	"secretType\x12\x12\n" +
	"\x04isOn\x18\x06 \x01(\bR\x04isOn\".\n" +
	"\x12DeleteNSKeyRequest\x12\x18\n" +
	"\ansKeyId\x18\x01 \x01(\x03R\ansKeyId\",\n" +
	"\x10FindNSKeyRequest\x12\x18\n" +
	"\ansKeyId\x18\x01 \x01(\x03R\ansKeyId\"4\n" +
	"\x11FindNSKeyResponse\x12\x1f\n" +
	"\x05nsKey\x18\x01 \x01(\v2\t.pb.NSKeyR\x05nsKey\"S\n" +
	"\x15CountAllNSKeysRequest\x12\x1e\n" +
	"\n" +
	"nsDomainId\x18\x01 \x01(\x03R\n" +
	"nsDomainId\x12\x1a\n" +
	"\bnsZoneId\x18\x02 \x01(\x03R\bnsZoneId\"{\n" +
	"\x11ListNSKeysRequest\x12\x1e\n" +
	"\n" +
	"nsDomainId\x18\x01 \x01(\x03R\n" +
	"nsDomainId\x12\x1a\n" +
	"\bnsZoneId\x18\x02 \x01(\x03R\bnsZoneId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"7\n" +
	"\x12ListNSKeysResponse\x12!\n" +
	"\x06nsKeys\x18\x01 \x03(\v2\t.pb.NSKeyR\x06nsKeys\"M\n" +
	"\x1dListNSKeysAfterVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"C\n" +
	"\x1eListNSKeysAfterVersionResponse\x12!\n" +
	"\x06nsKeys\x18\x01 \x03(\v2\t.pb.NSKeyR\x06nsKeys2\xd7\x03\n" +
	"\fNSKeyService\x12>\n" +
	"\vcreateNSKey\x12\x16.pb.CreateNSKeyRequest\x1a\x17.pb.CreateNSKeyResponse\x125\n" +
	"\vupdateNSKey\x12\x16.pb.UpdateNSKeyRequest\x1a\x0e.pb.RPCSuccess\x125\n" +
	"\vdeleteNSKey\x12\x16.pb.DeleteNSKeyRequest\x1a\x0e.pb.RPCSuccess\x128\n" +
	"\tfindNSKey\x12\x14.pb.FindNSKeyRequest\x1a\x15.pb.FindNSKeyResponse\x12A\n" +
	"\x0ecountAllNSKeys\x12\x19.pb.CountAllNSKeysRequest\x1a\x14.pb.RPCCountResponse\x12;\n" +
	"\n" +
	"listNSKeys\x12\x15.pb.ListNSKeysRequest\x1a\x16.pb.ListNSKeysResponse\x12_\n" +
	"\x16listNSKeysAfterVersion\x12!.pb.ListNSKeysAfterVersionRequest\x1a\".pb.ListNSKeysAfterVersionResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_ns_key_proto_rawDescOnce sync.Once
	file_service_ns_key_proto_rawDescData []byte
)

func file_service_ns_key_proto_rawDescGZIP() []byte {
	file_service_ns_key_proto_rawDescOnce.Do(func() {
		file_service_ns_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_ns_key_proto_rawDesc), len(file_service_ns_key_proto_rawDesc)))
	})
	return file_service_ns_key_proto_rawDescData
}

var file_service_ns_key_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_ns_key_proto_goTypes = []any{
	(*CreateNSKeyRequest)(nil),             // 0: pb.CreateNSKeyRequest
	(*CreateNSKeyResponse)(nil),            // 1: pb.CreateNSKeyResponse
	(*UpdateNSKeyRequest)(nil),             // 2: pb.UpdateNSKeyRequest
	(*DeleteNSKeyRequest)(nil),             // 3: pb.DeleteNSKeyRequest
	(*FindNSKeyRequest)(nil),               // 4: pb.FindNSKeyRequest
	(*FindNSKeyResponse)(nil),              // 5: pb.FindNSKeyResponse
	(*CountAllNSKeysRequest)(nil),          // 6: pb.CountAllNSKeysRequest
	(*ListNSKeysRequest)(nil),              // 7: pb.ListNSKeysRequest
	(*ListNSKeysResponse)(nil),             // 8: pb.ListNSKeysResponse
	(*ListNSKeysAfterVersionRequest)(nil),  // 9: pb.ListNSKeysAfterVersionRequest
	(*ListNSKeysAfterVersionResponse)(nil), // 10: pb.ListNSKeysAfterVersionResponse
	(*NSKey)(nil),                          // 11: pb.NSKey
	(*RPCSuccess)(nil),                     // 12: pb.RPCSuccess
	(*RPCCountResponse)(nil),               // 13: pb.RPCCountResponse
}
var file_service_ns_key_proto_depIdxs = []int32{
	11, // 0: pb.FindNSKeyResponse.nsKey:type_name -> pb.NSKey
	11, // 1: pb.ListNSKeysResponse.nsKeys:type_name -> pb.NSKey
	11, // 2: pb.ListNSKeysAfterVersionResponse.nsKeys:type_name -> pb.NSKey
	0,  // 3: pb.NSKeyService.createNSKey:input_type -> pb.CreateNSKeyRequest
	2,  // 4: pb.NSKeyService.updateNSKey:input_type -> pb.UpdateNSKeyRequest
	3,  // 5: pb.NSKeyService.deleteNSKey:input_type -> pb.DeleteNSKeyRequest
	4,  // 6: pb.NSKeyService.findNSKey:input_type -> pb.FindNSKeyRequest
	6,  // 7: pb.NSKeyService.countAllNSKeys:input_type -> pb.CountAllNSKeysRequest
	7,  // 8: pb.NSKeyService.listNSKeys:input_type -> pb.ListNSKeysRequest
	9,  // 9: pb.NSKeyService.listNSKeysAfterVersion:input_type -> pb.ListNSKeysAfterVersionRequest
	1,  // 10: pb.NSKeyService.createNSKey:output_type -> pb.CreateNSKeyResponse
	12, // 11: pb.NSKeyService.updateNSKey:output_type -> pb.RPCSuccess
	12, // 12: pb.NSKeyService.deleteNSKey:output_type -> pb.RPCSuccess
	5,  // 13: pb.NSKeyService.findNSKey:output_type -> pb.FindNSKeyResponse
	13, // 14: pb.NSKeyService.countAllNSKeys:output_type -> pb.RPCCountResponse
	8,  // 15: pb.NSKeyService.listNSKeys:output_type -> pb.ListNSKeysResponse
	10, // 16: pb.NSKeyService.listNSKeysAfterVersion:output_type -> pb.ListNSKeysAfterVersionResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_ns_key_proto_init() }
func file_service_ns_key_proto_init() {
	if File_service_ns_key_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	file_models_model_ns_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_ns_key_proto_rawDesc), len(file_service_ns_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_ns_key_proto_goTypes,
		DependencyIndexes: file_service_ns_key_proto_depIdxs,
		MessageInfos:      file_service_ns_key_proto_msgTypes,
	}.Build()
	File_service_ns_key_proto = out.File
	file_service_ns_key_proto_goTypes = nil
	file_service_ns_key_proto_depIdxs = nil
}
