// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_ns_access_log.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建访问日志
type CreateNSAccessLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsAccessLogs  []*NSAccessLog         `protobuf:"bytes,1,rep,name=nsAccessLogs,proto3" json:"nsAccessLogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNSAccessLogsRequest) Reset() {
	*x = CreateNSAccessLogsRequest{}
	mi := &file_service_ns_access_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNSAccessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNSAccessLogsRequest) ProtoMessage() {}

func (x *CreateNSAccessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_access_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNSAccessLogsRequest.ProtoReflect.Descriptor instead.
func (*CreateNSAccessLogsRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_access_log_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNSAccessLogsRequest) GetNsAccessLogs() []*NSAccessLog {
	if x != nil {
		return x.NsAccessLogs
	}
	return nil
}

type CreateNSAccessLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNSAccessLogsResponse) Reset() {
	*x = CreateNSAccessLogsResponse{}
	mi := &file_service_ns_access_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNSAccessLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNSAccessLogsResponse) ProtoMessage() {}

func (x *CreateNSAccessLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_access_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNSAccessLogsResponse.ProtoReflect.Descriptor instead.
func (*CreateNSAccessLogsResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_access_log_proto_rawDescGZIP(), []int{1}
}

// 列出往前的单页访问日志
type ListNSAccessLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`      // 上一页请求ID，可选
	NsClusterId   int64                  `protobuf:"varint,9,opt,name=nsClusterId,proto3" json:"nsClusterId,omitempty"` // 集群
	NsNodeId      int64                  `protobuf:"varint,2,opt,name=nsNodeId,proto3" json:"nsNodeId,omitempty"`       // 节点ID
	NsDomainId    int64                  `protobuf:"varint,3,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`   // 域名ID
	NsRecordId    int64                  `protobuf:"varint,4,opt,name=nsRecordId,proto3" json:"nsRecordId,omitempty"`   // 记录ID
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`               // 单页条数
	Day           string                 `protobuf:"bytes,6,opt,name=day,proto3" json:"day,omitempty"`                  // 日期，格式YYYYMMDD
	Reverse       bool                   `protobuf:"varint,7,opt,name=reverse,proto3" json:"reverse,omitempty"`         // 是否反向查找，可选
	Keyword       string                 `protobuf:"bytes,8,opt,name=keyword,proto3" json:"keyword,omitempty"`          // 关键词
	RecordType    string                 `protobuf:"bytes,10,opt,name=recordType,proto3" json:"recordType,omitempty"`   // 记录类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNSAccessLogsRequest) Reset() {
	*x = ListNSAccessLogsRequest{}
	mi := &file_service_ns_access_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNSAccessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSAccessLogsRequest) ProtoMessage() {}

func (x *ListNSAccessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_access_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSAccessLogsRequest.ProtoReflect.Descriptor instead.
func (*ListNSAccessLogsRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_access_log_proto_rawDescGZIP(), []int{2}
}

func (x *ListNSAccessLogsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListNSAccessLogsRequest) GetNsClusterId() int64 {
	if x != nil {
		return x.NsClusterId
	}
	return 0
}

func (x *ListNSAccessLogsRequest) GetNsNodeId() int64 {
	if x != nil {
		return x.NsNodeId
	}
	return 0
}

func (x *ListNSAccessLogsRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *ListNSAccessLogsRequest) GetNsRecordId() int64 {
	if x != nil {
		return x.NsRecordId
	}
	return 0
}

func (x *ListNSAccessLogsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListNSAccessLogsRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *ListNSAccessLogsRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *ListNSAccessLogsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListNSAccessLogsRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

type ListNSAccessLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsAccessLogs  []*NSAccessLog         `protobuf:"bytes,1,rep,name=nsAccessLogs,proto3" json:"nsAccessLogs,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNSAccessLogsResponse) Reset() {
	*x = ListNSAccessLogsResponse{}
	mi := &file_service_ns_access_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNSAccessLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSAccessLogsResponse) ProtoMessage() {}

func (x *ListNSAccessLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_access_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSAccessLogsResponse.ProtoReflect.Descriptor instead.
func (*ListNSAccessLogsResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_access_log_proto_rawDescGZIP(), []int{3}
}

func (x *ListNSAccessLogsResponse) GetNsAccessLogs() []*NSAccessLog {
	if x != nil {
		return x.NsAccessLogs
	}
	return nil
}

func (x *ListNSAccessLogsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListNSAccessLogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 查找单个日志
type FindNSAccessLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNSAccessLogRequest) Reset() {
	*x = FindNSAccessLogRequest{}
	mi := &file_service_ns_access_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSAccessLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSAccessLogRequest) ProtoMessage() {}

func (x *FindNSAccessLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_access_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSAccessLogRequest.ProtoReflect.Descriptor instead.
func (*FindNSAccessLogRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_access_log_proto_rawDescGZIP(), []int{4}
}

func (x *FindNSAccessLogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type FindNSAccessLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsAccessLog   *NSAccessLog           `protobuf:"bytes,1,opt,name=nsAccessLog,proto3" json:"nsAccessLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNSAccessLogResponse) Reset() {
	*x = FindNSAccessLogResponse{}
	mi := &file_service_ns_access_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNSAccessLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSAccessLogResponse) ProtoMessage() {}

func (x *FindNSAccessLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_access_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSAccessLogResponse.ProtoReflect.Descriptor instead.
func (*FindNSAccessLogResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_access_log_proto_rawDescGZIP(), []int{5}
}

func (x *FindNSAccessLogResponse) GetNsAccessLog() *NSAccessLog {
	if x != nil {
		return x.NsAccessLog
	}
	return nil
}

var File_service_ns_access_log_proto protoreflect.FileDescriptor

const file_service_ns_access_log_proto_rawDesc = "" +
	"\n" +
	"\x1bservice_ns_access_log.proto\x12\x02pb\x1a models/model_ns_access_log.proto\"P\n" +
	"\x19CreateNSAccessLogsRequest\x123\n" +
	"\fnsAccessLogs\x18\x01 \x03(\v2\x0f.pb.NSAccessLogR\fnsAccessLogs\"\x1c\n" +
	"\x1aCreateNSAccessLogsResponse\"\xaf\x02\n" +
	"\x17ListNSAccessLogsRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12 \n" +
	"\vnsClusterId\x18\t \x01(\x03R\vnsClusterId\x12\x1a\n" +
	"\bnsNodeId\x18\x02 \x01(\x03R\bnsNodeId\x12\x1e\n" +
	"\n" +
	"nsDomainId\x18\x03 \x01(\x03R\n" +
	"nsDomainId\x12\x1e\n" +
	"\n" +
	"nsRecordId\x18\x04 \x01(\x03R\n" +
	"nsRecordId\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x10\n" +
	"\x03day\x18\x06 \x01(\tR\x03day\x12\x18\n" +
	"\areverse\x18\a \x01(\bR\areverse\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\x12\x1e\n" +
	"\n" +
	"recordType\x18\n" +
	" \x01(\tR\n" +
	"recordType\"\x87\x01\n" +
	"\x18ListNSAccessLogsResponse\x123\n" +
	"\fnsAccessLogs\x18\x01 \x03(\v2\x0f.pb.NSAccessLogR\fnsAccessLogs\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\ahasMore\x18\x03 \x01(\bR\ahasMore\"6\n" +
	"\x16FindNSAccessLogRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"L\n" +
	"\x17FindNSAccessLogResponse\x121\n" +
	"\vnsAccessLog\x18\x01 \x01(\v2\x0f.pb.NSAccessLogR\vnsAccessLog2\x84\x02\n" +
	"\x12NSAccessLogService\x12S\n" +
	"\x12createNSAccessLogs\x12\x1d.pb.CreateNSAccessLogsRequest\x1a\x1e.pb.CreateNSAccessLogsResponse\x12M\n" +
	"\x10listNSAccessLogs\x12\x1b.pb.ListNSAccessLogsRequest\x1a\x1c.pb.ListNSAccessLogsResponse\x12J\n" +
	"\x0ffindNSAccessLog\x12\x1a.pb.FindNSAccessLogRequest\x1a\x1b.pb.FindNSAccessLogResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_ns_access_log_proto_rawDescOnce sync.Once
	file_service_ns_access_log_proto_rawDescData []byte
)

func file_service_ns_access_log_proto_rawDescGZIP() []byte {
	file_service_ns_access_log_proto_rawDescOnce.Do(func() {
		file_service_ns_access_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_ns_access_log_proto_rawDesc), len(file_service_ns_access_log_proto_rawDesc)))
	})
	return file_service_ns_access_log_proto_rawDescData
}

var file_service_ns_access_log_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_ns_access_log_proto_goTypes = []any{
	(*CreateNSAccessLogsRequest)(nil),  // 0: pb.CreateNSAccessLogsRequest
	(*CreateNSAccessLogsResponse)(nil), // 1: pb.CreateNSAccessLogsResponse
	(*ListNSAccessLogsRequest)(nil),    // 2: pb.ListNSAccessLogsRequest
	(*ListNSAccessLogsResponse)(nil),   // 3: pb.ListNSAccessLogsResponse
	(*FindNSAccessLogRequest)(nil),     // 4: pb.FindNSAccessLogRequest
	(*FindNSAccessLogResponse)(nil),    // 5: pb.FindNSAccessLogResponse
	(*NSAccessLog)(nil),                // 6: pb.NSAccessLog
}
var file_service_ns_access_log_proto_depIdxs = []int32{
	6, // 0: pb.CreateNSAccessLogsRequest.nsAccessLogs:type_name -> pb.NSAccessLog
	6, // 1: pb.ListNSAccessLogsResponse.nsAccessLogs:type_name -> pb.NSAccessLog
	6, // 2: pb.FindNSAccessLogResponse.nsAccessLog:type_name -> pb.NSAccessLog
	0, // 3: pb.NSAccessLogService.createNSAccessLogs:input_type -> pb.CreateNSAccessLogsRequest
	2, // 4: pb.NSAccessLogService.listNSAccessLogs:input_type -> pb.ListNSAccessLogsRequest
	4, // 5: pb.NSAccessLogService.findNSAccessLog:input_type -> pb.FindNSAccessLogRequest
	1, // 6: pb.NSAccessLogService.createNSAccessLogs:output_type -> pb.CreateNSAccessLogsResponse
	3, // 7: pb.NSAccessLogService.listNSAccessLogs:output_type -> pb.ListNSAccessLogsResponse
	5, // 8: pb.NSAccessLogService.findNSAccessLog:output_type -> pb.FindNSAccessLogResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_ns_access_log_proto_init() }
func file_service_ns_access_log_proto_init() {
	if File_service_ns_access_log_proto != nil {
		return
	}
	file_models_model_ns_access_log_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_ns_access_log_proto_rawDesc), len(file_service_ns_access_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_ns_access_log_proto_goTypes,
		DependencyIndexes: file_service_ns_access_log_proto_depIdxs,
		MessageInfos:      file_service_ns_access_log_proto_msgTypes,
	}.Build()
	File_service_ns_access_log_proto = out.File
	file_service_ns_access_log_proto_goTypes = nil
	file_service_ns_access_log_proto_depIdxs = nil
}
