// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_node_ip_address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建IP地址
type CreateNodeIPAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         int64                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`                        // 节点ID
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                             // 角色：node：边缘节点，dns：智能DNS节点
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // 名称
	Ip             string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                 // IP地址
	CanAccess      bool                   `protobuf:"varint,5,opt,name=canAccess,proto3" json:"canAccess,omitempty"`                  // 是否能够访问
	IsUp           bool                   `protobuf:"varint,6,opt,name=isUp,proto3" json:"isUp,omitempty"`                            // 是否上线
	NodeClusterIds []int64                `protobuf:"varint,7,rep,packed,name=nodeClusterIds,proto3" json:"nodeClusterIds,omitempty"` // 可选项，所属集群ID列表，如果没有指定，则表示应用于节点所属的所有集群
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNodeIPAddressRequest) Reset() {
	*x = CreateNodeIPAddressRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeIPAddressRequest) ProtoMessage() {}

func (x *CreateNodeIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeIPAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeIPAddressRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CreateNodeIPAddressRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateNodeIPAddressRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeIPAddressRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CreateNodeIPAddressRequest) GetCanAccess() bool {
	if x != nil {
		return x.CanAccess
	}
	return false
}

func (x *CreateNodeIPAddressRequest) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *CreateNodeIPAddressRequest) GetNodeClusterIds() []int64 {
	if x != nil {
		return x.NodeClusterIds
	}
	return nil
}

type CreateNodeIPAddressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateNodeIPAddressResponse) Reset() {
	*x = CreateNodeIPAddressResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeIPAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeIPAddressResponse) ProtoMessage() {}

func (x *CreateNodeIPAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeIPAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeIPAddressResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeIPAddressResponse) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

// 批量创建IP地址
type CreateNodeIPAddressesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         int64                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IpList         []string               `protobuf:"bytes,4,rep,name=ipList,proto3" json:"ipList,omitempty"`
	CanAccess      bool                   `protobuf:"varint,5,opt,name=canAccess,proto3" json:"canAccess,omitempty"`
	IsUp           bool                   `protobuf:"varint,6,opt,name=isUp,proto3" json:"isUp,omitempty"`
	GroupValue     string                 `protobuf:"bytes,7,opt,name=groupValue,proto3" json:"groupValue,omitempty"`
	NodeClusterIds []int64                `protobuf:"varint,8,rep,packed,name=nodeClusterIds,proto3" json:"nodeClusterIds,omitempty"` // 可选项，所属集群ID列表，如果没有指定，则表示应用于节点所属的所有集群
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNodeIPAddressesRequest) Reset() {
	*x = CreateNodeIPAddressesRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeIPAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeIPAddressesRequest) ProtoMessage() {}

func (x *CreateNodeIPAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeIPAddressesRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeIPAddressesRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNodeIPAddressesRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CreateNodeIPAddressesRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateNodeIPAddressesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeIPAddressesRequest) GetIpList() []string {
	if x != nil {
		return x.IpList
	}
	return nil
}

func (x *CreateNodeIPAddressesRequest) GetCanAccess() bool {
	if x != nil {
		return x.CanAccess
	}
	return false
}

func (x *CreateNodeIPAddressesRequest) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *CreateNodeIPAddressesRequest) GetGroupValue() string {
	if x != nil {
		return x.GroupValue
	}
	return ""
}

func (x *CreateNodeIPAddressesRequest) GetNodeClusterIds() []int64 {
	if x != nil {
		return x.NodeClusterIds
	}
	return nil
}

type CreateNodeIPAddressesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressIds []int64                `protobuf:"varint,1,rep,packed,name=nodeIPAddressIds,proto3" json:"nodeIPAddressIds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateNodeIPAddressesResponse) Reset() {
	*x = CreateNodeIPAddressesResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeIPAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeIPAddressesResponse) ProtoMessage() {}

func (x *CreateNodeIPAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeIPAddressesResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeIPAddressesResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNodeIPAddressesResponse) GetNodeIPAddressIds() []int64 {
	if x != nil {
		return x.NodeIPAddressIds
	}
	return nil
}

// 修改IP地址
type UpdateNodeIPAddressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"` // IP地址ID
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ip              string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	CanAccess       bool                   `protobuf:"varint,4,opt,name=canAccess,proto3" json:"canAccess,omitempty"`          // 是否能够访问
	IsOn            bool                   `protobuf:"varint,5,opt,name=isOn,proto3" json:"isOn,omitempty"`                    // 是否启用
	IsUp            bool                   `protobuf:"varint,6,opt,name=isUp,proto3" json:"isUp,omitempty"`                    // 是否上线
	ClusterIds      []int64                `protobuf:"varint,7,rep,packed,name=clusterIds,proto3" json:"clusterIds,omitempty"` // 可选项，所属集群ID列表，如果没有指定，则表示应用于节点所属的所有集群
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNodeIPAddressRequest) Reset() {
	*x = UpdateNodeIPAddressRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeIPAddressRequest) ProtoMessage() {}

func (x *UpdateNodeIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeIPAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNodeIPAddressRequest) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

func (x *UpdateNodeIPAddressRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNodeIPAddressRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UpdateNodeIPAddressRequest) GetCanAccess() bool {
	if x != nil {
		return x.CanAccess
	}
	return false
}

func (x *UpdateNodeIPAddressRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *UpdateNodeIPAddressRequest) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *UpdateNodeIPAddressRequest) GetClusterIds() []int64 {
	if x != nil {
		return x.ClusterIds
	}
	return nil
}

// 修改IP地址所属节点
type UpdateNodeIPAddressNodeIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"`
	NodeId          int64                  `protobuf:"varint,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNodeIPAddressNodeIdRequest) Reset() {
	*x = UpdateNodeIPAddressNodeIdRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeIPAddressNodeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeIPAddressNodeIdRequest) ProtoMessage() {}

func (x *UpdateNodeIPAddressNodeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeIPAddressNodeIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeIPAddressNodeIdRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNodeIPAddressNodeIdRequest) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

func (x *UpdateNodeIPAddressNodeIdRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// 禁用单个IP地址
type DisableNodeIPAddressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DisableNodeIPAddressRequest) Reset() {
	*x = DisableNodeIPAddressRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableNodeIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableNodeIPAddressRequest) ProtoMessage() {}

func (x *DisableNodeIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableNodeIPAddressRequest.ProtoReflect.Descriptor instead.
func (*DisableNodeIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{6}
}

func (x *DisableNodeIPAddressRequest) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

type DisableNodeIPAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableNodeIPAddressResponse) Reset() {
	*x = DisableNodeIPAddressResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableNodeIPAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableNodeIPAddressResponse) ProtoMessage() {}

func (x *DisableNodeIPAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableNodeIPAddressResponse.ProtoReflect.Descriptor instead.
func (*DisableNodeIPAddressResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{7}
}

// 禁用节点的所有IP地址
type DisableAllNodeIPAddressesWithNodeIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAllNodeIPAddressesWithNodeIdRequest) Reset() {
	*x = DisableAllNodeIPAddressesWithNodeIdRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAllNodeIPAddressesWithNodeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAllNodeIPAddressesWithNodeIdRequest) ProtoMessage() {}

func (x *DisableAllNodeIPAddressesWithNodeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAllNodeIPAddressesWithNodeIdRequest.ProtoReflect.Descriptor instead.
func (*DisableAllNodeIPAddressesWithNodeIdRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{8}
}

func (x *DisableAllNodeIPAddressesWithNodeIdRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *DisableAllNodeIPAddressesWithNodeIdRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DisableAllNodeIPAddressesWithNodeIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAllNodeIPAddressesWithNodeIdResponse) Reset() {
	*x = DisableAllNodeIPAddressesWithNodeIdResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAllNodeIPAddressesWithNodeIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAllNodeIPAddressesWithNodeIdResponse) ProtoMessage() {}

func (x *DisableAllNodeIPAddressesWithNodeIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAllNodeIPAddressesWithNodeIdResponse.ProtoReflect.Descriptor instead.
func (*DisableAllNodeIPAddressesWithNodeIdResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{9}
}

// 查找单个IP地址
type FindEnabledNodeIPAddressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindEnabledNodeIPAddressRequest) Reset() {
	*x = FindEnabledNodeIPAddressRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledNodeIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledNodeIPAddressRequest) ProtoMessage() {}

func (x *FindEnabledNodeIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledNodeIPAddressRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledNodeIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{10}
}

func (x *FindEnabledNodeIPAddressRequest) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

type FindEnabledNodeIPAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddress *NodeIPAddress         `protobuf:"bytes,1,opt,name=nodeIPAddress,proto3" json:"nodeIPAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledNodeIPAddressResponse) Reset() {
	*x = FindEnabledNodeIPAddressResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledNodeIPAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledNodeIPAddressResponse) ProtoMessage() {}

func (x *FindEnabledNodeIPAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledNodeIPAddressResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledNodeIPAddressResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{11}
}

func (x *FindEnabledNodeIPAddressResponse) GetNodeIPAddress() *NodeIPAddress {
	if x != nil {
		return x.NodeIPAddress
	}
	return nil
}

// 查找节点的所有地址
type FindAllEnabledNodeIPAddressesWithNodeIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdRequest) Reset() {
	*x = FindAllEnabledNodeIPAddressesWithNodeIdRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEnabledNodeIPAddressesWithNodeIdRequest) ProtoMessage() {}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEnabledNodeIPAddressesWithNodeIdRequest.ProtoReflect.Descriptor instead.
func (*FindAllEnabledNodeIPAddressesWithNodeIdRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{12}
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type FindAllEnabledNodeIPAddressesWithNodeIdResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddresses []*NodeIPAddress       `protobuf:"bytes,1,rep,name=nodeIPAddresses,proto3" json:"nodeIPAddresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdResponse) Reset() {
	*x = FindAllEnabledNodeIPAddressesWithNodeIdResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEnabledNodeIPAddressesWithNodeIdResponse) ProtoMessage() {}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEnabledNodeIPAddressesWithNodeIdResponse.ProtoReflect.Descriptor instead.
func (*FindAllEnabledNodeIPAddressesWithNodeIdResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{13}
}

func (x *FindAllEnabledNodeIPAddressesWithNodeIdResponse) GetNodeIPAddresses() []*NodeIPAddress {
	if x != nil {
		return x.NodeIPAddresses
	}
	return nil
}

// 计算IP地址数量
type CountAllEnabledNodeIPAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusterId int64                  `protobuf:"varint,1,opt,name=nodeClusterId,proto3" json:"nodeClusterId,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	UpState       int32                  `protobuf:"varint,3,opt,name=upState,proto3" json:"upState,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountAllEnabledNodeIPAddressesRequest) Reset() {
	*x = CountAllEnabledNodeIPAddressesRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountAllEnabledNodeIPAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountAllEnabledNodeIPAddressesRequest) ProtoMessage() {}

func (x *CountAllEnabledNodeIPAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountAllEnabledNodeIPAddressesRequest.ProtoReflect.Descriptor instead.
func (*CountAllEnabledNodeIPAddressesRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{14}
}

func (x *CountAllEnabledNodeIPAddressesRequest) GetNodeClusterId() int64 {
	if x != nil {
		return x.NodeClusterId
	}
	return 0
}

func (x *CountAllEnabledNodeIPAddressesRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CountAllEnabledNodeIPAddressesRequest) GetUpState() int32 {
	if x != nil {
		return x.UpState
	}
	return 0
}

func (x *CountAllEnabledNodeIPAddressesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 列出单页IP地址
type ListEnabledNodeIPAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusterId int64                  `protobuf:"varint,1,opt,name=nodeClusterId,proto3" json:"nodeClusterId,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	UpState       int32                  `protobuf:"varint,3,opt,name=upState,proto3" json:"upState,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnabledNodeIPAddressesRequest) Reset() {
	*x = ListEnabledNodeIPAddressesRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnabledNodeIPAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnabledNodeIPAddressesRequest) ProtoMessage() {}

func (x *ListEnabledNodeIPAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnabledNodeIPAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListEnabledNodeIPAddressesRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{15}
}

func (x *ListEnabledNodeIPAddressesRequest) GetNodeClusterId() int64 {
	if x != nil {
		return x.NodeClusterId
	}
	return 0
}

func (x *ListEnabledNodeIPAddressesRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListEnabledNodeIPAddressesRequest) GetUpState() int32 {
	if x != nil {
		return x.UpState
	}
	return 0
}

func (x *ListEnabledNodeIPAddressesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListEnabledNodeIPAddressesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListEnabledNodeIPAddressesRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListEnabledNodeIPAddressesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddresses []*NodeIPAddress       `protobuf:"bytes,1,rep,name=nodeIPAddresses,proto3" json:"nodeIPAddresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListEnabledNodeIPAddressesResponse) Reset() {
	*x = ListEnabledNodeIPAddressesResponse{}
	mi := &file_service_node_ip_address_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnabledNodeIPAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnabledNodeIPAddressesResponse) ProtoMessage() {}

func (x *ListEnabledNodeIPAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnabledNodeIPAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListEnabledNodeIPAddressesResponse) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{16}
}

func (x *ListEnabledNodeIPAddressesResponse) GetNodeIPAddresses() []*NodeIPAddress {
	if x != nil {
		return x.NodeIPAddresses
	}
	return nil
}

// 设置上下线状态
type UpdateNodeIPAddressIsUpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"`
	IsUp            bool                   `protobuf:"varint,2,opt,name=isUp,proto3" json:"isUp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNodeIPAddressIsUpRequest) Reset() {
	*x = UpdateNodeIPAddressIsUpRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeIPAddressIsUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeIPAddressIsUpRequest) ProtoMessage() {}

func (x *UpdateNodeIPAddressIsUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeIPAddressIsUpRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeIPAddressIsUpRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateNodeIPAddressIsUpRequest) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

func (x *UpdateNodeIPAddressIsUpRequest) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

// 还原备用IP状态
type RestoreNodeIPAddressBackupIPRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIPAddressId int64                  `protobuf:"varint,1,opt,name=nodeIPAddressId,proto3" json:"nodeIPAddressId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreNodeIPAddressBackupIPRequest) Reset() {
	*x = RestoreNodeIPAddressBackupIPRequest{}
	mi := &file_service_node_ip_address_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreNodeIPAddressBackupIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreNodeIPAddressBackupIPRequest) ProtoMessage() {}

func (x *RestoreNodeIPAddressBackupIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_ip_address_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreNodeIPAddressBackupIPRequest.ProtoReflect.Descriptor instead.
func (*RestoreNodeIPAddressBackupIPRequest) Descriptor() ([]byte, []int) {
	return file_service_node_ip_address_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreNodeIPAddressBackupIPRequest) GetNodeIPAddressId() int64 {
	if x != nil {
		return x.NodeIPAddressId
	}
	return 0
}

var File_service_node_ip_address_proto protoreflect.FileDescriptor

const file_service_node_ip_address_proto_rawDesc = "" +
	"\n" +
	"\x1dservice_node_ip_address.proto\x12\x02pb\x1a\"models/model_node_ip_address.proto\x1a\x19models/rpc_messages.proto\"\xc6\x01\n" +
	"\x1aCreateNodeIPAddressRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1c\n" +
	"\tcanAccess\x18\x05 \x01(\bR\tcanAccess\x12\x12\n" +
	"\x04isUp\x18\x06 \x01(\bR\x04isUp\x12&\n" +
	"\x0enodeClusterIds\x18\a \x03(\x03R\x0enodeClusterIds\"G\n" +
	"\x1bCreateNodeIPAddressResponse\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId\"\xf0\x01\n" +
	"\x1cCreateNodeIPAddressesRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06ipList\x18\x04 \x03(\tR\x06ipList\x12\x1c\n" +
	"\tcanAccess\x18\x05 \x01(\bR\tcanAccess\x12\x12\n" +
	"\x04isUp\x18\x06 \x01(\bR\x04isUp\x12\x1e\n" +
	"\n" +
	"groupValue\x18\a \x01(\tR\n" +
	"groupValue\x12&\n" +
	"\x0enodeClusterIds\x18\b \x03(\x03R\x0enodeClusterIds\"K\n" +
	"\x1dCreateNodeIPAddressesResponse\x12*\n" +
	"\x10nodeIPAddressIds\x18\x01 \x03(\x03R\x10nodeIPAddressIds\"\xd0\x01\n" +
	"\x1aUpdateNodeIPAddressRequest\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1c\n" +
	"\tcanAccess\x18\x04 \x01(\bR\tcanAccess\x12\x12\n" +
	"\x04isOn\x18\x05 \x01(\bR\x04isOn\x12\x12\n" +
	"\x04isUp\x18\x06 \x01(\bR\x04isUp\x12\x1e\n" +
	"\n" +
	"clusterIds\x18\a \x03(\x03R\n" +
	"clusterIds\"d\n" +
	" UpdateNodeIPAddressNodeIdRequest\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\x03R\x06nodeId\"G\n" +
	"\x1bDisableNodeIPAddressRequest\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId\"\x1e\n" +
	"\x1cDisableNodeIPAddressResponse\"X\n" +
	"*DisableAllNodeIPAddressesWithNodeIdRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"-\n" +
	"+DisableAllNodeIPAddressesWithNodeIdResponse\"K\n" +
	"\x1fFindEnabledNodeIPAddressRequest\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId\"[\n" +
	" FindEnabledNodeIPAddressResponse\x127\n" +
	"\rnodeIPAddress\x18\x01 \x01(\v2\x11.pb.NodeIPAddressR\rnodeIPAddress\"\\\n" +
	".FindAllEnabledNodeIPAddressesWithNodeIdRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"n\n" +
	"/FindAllEnabledNodeIPAddressesWithNodeIdResponse\x12;\n" +
	"\x0fnodeIPAddresses\x18\x01 \x03(\v2\x11.pb.NodeIPAddressR\x0fnodeIPAddresses\"\x95\x01\n" +
	"%CountAllEnabledNodeIPAddressesRequest\x12$\n" +
	"\rnodeClusterId\x18\x01 \x01(\x03R\rnodeClusterId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\aupState\x18\x03 \x01(\x05R\aupState\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\"\xbd\x01\n" +
	"!ListEnabledNodeIPAddressesRequest\x12$\n" +
	"\rnodeClusterId\x18\x01 \x01(\x03R\rnodeClusterId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\aupState\x18\x03 \x01(\x05R\aupState\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"a\n" +
	"\"ListEnabledNodeIPAddressesResponse\x12;\n" +
	"\x0fnodeIPAddresses\x18\x01 \x03(\v2\x11.pb.NodeIPAddressR\x0fnodeIPAddresses\"^\n" +
	"\x1eUpdateNodeIPAddressIsUpRequest\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId\x12\x12\n" +
	"\x04isUp\x18\x02 \x01(\bR\x04isUp\"O\n" +
	"#RestoreNodeIPAddressBackupIPRequest\x12(\n" +
	"\x0fnodeIPAddressId\x18\x01 \x01(\x03R\x0fnodeIPAddressId2\xbe\t\n" +
	"\x14NodeIPAddressService\x12V\n" +
	"\x13createNodeIPAddress\x12\x1e.pb.CreateNodeIPAddressRequest\x1a\x1f.pb.CreateNodeIPAddressResponse\x12\\\n" +
	"\x15createNodeIPAddresses\x12 .pb.CreateNodeIPAddressesRequest\x1a!.pb.CreateNodeIPAddressesResponse\x12E\n" +
	"\x13updateNodeIPAddress\x12\x1e.pb.UpdateNodeIPAddressRequest\x1a\x0e.pb.RPCSuccess\x12Q\n" +
	"\x19updateNodeIPAddressNodeId\x12$.pb.UpdateNodeIPAddressNodeIdRequest\x1a\x0e.pb.RPCSuccess\x12Y\n" +
	"\x14disableNodeIPAddress\x12\x1f.pb.DisableNodeIPAddressRequest\x1a .pb.DisableNodeIPAddressResponse\x12\x86\x01\n" +
	"#disableAllNodeIPAddressesWithNodeId\x12..pb.DisableAllNodeIPAddressesWithNodeIdRequest\x1a/.pb.DisableAllNodeIPAddressesWithNodeIdResponse\x12e\n" +
	"\x18findEnabledNodeIPAddress\x12#.pb.FindEnabledNodeIPAddressRequest\x1a$.pb.FindEnabledNodeIPAddressResponse\x12\x92\x01\n" +
	"'findAllEnabledNodeIPAddressesWithNodeId\x122.pb.FindAllEnabledNodeIPAddressesWithNodeIdRequest\x1a3.pb.FindAllEnabledNodeIPAddressesWithNodeIdResponse\x12a\n" +
	"\x1ecountAllEnabledNodeIPAddresses\x12).pb.CountAllEnabledNodeIPAddressesRequest\x1a\x14.pb.RPCCountResponse\x12k\n" +
	"\x1alistEnabledNodeIPAddresses\x12%.pb.ListEnabledNodeIPAddressesRequest\x1a&.pb.ListEnabledNodeIPAddressesResponse\x12M\n" +
	"\x17updateNodeIPAddressIsUp\x12\".pb.UpdateNodeIPAddressIsUpRequest\x1a\x0e.pb.RPCSuccess\x12W\n" +
	"\x1crestoreNodeIPAddressBackupIP\x12'.pb.RestoreNodeIPAddressBackupIPRequest\x1a\x0e.pb.RPCSuccessB\x06Z\x04./pbb\x06proto3"

var (
	file_service_node_ip_address_proto_rawDescOnce sync.Once
	file_service_node_ip_address_proto_rawDescData []byte
)

func file_service_node_ip_address_proto_rawDescGZIP() []byte {
	file_service_node_ip_address_proto_rawDescOnce.Do(func() {
		file_service_node_ip_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_node_ip_address_proto_rawDesc), len(file_service_node_ip_address_proto_rawDesc)))
	})
	return file_service_node_ip_address_proto_rawDescData
}

var file_service_node_ip_address_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_service_node_ip_address_proto_goTypes = []any{
	(*CreateNodeIPAddressRequest)(nil),                      // 0: pb.CreateNodeIPAddressRequest
	(*CreateNodeIPAddressResponse)(nil),                     // 1: pb.CreateNodeIPAddressResponse
	(*CreateNodeIPAddressesRequest)(nil),                    // 2: pb.CreateNodeIPAddressesRequest
	(*CreateNodeIPAddressesResponse)(nil),                   // 3: pb.CreateNodeIPAddressesResponse
	(*UpdateNodeIPAddressRequest)(nil),                      // 4: pb.UpdateNodeIPAddressRequest
	(*UpdateNodeIPAddressNodeIdRequest)(nil),                // 5: pb.UpdateNodeIPAddressNodeIdRequest
	(*DisableNodeIPAddressRequest)(nil),                     // 6: pb.DisableNodeIPAddressRequest
	(*DisableNodeIPAddressResponse)(nil),                    // 7: pb.DisableNodeIPAddressResponse
	(*DisableAllNodeIPAddressesWithNodeIdRequest)(nil),      // 8: pb.DisableAllNodeIPAddressesWithNodeIdRequest
	(*DisableAllNodeIPAddressesWithNodeIdResponse)(nil),     // 9: pb.DisableAllNodeIPAddressesWithNodeIdResponse
	(*FindEnabledNodeIPAddressRequest)(nil),                 // 10: pb.FindEnabledNodeIPAddressRequest
	(*FindEnabledNodeIPAddressResponse)(nil),                // 11: pb.FindEnabledNodeIPAddressResponse
	(*FindAllEnabledNodeIPAddressesWithNodeIdRequest)(nil),  // 12: pb.FindAllEnabledNodeIPAddressesWithNodeIdRequest
	(*FindAllEnabledNodeIPAddressesWithNodeIdResponse)(nil), // 13: pb.FindAllEnabledNodeIPAddressesWithNodeIdResponse
	(*CountAllEnabledNodeIPAddressesRequest)(nil),           // 14: pb.CountAllEnabledNodeIPAddressesRequest
	(*ListEnabledNodeIPAddressesRequest)(nil),               // 15: pb.ListEnabledNodeIPAddressesRequest
	(*ListEnabledNodeIPAddressesResponse)(nil),              // 16: pb.ListEnabledNodeIPAddressesResponse
	(*UpdateNodeIPAddressIsUpRequest)(nil),                  // 17: pb.UpdateNodeIPAddressIsUpRequest
	(*RestoreNodeIPAddressBackupIPRequest)(nil),             // 18: pb.RestoreNodeIPAddressBackupIPRequest
	(*NodeIPAddress)(nil),                                   // 19: pb.NodeIPAddress
	(*RPCSuccess)(nil),                                      // 20: pb.RPCSuccess
	(*RPCCountResponse)(nil),                                // 21: pb.RPCCountResponse
}
var file_service_node_ip_address_proto_depIdxs = []int32{
	19, // 0: pb.FindEnabledNodeIPAddressResponse.nodeIPAddress:type_name -> pb.NodeIPAddress
	19, // 1: pb.FindAllEnabledNodeIPAddressesWithNodeIdResponse.nodeIPAddresses:type_name -> pb.NodeIPAddress
	19, // 2: pb.ListEnabledNodeIPAddressesResponse.nodeIPAddresses:type_name -> pb.NodeIPAddress
	0,  // 3: pb.NodeIPAddressService.createNodeIPAddress:input_type -> pb.CreateNodeIPAddressRequest
	2,  // 4: pb.NodeIPAddressService.createNodeIPAddresses:input_type -> pb.CreateNodeIPAddressesRequest
	4,  // 5: pb.NodeIPAddressService.updateNodeIPAddress:input_type -> pb.UpdateNodeIPAddressRequest
	5,  // 6: pb.NodeIPAddressService.updateNodeIPAddressNodeId:input_type -> pb.UpdateNodeIPAddressNodeIdRequest
	6,  // 7: pb.NodeIPAddressService.disableNodeIPAddress:input_type -> pb.DisableNodeIPAddressRequest
	8,  // 8: pb.NodeIPAddressService.disableAllNodeIPAddressesWithNodeId:input_type -> pb.DisableAllNodeIPAddressesWithNodeIdRequest
	10, // 9: pb.NodeIPAddressService.findEnabledNodeIPAddress:input_type -> pb.FindEnabledNodeIPAddressRequest
	12, // 10: pb.NodeIPAddressService.findAllEnabledNodeIPAddressesWithNodeId:input_type -> pb.FindAllEnabledNodeIPAddressesWithNodeIdRequest
	14, // 11: pb.NodeIPAddressService.countAllEnabledNodeIPAddresses:input_type -> pb.CountAllEnabledNodeIPAddressesRequest
	15, // 12: pb.NodeIPAddressService.listEnabledNodeIPAddresses:input_type -> pb.ListEnabledNodeIPAddressesRequest
	17, // 13: pb.NodeIPAddressService.updateNodeIPAddressIsUp:input_type -> pb.UpdateNodeIPAddressIsUpRequest
	18, // 14: pb.NodeIPAddressService.restoreNodeIPAddressBackupIP:input_type -> pb.RestoreNodeIPAddressBackupIPRequest
	1,  // 15: pb.NodeIPAddressService.createNodeIPAddress:output_type -> pb.CreateNodeIPAddressResponse
	3,  // 16: pb.NodeIPAddressService.createNodeIPAddresses:output_type -> pb.CreateNodeIPAddressesResponse
	20, // 17: pb.NodeIPAddressService.updateNodeIPAddress:output_type -> pb.RPCSuccess
	20, // 18: pb.NodeIPAddressService.updateNodeIPAddressNodeId:output_type -> pb.RPCSuccess
	7,  // 19: pb.NodeIPAddressService.disableNodeIPAddress:output_type -> pb.DisableNodeIPAddressResponse
	9,  // 20: pb.NodeIPAddressService.disableAllNodeIPAddressesWithNodeId:output_type -> pb.DisableAllNodeIPAddressesWithNodeIdResponse
	11, // 21: pb.NodeIPAddressService.findEnabledNodeIPAddress:output_type -> pb.FindEnabledNodeIPAddressResponse
	13, // 22: pb.NodeIPAddressService.findAllEnabledNodeIPAddressesWithNodeId:output_type -> pb.FindAllEnabledNodeIPAddressesWithNodeIdResponse
	21, // 23: pb.NodeIPAddressService.countAllEnabledNodeIPAddresses:output_type -> pb.RPCCountResponse
	16, // 24: pb.NodeIPAddressService.listEnabledNodeIPAddresses:output_type -> pb.ListEnabledNodeIPAddressesResponse
	20, // 25: pb.NodeIPAddressService.updateNodeIPAddressIsUp:output_type -> pb.RPCSuccess
	20, // 26: pb.NodeIPAddressService.restoreNodeIPAddressBackupIP:output_type -> pb.RPCSuccess
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_node_ip_address_proto_init() }
func file_service_node_ip_address_proto_init() {
	if File_service_node_ip_address_proto != nil {
		return
	}
	file_models_model_node_ip_address_proto_init()
	file_models_rpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_node_ip_address_proto_rawDesc), len(file_service_node_ip_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_node_ip_address_proto_goTypes,
		DependencyIndexes: file_service_node_ip_address_proto_depIdxs,
		MessageInfos:      file_service_node_ip_address_proto_msgTypes,
	}.Build()
	File_service_node_ip_address_proto = out.File
	file_service_node_ip_address_proto_goTypes = nil
	file_service_node_ip_address_proto_depIdxs = nil
}
