// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_node_cluster_metric_item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 启用某个指标
type EnableNodeClusterMetricItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusterId int64                  `protobuf:"varint,1,opt,name=nodeClusterId,proto3" json:"nodeClusterId,omitempty"`
	MetricItemId  int64                  `protobuf:"varint,2,opt,name=metricItemId,proto3" json:"metricItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableNodeClusterMetricItemRequest) Reset() {
	*x = EnableNodeClusterMetricItemRequest{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableNodeClusterMetricItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableNodeClusterMetricItemRequest) ProtoMessage() {}

func (x *EnableNodeClusterMetricItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableNodeClusterMetricItemRequest.ProtoReflect.Descriptor instead.
func (*EnableNodeClusterMetricItemRequest) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{0}
}

func (x *EnableNodeClusterMetricItemRequest) GetNodeClusterId() int64 {
	if x != nil {
		return x.NodeClusterId
	}
	return 0
}

func (x *EnableNodeClusterMetricItemRequest) GetMetricItemId() int64 {
	if x != nil {
		return x.MetricItemId
	}
	return 0
}

// 禁用某个指标
type DisableNodeClusterMetricItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusterId int64                  `protobuf:"varint,1,opt,name=nodeClusterId,proto3" json:"nodeClusterId,omitempty"`
	MetricItemId  int64                  `protobuf:"varint,2,opt,name=metricItemId,proto3" json:"metricItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableNodeClusterMetricItemRequest) Reset() {
	*x = DisableNodeClusterMetricItemRequest{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableNodeClusterMetricItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableNodeClusterMetricItemRequest) ProtoMessage() {}

func (x *DisableNodeClusterMetricItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableNodeClusterMetricItemRequest.ProtoReflect.Descriptor instead.
func (*DisableNodeClusterMetricItemRequest) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{1}
}

func (x *DisableNodeClusterMetricItemRequest) GetNodeClusterId() int64 {
	if x != nil {
		return x.NodeClusterId
	}
	return 0
}

func (x *DisableNodeClusterMetricItemRequest) GetMetricItemId() int64 {
	if x != nil {
		return x.MetricItemId
	}
	return 0
}

// 查找集群中所有指标
type FindAllNodeClusterMetricItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusterId int64                  `protobuf:"varint,1,opt,name=nodeClusterId,proto3" json:"nodeClusterId,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllNodeClusterMetricItemsRequest) Reset() {
	*x = FindAllNodeClusterMetricItemsRequest{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllNodeClusterMetricItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNodeClusterMetricItemsRequest) ProtoMessage() {}

func (x *FindAllNodeClusterMetricItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNodeClusterMetricItemsRequest.ProtoReflect.Descriptor instead.
func (*FindAllNodeClusterMetricItemsRequest) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllNodeClusterMetricItemsRequest) GetNodeClusterId() int64 {
	if x != nil {
		return x.NodeClusterId
	}
	return 0
}

func (x *FindAllNodeClusterMetricItemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type FindAllNodeClusterMetricItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricItems   []*MetricItem          `protobuf:"bytes,1,rep,name=metricItems,proto3" json:"metricItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllNodeClusterMetricItemsResponse) Reset() {
	*x = FindAllNodeClusterMetricItemsResponse{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllNodeClusterMetricItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNodeClusterMetricItemsResponse) ProtoMessage() {}

func (x *FindAllNodeClusterMetricItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNodeClusterMetricItemsResponse.ProtoReflect.Descriptor instead.
func (*FindAllNodeClusterMetricItemsResponse) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllNodeClusterMetricItemsResponse) GetMetricItems() []*MetricItem {
	if x != nil {
		return x.MetricItems
	}
	return nil
}

// 检查是否已添加某个指标
type ExistsNodeClusterMetricItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusterId int64                  `protobuf:"varint,1,opt,name=nodeClusterId,proto3" json:"nodeClusterId,omitempty"`
	MetricItemId  int64                  `protobuf:"varint,2,opt,name=metricItemId,proto3" json:"metricItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsNodeClusterMetricItemRequest) Reset() {
	*x = ExistsNodeClusterMetricItemRequest{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsNodeClusterMetricItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsNodeClusterMetricItemRequest) ProtoMessage() {}

func (x *ExistsNodeClusterMetricItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsNodeClusterMetricItemRequest.ProtoReflect.Descriptor instead.
func (*ExistsNodeClusterMetricItemRequest) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{4}
}

func (x *ExistsNodeClusterMetricItemRequest) GetNodeClusterId() int64 {
	if x != nil {
		return x.NodeClusterId
	}
	return 0
}

func (x *ExistsNodeClusterMetricItemRequest) GetMetricItemId() int64 {
	if x != nil {
		return x.MetricItemId
	}
	return 0
}

// 查找使用指标的集群
type FindAllNodeClustersWithMetricItemIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricItemId  int64                  `protobuf:"varint,1,opt,name=metricItemId,proto3" json:"metricItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllNodeClustersWithMetricItemIdRequest) Reset() {
	*x = FindAllNodeClustersWithMetricItemIdRequest{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllNodeClustersWithMetricItemIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNodeClustersWithMetricItemIdRequest) ProtoMessage() {}

func (x *FindAllNodeClustersWithMetricItemIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNodeClustersWithMetricItemIdRequest.ProtoReflect.Descriptor instead.
func (*FindAllNodeClustersWithMetricItemIdRequest) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllNodeClustersWithMetricItemIdRequest) GetMetricItemId() int64 {
	if x != nil {
		return x.MetricItemId
	}
	return 0
}

type FindAllNodeClustersWithMetricItemIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeClusters  []*NodeCluster         `protobuf:"bytes,1,rep,name=nodeClusters,proto3" json:"nodeClusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllNodeClustersWithMetricItemIdResponse) Reset() {
	*x = FindAllNodeClustersWithMetricItemIdResponse{}
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllNodeClustersWithMetricItemIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNodeClustersWithMetricItemIdResponse) ProtoMessage() {}

func (x *FindAllNodeClustersWithMetricItemIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_cluster_metric_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNodeClustersWithMetricItemIdResponse.ProtoReflect.Descriptor instead.
func (*FindAllNodeClustersWithMetricItemIdResponse) Descriptor() ([]byte, []int) {
	return file_service_node_cluster_metric_item_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllNodeClustersWithMetricItemIdResponse) GetNodeClusters() []*NodeCluster {
	if x != nil {
		return x.NodeClusters
	}
	return nil
}

var File_service_node_cluster_metric_item_proto protoreflect.FileDescriptor

const file_service_node_cluster_metric_item_proto_rawDesc = "" +
	"\n" +
	"&service_node_cluster_metric_item.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\x1a\x1emodels/model_metric_item.proto\x1a\x1fmodels/model_node_cluster.proto\"n\n" +
	"\"EnableNodeClusterMetricItemRequest\x12$\n" +
	"\rnodeClusterId\x18\x01 \x01(\x03R\rnodeClusterId\x12\"\n" +
	"\fmetricItemId\x18\x02 \x01(\x03R\fmetricItemId\"o\n" +
	"#DisableNodeClusterMetricItemRequest\x12$\n" +
	"\rnodeClusterId\x18\x01 \x01(\x03R\rnodeClusterId\x12\"\n" +
	"\fmetricItemId\x18\x02 \x01(\x03R\fmetricItemId\"h\n" +
	"$FindAllNodeClusterMetricItemsRequest\x12$\n" +
	"\rnodeClusterId\x18\x01 \x01(\x03R\rnodeClusterId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"Y\n" +
	"%FindAllNodeClusterMetricItemsResponse\x120\n" +
	"\vmetricItems\x18\x01 \x03(\v2\x0e.pb.MetricItemR\vmetricItems\"n\n" +
	"\"ExistsNodeClusterMetricItemRequest\x12$\n" +
	"\rnodeClusterId\x18\x01 \x01(\x03R\rnodeClusterId\x12\"\n" +
	"\fmetricItemId\x18\x02 \x01(\x03R\fmetricItemId\"P\n" +
	"*FindAllNodeClustersWithMetricItemIdRequest\x12\"\n" +
	"\fmetricItemId\x18\x01 \x01(\x03R\fmetricItemId\"b\n" +
	"+FindAllNodeClustersWithMetricItemIdResponse\x123\n" +
	"\fnodeClusters\x18\x01 \x03(\v2\x0f.pb.NodeClusterR\fnodeClusters2\xa3\x04\n" +
	"\x1cNodeClusterMetricItemService\x12U\n" +
	"\x1benableNodeClusterMetricItem\x12&.pb.EnableNodeClusterMetricItemRequest\x1a\x0e.pb.RPCSuccess\x12W\n" +
	"\x1cdisableNodeClusterMetricItem\x12'.pb.DisableNodeClusterMetricItemRequest\x1a\x0e.pb.RPCSuccess\x12t\n" +
	"\x1dfindAllNodeClusterMetricItems\x12(.pb.FindAllNodeClusterMetricItemsRequest\x1a).pb.FindAllNodeClusterMetricItemsResponse\x12T\n" +
	"\x1bexistsNodeClusterMetricItem\x12&.pb.ExistsNodeClusterMetricItemRequest\x1a\r.pb.RPCExists\x12\x86\x01\n" +
	"#findAllNodeClustersWithMetricItemId\x12..pb.FindAllNodeClustersWithMetricItemIdRequest\x1a/.pb.FindAllNodeClustersWithMetricItemIdResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_node_cluster_metric_item_proto_rawDescOnce sync.Once
	file_service_node_cluster_metric_item_proto_rawDescData []byte
)

func file_service_node_cluster_metric_item_proto_rawDescGZIP() []byte {
	file_service_node_cluster_metric_item_proto_rawDescOnce.Do(func() {
		file_service_node_cluster_metric_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_node_cluster_metric_item_proto_rawDesc), len(file_service_node_cluster_metric_item_proto_rawDesc)))
	})
	return file_service_node_cluster_metric_item_proto_rawDescData
}

var file_service_node_cluster_metric_item_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_node_cluster_metric_item_proto_goTypes = []any{
	(*EnableNodeClusterMetricItemRequest)(nil),          // 0: pb.EnableNodeClusterMetricItemRequest
	(*DisableNodeClusterMetricItemRequest)(nil),         // 1: pb.DisableNodeClusterMetricItemRequest
	(*FindAllNodeClusterMetricItemsRequest)(nil),        // 2: pb.FindAllNodeClusterMetricItemsRequest
	(*FindAllNodeClusterMetricItemsResponse)(nil),       // 3: pb.FindAllNodeClusterMetricItemsResponse
	(*ExistsNodeClusterMetricItemRequest)(nil),          // 4: pb.ExistsNodeClusterMetricItemRequest
	(*FindAllNodeClustersWithMetricItemIdRequest)(nil),  // 5: pb.FindAllNodeClustersWithMetricItemIdRequest
	(*FindAllNodeClustersWithMetricItemIdResponse)(nil), // 6: pb.FindAllNodeClustersWithMetricItemIdResponse
	(*MetricItem)(nil),  // 7: pb.MetricItem
	(*NodeCluster)(nil), // 8: pb.NodeCluster
	(*RPCSuccess)(nil),  // 9: pb.RPCSuccess
	(*RPCExists)(nil),   // 10: pb.RPCExists
}
var file_service_node_cluster_metric_item_proto_depIdxs = []int32{
	7,  // 0: pb.FindAllNodeClusterMetricItemsResponse.metricItems:type_name -> pb.MetricItem
	8,  // 1: pb.FindAllNodeClustersWithMetricItemIdResponse.nodeClusters:type_name -> pb.NodeCluster
	0,  // 2: pb.NodeClusterMetricItemService.enableNodeClusterMetricItem:input_type -> pb.EnableNodeClusterMetricItemRequest
	1,  // 3: pb.NodeClusterMetricItemService.disableNodeClusterMetricItem:input_type -> pb.DisableNodeClusterMetricItemRequest
	2,  // 4: pb.NodeClusterMetricItemService.findAllNodeClusterMetricItems:input_type -> pb.FindAllNodeClusterMetricItemsRequest
	4,  // 5: pb.NodeClusterMetricItemService.existsNodeClusterMetricItem:input_type -> pb.ExistsNodeClusterMetricItemRequest
	5,  // 6: pb.NodeClusterMetricItemService.findAllNodeClustersWithMetricItemId:input_type -> pb.FindAllNodeClustersWithMetricItemIdRequest
	9,  // 7: pb.NodeClusterMetricItemService.enableNodeClusterMetricItem:output_type -> pb.RPCSuccess
	9,  // 8: pb.NodeClusterMetricItemService.disableNodeClusterMetricItem:output_type -> pb.RPCSuccess
	3,  // 9: pb.NodeClusterMetricItemService.findAllNodeClusterMetricItems:output_type -> pb.FindAllNodeClusterMetricItemsResponse
	10, // 10: pb.NodeClusterMetricItemService.existsNodeClusterMetricItem:output_type -> pb.RPCExists
	6,  // 11: pb.NodeClusterMetricItemService.findAllNodeClustersWithMetricItemId:output_type -> pb.FindAllNodeClustersWithMetricItemIdResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_service_node_cluster_metric_item_proto_init() }
func file_service_node_cluster_metric_item_proto_init() {
	if File_service_node_cluster_metric_item_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	file_models_model_metric_item_proto_init()
	file_models_model_node_cluster_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_node_cluster_metric_item_proto_rawDesc), len(file_service_node_cluster_metric_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_node_cluster_metric_item_proto_goTypes,
		DependencyIndexes: file_service_node_cluster_metric_item_proto_depIdxs,
		MessageInfos:      file_service_node_cluster_metric_item_proto_msgTypes,
	}.Build()
	File_service_node_cluster_metric_item_proto = out.File
	file_service_node_cluster_metric_item_proto_goTypes = nil
	file_service_node_cluster_metric_item_proto_depIdxs = nil
}
