// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_ip_item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建IP
type CreateIPItemRequest struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	IpListId                      int64                  `protobuf:"varint,1,opt,name=ipListId,proto3" json:"ipListId,omitempty"`                                            // 所属IP列表ID
	Value                         string                 `protobuf:"bytes,15,opt,name=value,proto3" json:"value,omitempty"`                                                  // IP原始值，比如单个IP、IP范围或者CIDR，指定了原始值后，无需设置ipFrom和ipTo两个参数
	IpFrom                        string                 `protobuf:"bytes,2,opt,name=ipFrom,proto3" json:"ipFrom,omitempty"`                                                 // 开始IP
	IpTo                          string                 `protobuf:"bytes,3,opt,name=ipTo,proto3" json:"ipTo,omitempty"`                                                     // 结束IP（可选）
	ExpiredAt                     int64                  `protobuf:"varint,4,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`                                          // 过期时间戳（可选）
	Reason                        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                                 // 加入理由（可选）
	Type                          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`                                                     // IP类型，值为ipv4或ipv6
	EventLevel                    string                 `protobuf:"bytes,7,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"`                                         // 级别：debug, notice, warning, error, critical, fatal
	NodeId                        int64                  `protobuf:"varint,8,opt,name=nodeId,proto3" json:"nodeId,omitempty"`                                                // 可选项，所属节点ID
	ServerId                      int64                  `protobuf:"varint,9,opt,name=serverId,proto3" json:"serverId,omitempty"`                                            // 可选项，所属网站ID
	SourceNodeId                  int64                  `protobuf:"varint,10,opt,name=sourceNodeId,proto3" json:"sourceNodeId,omitempty"`                                   // 可选项，来源节点
	SourceServerId                int64                  `protobuf:"varint,11,opt,name=sourceServerId,proto3" json:"sourceServerId,omitempty"`                               // 可选项，来源网站ID
	SourceHTTPFirewallPolicyId    int64                  `protobuf:"varint,12,opt,name=sourceHTTPFirewallPolicyId,proto3" json:"sourceHTTPFirewallPolicyId,omitempty"`       // 可选项，来源WAF策略ID
	SourceHTTPFirewallRuleGroupId int64                  `protobuf:"varint,13,opt,name=sourceHTTPFirewallRuleGroupId,proto3" json:"sourceHTTPFirewallRuleGroupId,omitempty"` // 可选项，来源WAF规则分组ID
	SourceHTTPFirewallRuleSetId   int64                  `protobuf:"varint,14,opt,name=sourceHTTPFirewallRuleSetId,proto3" json:"sourceHTTPFirewallRuleSetId,omitempty"`     // 可选项，来源WAF规则集ID
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CreateIPItemRequest) Reset() {
	*x = CreateIPItemRequest{}
	mi := &file_service_ip_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIPItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIPItemRequest) ProtoMessage() {}

func (x *CreateIPItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIPItemRequest.ProtoReflect.Descriptor instead.
func (*CreateIPItemRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIPItemRequest) GetIpListId() int64 {
	if x != nil {
		return x.IpListId
	}
	return 0
}

func (x *CreateIPItemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateIPItemRequest) GetIpFrom() string {
	if x != nil {
		return x.IpFrom
	}
	return ""
}

func (x *CreateIPItemRequest) GetIpTo() string {
	if x != nil {
		return x.IpTo
	}
	return ""
}

func (x *CreateIPItemRequest) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *CreateIPItemRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateIPItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateIPItemRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *CreateIPItemRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CreateIPItemRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *CreateIPItemRequest) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *CreateIPItemRequest) GetSourceServerId() int64 {
	if x != nil {
		return x.SourceServerId
	}
	return 0
}

func (x *CreateIPItemRequest) GetSourceHTTPFirewallPolicyId() int64 {
	if x != nil {
		return x.SourceHTTPFirewallPolicyId
	}
	return 0
}

func (x *CreateIPItemRequest) GetSourceHTTPFirewallRuleGroupId() int64 {
	if x != nil {
		return x.SourceHTTPFirewallRuleGroupId
	}
	return 0
}

func (x *CreateIPItemRequest) GetSourceHTTPFirewallRuleSetId() int64 {
	if x != nil {
		return x.SourceHTTPFirewallRuleSetId
	}
	return 0
}

type CreateIPItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemId      int64                  `protobuf:"varint,1,opt,name=ipItemId,proto3" json:"ipItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIPItemResponse) Reset() {
	*x = CreateIPItemResponse{}
	mi := &file_service_ip_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIPItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIPItemResponse) ProtoMessage() {}

func (x *CreateIPItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIPItemResponse.ProtoReflect.Descriptor instead.
func (*CreateIPItemResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIPItemResponse) GetIpItemId() int64 {
	if x != nil {
		return x.IpItemId
	}
	return 0
}

// 创建一组IP
type CreateIPItemsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	IpItems       []*CreateIPItemsRequest_IPItem `protobuf:"bytes,1,rep,name=ipItems,proto3" json:"ipItems,omitempty"` // 要创建的IP列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIPItemsRequest) Reset() {
	*x = CreateIPItemsRequest{}
	mi := &file_service_ip_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIPItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIPItemsRequest) ProtoMessage() {}

func (x *CreateIPItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIPItemsRequest.ProtoReflect.Descriptor instead.
func (*CreateIPItemsRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIPItemsRequest) GetIpItems() []*CreateIPItemsRequest_IPItem {
	if x != nil {
		return x.IpItems
	}
	return nil
}

type CreateIPItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemIds     []int64                `protobuf:"varint,1,rep,packed,name=ipItemIds,proto3" json:"ipItemIds,omitempty"` // 创建后的IP ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIPItemsResponse) Reset() {
	*x = CreateIPItemsResponse{}
	mi := &file_service_ip_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIPItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIPItemsResponse) ProtoMessage() {}

func (x *CreateIPItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIPItemsResponse.ProtoReflect.Descriptor instead.
func (*CreateIPItemsResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIPItemsResponse) GetIpItemIds() []int64 {
	if x != nil {
		return x.IpItemIds
	}
	return nil
}

// 修改IP
type UpdateIPItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemId      int64                  `protobuf:"varint,1,opt,name=ipItemId,proto3" json:"ipItemId,omitempty"`
	Value         string                 `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`   // IP原始值，比如单个IP、IP范围或者CIDR，指定了原始值后，无需设置ipFrom和ipTo两个参数
	IpFrom        string                 `protobuf:"bytes,2,opt,name=ipFrom,proto3" json:"ipFrom,omitempty"` // 开始IP
	IpTo          string                 `protobuf:"bytes,3,opt,name=ipTo,proto3" json:"ipTo,omitempty"`     // 结束IP（可选）
	ExpiredAt     int64                  `protobuf:"varint,4,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`             // 类型
	EventLevel    string                 `protobuf:"bytes,7,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"` // 级别
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIPItemRequest) Reset() {
	*x = UpdateIPItemRequest{}
	mi := &file_service_ip_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIPItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIPItemRequest) ProtoMessage() {}

func (x *UpdateIPItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIPItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateIPItemRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateIPItemRequest) GetIpItemId() int64 {
	if x != nil {
		return x.IpItemId
	}
	return 0
}

func (x *UpdateIPItemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateIPItemRequest) GetIpFrom() string {
	if x != nil {
		return x.IpFrom
	}
	return ""
}

func (x *UpdateIPItemRequest) GetIpTo() string {
	if x != nil {
		return x.IpTo
	}
	return ""
}

func (x *UpdateIPItemRequest) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *UpdateIPItemRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateIPItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateIPItemRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

// 删除IP
// 可以使用 ipItemId 删除，也可以使用 ipFrom+ipTo+ipListId 删除，如果只是单个IP，则不需要指定ipTo
type DeleteIPItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemId      int64                  `protobuf:"varint,1,opt,name=ipItemId,proto3" json:"ipItemId,omitempty"` // IP条目的ID
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`        // IP原始值，比如单个IP、IP范围或者CIDR，指定了原始值后，无需设置ipFrom和ipTo两个参数
	IpFrom        string                 `protobuf:"bytes,2,opt,name=ipFrom,proto3" json:"ipFrom,omitempty"`      // v0.4.8新增，开始IP，和ipItemId二选一
	IpTo          string                 `protobuf:"bytes,3,opt,name=ipTo,proto3" json:"ipTo,omitempty"`          // v0.4.8新增，结束IP，和ipItemId二选一
	IpListId      int64                  `protobuf:"varint,4,opt,name=ipListId,proto3" json:"ipListId,omitempty"` // v0.4.8新增，IP列表，IP所在的IP列表，如果不指定，则会删除所有IP列表中的相关IP信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIPItemRequest) Reset() {
	*x = DeleteIPItemRequest{}
	mi := &file_service_ip_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIPItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIPItemRequest) ProtoMessage() {}

func (x *DeleteIPItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIPItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteIPItemRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteIPItemRequest) GetIpItemId() int64 {
	if x != nil {
		return x.IpItemId
	}
	return 0
}

func (x *DeleteIPItemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DeleteIPItemRequest) GetIpFrom() string {
	if x != nil {
		return x.IpFrom
	}
	return ""
}

func (x *DeleteIPItemRequest) GetIpTo() string {
	if x != nil {
		return x.IpTo
	}
	return ""
}

func (x *DeleteIPItemRequest) GetIpListId() int64 {
	if x != nil {
		return x.IpListId
	}
	return 0
}

// 批量删除IP
type DeleteIPItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemIds     []int64                `protobuf:"varint,1,rep,packed,name=ipItemIds,proto3" json:"ipItemIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIPItemsRequest) Reset() {
	*x = DeleteIPItemsRequest{}
	mi := &file_service_ip_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIPItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIPItemsRequest) ProtoMessage() {}

func (x *DeleteIPItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIPItemsRequest.ProtoReflect.Descriptor instead.
func (*DeleteIPItemsRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteIPItemsRequest) GetIpItemIds() []int64 {
	if x != nil {
		return x.IpItemIds
	}
	return nil
}

// 计算IP数量
type CountIPItemsWithListIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpListId      int64                  `protobuf:"varint,1,opt,name=ipListId,proto3" json:"ipListId,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	IpFrom        string                 `protobuf:"bytes,3,opt,name=ipFrom,proto3" json:"ipFrom,omitempty"`
	IpTo          string                 `protobuf:"bytes,4,opt,name=ipTo,proto3" json:"ipTo,omitempty"`
	EventLevel    string                 `protobuf:"bytes,5,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountIPItemsWithListIdRequest) Reset() {
	*x = CountIPItemsWithListIdRequest{}
	mi := &file_service_ip_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountIPItemsWithListIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountIPItemsWithListIdRequest) ProtoMessage() {}

func (x *CountIPItemsWithListIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountIPItemsWithListIdRequest.ProtoReflect.Descriptor instead.
func (*CountIPItemsWithListIdRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{7}
}

func (x *CountIPItemsWithListIdRequest) GetIpListId() int64 {
	if x != nil {
		return x.IpListId
	}
	return 0
}

func (x *CountIPItemsWithListIdRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CountIPItemsWithListIdRequest) GetIpFrom() string {
	if x != nil {
		return x.IpFrom
	}
	return ""
}

func (x *CountIPItemsWithListIdRequest) GetIpTo() string {
	if x != nil {
		return x.IpTo
	}
	return ""
}

func (x *CountIPItemsWithListIdRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

// 列出单页的IP
type ListIPItemsWithListIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpListId      int64                  `protobuf:"varint,1,opt,name=ipListId,proto3" json:"ipListId,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	IpFrom        string                 `protobuf:"bytes,5,opt,name=ipFrom,proto3" json:"ipFrom,omitempty"`
	IpTo          string                 `protobuf:"bytes,6,opt,name=ipTo,proto3" json:"ipTo,omitempty"`
	EventLevel    string                 `protobuf:"bytes,7,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPItemsWithListIdRequest) Reset() {
	*x = ListIPItemsWithListIdRequest{}
	mi := &file_service_ip_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPItemsWithListIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPItemsWithListIdRequest) ProtoMessage() {}

func (x *ListIPItemsWithListIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPItemsWithListIdRequest.ProtoReflect.Descriptor instead.
func (*ListIPItemsWithListIdRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{8}
}

func (x *ListIPItemsWithListIdRequest) GetIpListId() int64 {
	if x != nil {
		return x.IpListId
	}
	return 0
}

func (x *ListIPItemsWithListIdRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListIPItemsWithListIdRequest) GetIpFrom() string {
	if x != nil {
		return x.IpFrom
	}
	return ""
}

func (x *ListIPItemsWithListIdRequest) GetIpTo() string {
	if x != nil {
		return x.IpTo
	}
	return ""
}

func (x *ListIPItemsWithListIdRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *ListIPItemsWithListIdRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListIPItemsWithListIdRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListIPItemsWithListIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItems       []*IPItem              `protobuf:"bytes,1,rep,name=ipItems,proto3" json:"ipItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPItemsWithListIdResponse) Reset() {
	*x = ListIPItemsWithListIdResponse{}
	mi := &file_service_ip_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPItemsWithListIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPItemsWithListIdResponse) ProtoMessage() {}

func (x *ListIPItemsWithListIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPItemsWithListIdResponse.ProtoReflect.Descriptor instead.
func (*ListIPItemsWithListIdResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{9}
}

func (x *ListIPItemsWithListIdResponse) GetIpItems() []*IPItem {
	if x != nil {
		return x.IpItems
	}
	return nil
}

// 查找单个IP
type FindEnabledIPItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemId      int64                  `protobuf:"varint,1,opt,name=ipItemId,proto3" json:"ipItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledIPItemRequest) Reset() {
	*x = FindEnabledIPItemRequest{}
	mi := &file_service_ip_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledIPItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledIPItemRequest) ProtoMessage() {}

func (x *FindEnabledIPItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledIPItemRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledIPItemRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{10}
}

func (x *FindEnabledIPItemRequest) GetIpItemId() int64 {
	if x != nil {
		return x.IpItemId
	}
	return 0
}

type FindEnabledIPItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItem        *IPItem                `protobuf:"bytes,1,opt,name=ipItem,proto3" json:"ipItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledIPItemResponse) Reset() {
	*x = FindEnabledIPItemResponse{}
	mi := &file_service_ip_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledIPItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledIPItemResponse) ProtoMessage() {}

func (x *FindEnabledIPItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledIPItemResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledIPItemResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{11}
}

func (x *FindEnabledIPItemResponse) GetIpItem() *IPItem {
	if x != nil {
		return x.IpItem
	}
	return nil
}

// 根据版本列出一组IP
type ListIPItemsAfterVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // 版本号
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`       // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPItemsAfterVersionRequest) Reset() {
	*x = ListIPItemsAfterVersionRequest{}
	mi := &file_service_ip_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPItemsAfterVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPItemsAfterVersionRequest) ProtoMessage() {}

func (x *ListIPItemsAfterVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPItemsAfterVersionRequest.ProtoReflect.Descriptor instead.
func (*ListIPItemsAfterVersionRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{12}
}

func (x *ListIPItemsAfterVersionRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListIPItemsAfterVersionRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListIPItemsAfterVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItems       []*IPItem              `protobuf:"bytes,1,rep,name=ipItems,proto3" json:"ipItems,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 新的版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPItemsAfterVersionResponse) Reset() {
	*x = ListIPItemsAfterVersionResponse{}
	mi := &file_service_ip_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPItemsAfterVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPItemsAfterVersionResponse) ProtoMessage() {}

func (x *ListIPItemsAfterVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPItemsAfterVersionResponse.ProtoReflect.Descriptor instead.
func (*ListIPItemsAfterVersionResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{13}
}

func (x *ListIPItemsAfterVersionResponse) GetIpItems() []*IPItem {
	if x != nil {
		return x.IpItems
	}
	return nil
}

func (x *ListIPItemsAfterVersionResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 检查IP状态
type CheckIPItemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpListId      int64                  `protobuf:"varint,1,opt,name=ipListId,proto3" json:"ipListId,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIPItemStatusRequest) Reset() {
	*x = CheckIPItemStatusRequest{}
	mi := &file_service_ip_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIPItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIPItemStatusRequest) ProtoMessage() {}

func (x *CheckIPItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIPItemStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckIPItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{14}
}

func (x *CheckIPItemStatusRequest) GetIpListId() int64 {
	if x != nil {
		return x.IpListId
	}
	return 0
}

func (x *CheckIPItemStatusRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CheckIPItemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"` // 是否查询成功
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	IsFound       bool                   `protobuf:"varint,3,opt,name=isFound,proto3" json:"isFound,omitempty"`     // 是否找到
	IsAllowed     bool                   `protobuf:"varint,4,opt,name=isAllowed,proto3" json:"isAllowed,omitempty"` // 是否允许
	IpItem        *IPItem                `protobuf:"bytes,5,opt,name=ipItem,proto3" json:"ipItem,omitempty"`        // 匹配的IPItem
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIPItemStatusResponse) Reset() {
	*x = CheckIPItemStatusResponse{}
	mi := &file_service_ip_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIPItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIPItemStatusResponse) ProtoMessage() {}

func (x *CheckIPItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIPItemStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckIPItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{15}
}

func (x *CheckIPItemStatusResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *CheckIPItemStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CheckIPItemStatusResponse) GetIsFound() bool {
	if x != nil {
		return x.IsFound
	}
	return false
}

func (x *CheckIPItemStatusResponse) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

func (x *CheckIPItemStatusResponse) GetIpItem() *IPItem {
	if x != nil {
		return x.IpItem
	}
	return nil
}

// 检查IP是否存在
type ExistsEnabledIPItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemId      int64                  `protobuf:"varint,1,opt,name=ipItemId,proto3" json:"ipItemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsEnabledIPItemRequest) Reset() {
	*x = ExistsEnabledIPItemRequest{}
	mi := &file_service_ip_item_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsEnabledIPItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsEnabledIPItemRequest) ProtoMessage() {}

func (x *ExistsEnabledIPItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsEnabledIPItemRequest.ProtoReflect.Descriptor instead.
func (*ExistsEnabledIPItemRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{16}
}

func (x *ExistsEnabledIPItemRequest) GetIpItemId() int64 {
	if x != nil {
		return x.IpItemId
	}
	return 0
}

type ExistsEnabledIPItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsEnabledIPItemResponse) Reset() {
	*x = ExistsEnabledIPItemResponse{}
	mi := &file_service_ip_item_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsEnabledIPItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsEnabledIPItemResponse) ProtoMessage() {}

func (x *ExistsEnabledIPItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsEnabledIPItemResponse.ProtoReflect.Descriptor instead.
func (*ExistsEnabledIPItemResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{17}
}

func (x *ExistsEnabledIPItemResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// 计算所有IP数量
type CountAllEnabledIPItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`        // 关键词
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                  // 单个IP，搜索单个IP时需要
	GlobalOnly    bool                   `protobuf:"varint,2,opt,name=globalOnly,proto3" json:"globalOnly,omitempty"` // 是否为自动添加的IP
	Unread        bool                   `protobuf:"varint,3,opt,name=unread,proto3" json:"unread,omitempty"`         // 是否未读
	EventLevel    string                 `protobuf:"bytes,4,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"`  // 事件级别
	ListType      string                 `protobuf:"bytes,5,opt,name=listType,proto3" json:"listType,omitempty"`      // 列表类型：black|white
	UserId        int64                  `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`         // 用户ID，只有管理员才有权限指定用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountAllEnabledIPItemsRequest) Reset() {
	*x = CountAllEnabledIPItemsRequest{}
	mi := &file_service_ip_item_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountAllEnabledIPItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountAllEnabledIPItemsRequest) ProtoMessage() {}

func (x *CountAllEnabledIPItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountAllEnabledIPItemsRequest.ProtoReflect.Descriptor instead.
func (*CountAllEnabledIPItemsRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{18}
}

func (x *CountAllEnabledIPItemsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CountAllEnabledIPItemsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CountAllEnabledIPItemsRequest) GetGlobalOnly() bool {
	if x != nil {
		return x.GlobalOnly
	}
	return false
}

func (x *CountAllEnabledIPItemsRequest) GetUnread() bool {
	if x != nil {
		return x.Unread
	}
	return false
}

func (x *CountAllEnabledIPItemsRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *CountAllEnabledIPItemsRequest) GetListType() string {
	if x != nil {
		return x.ListType
	}
	return ""
}

func (x *CountAllEnabledIPItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 列出所有名单中的IP
type ListAllEnabledIPItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,8,opt,name=keyword,proto3" json:"keyword,omitempty"`        // 关键词
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                  // 单个IP，搜索单个IP时需要
	GlobalOnly    bool                   `protobuf:"varint,2,opt,name=globalOnly,proto3" json:"globalOnly,omitempty"` // 是否为自动添加的IP
	Unread        bool                   `protobuf:"varint,5,opt,name=unread,proto3" json:"unread,omitempty"`         // 是否未读
	EventLevel    string                 `protobuf:"bytes,6,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"`  // 事件级别
	ListType      string                 `protobuf:"bytes,7,opt,name=listType,proto3" json:"listType,omitempty"`      // 列表类型：black|white
	UserId        int64                  `protobuf:"varint,9,opt,name=userId,proto3" json:"userId,omitempty"`         // 用户ID，只有管理员才有权限指定用户ID
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`         // 读取位置，从0开始
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`             // 每次读取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllEnabledIPItemsRequest) Reset() {
	*x = ListAllEnabledIPItemsRequest{}
	mi := &file_service_ip_item_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllEnabledIPItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllEnabledIPItemsRequest) ProtoMessage() {}

func (x *ListAllEnabledIPItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllEnabledIPItemsRequest.ProtoReflect.Descriptor instead.
func (*ListAllEnabledIPItemsRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{19}
}

func (x *ListAllEnabledIPItemsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListAllEnabledIPItemsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListAllEnabledIPItemsRequest) GetGlobalOnly() bool {
	if x != nil {
		return x.GlobalOnly
	}
	return false
}

func (x *ListAllEnabledIPItemsRequest) GetUnread() bool {
	if x != nil {
		return x.Unread
	}
	return false
}

func (x *ListAllEnabledIPItemsRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *ListAllEnabledIPItemsRequest) GetListType() string {
	if x != nil {
		return x.ListType
	}
	return ""
}

func (x *ListAllEnabledIPItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAllEnabledIPItemsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAllEnabledIPItemsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListAllEnabledIPItemsResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Results       []*ListAllEnabledIPItemsResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllEnabledIPItemsResponse) Reset() {
	*x = ListAllEnabledIPItemsResponse{}
	mi := &file_service_ip_item_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllEnabledIPItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllEnabledIPItemsResponse) ProtoMessage() {}

func (x *ListAllEnabledIPItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllEnabledIPItemsResponse.ProtoReflect.Descriptor instead.
func (*ListAllEnabledIPItemsResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{20}
}

func (x *ListAllEnabledIPItemsResponse) GetResults() []*ListAllEnabledIPItemsResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

// 列出所有名单中的IP ID
type ListAllIPItemIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,8,opt,name=keyword,proto3" json:"keyword,omitempty"`        // 关键词
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                  // 单个IP，搜索单个IP时需要
	GlobalOnly    bool                   `protobuf:"varint,2,opt,name=globalOnly,proto3" json:"globalOnly,omitempty"` // 是否为自动添加的IP
	Unread        bool                   `protobuf:"varint,5,opt,name=unread,proto3" json:"unread,omitempty"`         // 是否未读
	EventLevel    string                 `protobuf:"bytes,6,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"`  // 事件级别
	ListType      string                 `protobuf:"bytes,7,opt,name=listType,proto3" json:"listType,omitempty"`      // 列表类型：black|white
	UserId        int64                  `protobuf:"varint,9,opt,name=userId,proto3" json:"userId,omitempty"`         // 用户ID，只有管理员才有权限指定用户ID
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`         // 读取位置，从0开始
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`             // 每次读取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllIPItemIdsRequest) Reset() {
	*x = ListAllIPItemIdsRequest{}
	mi := &file_service_ip_item_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllIPItemIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllIPItemIdsRequest) ProtoMessage() {}

func (x *ListAllIPItemIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllIPItemIdsRequest.ProtoReflect.Descriptor instead.
func (*ListAllIPItemIdsRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{21}
}

func (x *ListAllIPItemIdsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListAllIPItemIdsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListAllIPItemIdsRequest) GetGlobalOnly() bool {
	if x != nil {
		return x.GlobalOnly
	}
	return false
}

func (x *ListAllIPItemIdsRequest) GetUnread() bool {
	if x != nil {
		return x.Unread
	}
	return false
}

func (x *ListAllIPItemIdsRequest) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *ListAllIPItemIdsRequest) GetListType() string {
	if x != nil {
		return x.ListType
	}
	return ""
}

func (x *ListAllIPItemIdsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAllIPItemIdsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAllIPItemIdsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListAllIPItemIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemIds     []int64                `protobuf:"varint,1,rep,packed,name=ipItemIds,proto3" json:"ipItemIds,omitempty"` // IP ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllIPItemIdsResponse) Reset() {
	*x = ListAllIPItemIdsResponse{}
	mi := &file_service_ip_item_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllIPItemIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllIPItemIdsResponse) ProtoMessage() {}

func (x *ListAllIPItemIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllIPItemIdsResponse.ProtoReflect.Descriptor instead.
func (*ListAllIPItemIdsResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{22}
}

func (x *ListAllIPItemIdsResponse) GetIpItemIds() []int64 {
	if x != nil {
		return x.IpItemIds
	}
	return nil
}

// 设置所有为已读
type UpdateIPItemsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIPItemsReadRequest) Reset() {
	*x = UpdateIPItemsReadRequest{}
	mi := &file_service_ip_item_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIPItemsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIPItemsReadRequest) ProtoMessage() {}

func (x *UpdateIPItemsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIPItemsReadRequest.ProtoReflect.Descriptor instead.
func (*UpdateIPItemsReadRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{23}
}

// 查找IP对应的名单所属网站ID
type FindServerIdWithIPItemIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpItemId      int64                  `protobuf:"varint,1,opt,name=ipItemId,proto3" json:"ipItemId,omitempty"` // IP ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindServerIdWithIPItemIdRequest) Reset() {
	*x = FindServerIdWithIPItemIdRequest{}
	mi := &file_service_ip_item_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindServerIdWithIPItemIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindServerIdWithIPItemIdRequest) ProtoMessage() {}

func (x *FindServerIdWithIPItemIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindServerIdWithIPItemIdRequest.ProtoReflect.Descriptor instead.
func (*FindServerIdWithIPItemIdRequest) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{24}
}

func (x *FindServerIdWithIPItemIdRequest) GetIpItemId() int64 {
	if x != nil {
		return x.IpItemId
	}
	return 0
}

type FindServerIdWithIPItemIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int64                  `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"` // 网站ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindServerIdWithIPItemIdResponse) Reset() {
	*x = FindServerIdWithIPItemIdResponse{}
	mi := &file_service_ip_item_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindServerIdWithIPItemIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindServerIdWithIPItemIdResponse) ProtoMessage() {}

func (x *FindServerIdWithIPItemIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindServerIdWithIPItemIdResponse.ProtoReflect.Descriptor instead.
func (*FindServerIdWithIPItemIdResponse) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{25}
}

func (x *FindServerIdWithIPItemIdResponse) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type CreateIPItemsRequest_IPItem struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	IpListId                      int64                  `protobuf:"varint,1,opt,name=ipListId,proto3" json:"ipListId,omitempty"`    // IP列表ID
	Value                         string                 `protobuf:"bytes,15,opt,name=value,proto3" json:"value,omitempty"`          // IP原始值，比如单个IP、IP范围或者CIDR，指定了原始值后，无需设置ipFrom和ipTo两个参数
	IpFrom                        string                 `protobuf:"bytes,2,opt,name=ipFrom,proto3" json:"ipFrom,omitempty"`         // 开始IP
	IpTo                          string                 `protobuf:"bytes,3,opt,name=ipTo,proto3" json:"ipTo,omitempty"`             // 结束IP（可选）
	ExpiredAt                     int64                  `protobuf:"varint,4,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`  // 过期时间戳（可选）
	Reason                        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`         // 加入理由（可选）
	Type                          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`             // 类型
	EventLevel                    string                 `protobuf:"bytes,7,opt,name=eventLevel,proto3" json:"eventLevel,omitempty"` // 级别
	NodeId                        int64                  `protobuf:"varint,8,opt,name=nodeId,proto3" json:"nodeId,omitempty"`        // 所属节点ID
	ServerId                      int64                  `protobuf:"varint,9,opt,name=serverId,proto3" json:"serverId,omitempty"`    // 所属服务ID
	SourceNodeId                  int64                  `protobuf:"varint,10,opt,name=sourceNodeId,proto3" json:"sourceNodeId,omitempty"`
	SourceServerId                int64                  `protobuf:"varint,11,opt,name=sourceServerId,proto3" json:"sourceServerId,omitempty"`
	SourceHTTPFirewallPolicyId    int64                  `protobuf:"varint,12,opt,name=sourceHTTPFirewallPolicyId,proto3" json:"sourceHTTPFirewallPolicyId,omitempty"`
	SourceHTTPFirewallRuleGroupId int64                  `protobuf:"varint,13,opt,name=sourceHTTPFirewallRuleGroupId,proto3" json:"sourceHTTPFirewallRuleGroupId,omitempty"`
	SourceHTTPFirewallRuleSetId   int64                  `protobuf:"varint,14,opt,name=sourceHTTPFirewallRuleSetId,proto3" json:"sourceHTTPFirewallRuleSetId,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CreateIPItemsRequest_IPItem) Reset() {
	*x = CreateIPItemsRequest_IPItem{}
	mi := &file_service_ip_item_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIPItemsRequest_IPItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIPItemsRequest_IPItem) ProtoMessage() {}

func (x *CreateIPItemsRequest_IPItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIPItemsRequest_IPItem.ProtoReflect.Descriptor instead.
func (*CreateIPItemsRequest_IPItem) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateIPItemsRequest_IPItem) GetIpListId() int64 {
	if x != nil {
		return x.IpListId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateIPItemsRequest_IPItem) GetIpFrom() string {
	if x != nil {
		return x.IpFrom
	}
	return ""
}

func (x *CreateIPItemsRequest_IPItem) GetIpTo() string {
	if x != nil {
		return x.IpTo
	}
	return ""
}

func (x *CreateIPItemsRequest_IPItem) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateIPItemsRequest_IPItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateIPItemsRequest_IPItem) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *CreateIPItemsRequest_IPItem) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetSourceServerId() int64 {
	if x != nil {
		return x.SourceServerId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetSourceHTTPFirewallPolicyId() int64 {
	if x != nil {
		return x.SourceHTTPFirewallPolicyId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetSourceHTTPFirewallRuleGroupId() int64 {
	if x != nil {
		return x.SourceHTTPFirewallRuleGroupId
	}
	return 0
}

func (x *CreateIPItemsRequest_IPItem) GetSourceHTTPFirewallRuleSetId() int64 {
	if x != nil {
		return x.SourceHTTPFirewallRuleSetId
	}
	return 0
}

type ListAllEnabledIPItemsResponse_Result struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IpList             *IPList                `protobuf:"bytes,1,opt,name=ipList,proto3" json:"ipList,omitempty"`                         // 所属名单
	IpItem             *IPItem                `protobuf:"bytes,2,opt,name=ipItem,proto3" json:"ipItem,omitempty"`                         // IP信息
	Server             *Server                `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`                         // 所属服务
	HttpFirewallPolicy *HTTPFirewallPolicy    `protobuf:"bytes,4,opt,name=httpFirewallPolicy,proto3" json:"httpFirewallPolicy,omitempty"` // 所属WAF策略
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListAllEnabledIPItemsResponse_Result) Reset() {
	*x = ListAllEnabledIPItemsResponse_Result{}
	mi := &file_service_ip_item_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllEnabledIPItemsResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllEnabledIPItemsResponse_Result) ProtoMessage() {}

func (x *ListAllEnabledIPItemsResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_ip_item_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllEnabledIPItemsResponse_Result.ProtoReflect.Descriptor instead.
func (*ListAllEnabledIPItemsResponse_Result) Descriptor() ([]byte, []int) {
	return file_service_ip_item_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ListAllEnabledIPItemsResponse_Result) GetIpList() *IPList {
	if x != nil {
		return x.IpList
	}
	return nil
}

func (x *ListAllEnabledIPItemsResponse_Result) GetIpItem() *IPItem {
	if x != nil {
		return x.IpItem
	}
	return nil
}

func (x *ListAllEnabledIPItemsResponse_Result) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ListAllEnabledIPItemsResponse_Result) GetHttpFirewallPolicy() *HTTPFirewallPolicy {
	if x != nil {
		return x.HttpFirewallPolicy
	}
	return nil
}

var File_service_ip_item_proto protoreflect.FileDescriptor

const file_service_ip_item_proto_rawDesc = "" +
	"\n" +
	"\x15service_ip_item.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\x1a\x1amodels/model_ip_item.proto\x1a\x1amodels/model_ip_list.proto\x1a\x19models/model_server.proto\x1a'models/model_http_firewall_policy.proto\"\xa5\x04\n" +
	"\x13CreateIPItemRequest\x12\x1a\n" +
	"\bipListId\x18\x01 \x01(\x03R\bipListId\x12\x14\n" +
	"\x05value\x18\x0f \x01(\tR\x05value\x12\x16\n" +
	"\x06ipFrom\x18\x02 \x01(\tR\x06ipFrom\x12\x12\n" +
	"\x04ipTo\x18\x03 \x01(\tR\x04ipTo\x12\x1c\n" +
	"\texpiredAt\x18\x04 \x01(\x03R\texpiredAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\a \x01(\tR\n" +
	"eventLevel\x12\x16\n" +
	"\x06nodeId\x18\b \x01(\x03R\x06nodeId\x12\x1a\n" +
	"\bserverId\x18\t \x01(\x03R\bserverId\x12\"\n" +
	"\fsourceNodeId\x18\n" +
	" \x01(\x03R\fsourceNodeId\x12&\n" +
	"\x0esourceServerId\x18\v \x01(\x03R\x0esourceServerId\x12>\n" +
	"\x1asourceHTTPFirewallPolicyId\x18\f \x01(\x03R\x1asourceHTTPFirewallPolicyId\x12D\n" +
	"\x1dsourceHTTPFirewallRuleGroupId\x18\r \x01(\x03R\x1dsourceHTTPFirewallRuleGroupId\x12@\n" +
	"\x1bsourceHTTPFirewallRuleSetId\x18\x0e \x01(\x03R\x1bsourceHTTPFirewallRuleSetId\"2\n" +
	"\x14CreateIPItemResponse\x12\x1a\n" +
	"\bipItemId\x18\x01 \x01(\x03R\bipItemId\"\xec\x04\n" +
	"\x14CreateIPItemsRequest\x129\n" +
	"\aipItems\x18\x01 \x03(\v2\x1f.pb.CreateIPItemsRequest.IPItemR\aipItems\x1a\x98\x04\n" +
	"\x06IPItem\x12\x1a\n" +
	"\bipListId\x18\x01 \x01(\x03R\bipListId\x12\x14\n" +
	"\x05value\x18\x0f \x01(\tR\x05value\x12\x16\n" +
	"\x06ipFrom\x18\x02 \x01(\tR\x06ipFrom\x12\x12\n" +
	"\x04ipTo\x18\x03 \x01(\tR\x04ipTo\x12\x1c\n" +
	"\texpiredAt\x18\x04 \x01(\x03R\texpiredAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\a \x01(\tR\n" +
	"eventLevel\x12\x16\n" +
	"\x06nodeId\x18\b \x01(\x03R\x06nodeId\x12\x1a\n" +
	"\bserverId\x18\t \x01(\x03R\bserverId\x12\"\n" +
	"\fsourceNodeId\x18\n" +
	" \x01(\x03R\fsourceNodeId\x12&\n" +
	"\x0esourceServerId\x18\v \x01(\x03R\x0esourceServerId\x12>\n" +
	"\x1asourceHTTPFirewallPolicyId\x18\f \x01(\x03R\x1asourceHTTPFirewallPolicyId\x12D\n" +
	"\x1dsourceHTTPFirewallRuleGroupId\x18\r \x01(\x03R\x1dsourceHTTPFirewallRuleGroupId\x12@\n" +
	"\x1bsourceHTTPFirewallRuleSetId\x18\x0e \x01(\x03R\x1bsourceHTTPFirewallRuleSetId\"5\n" +
	"\x15CreateIPItemsResponse\x12\x1c\n" +
	"\tipItemIds\x18\x01 \x03(\x03R\tipItemIds\"\xdd\x01\n" +
	"\x13UpdateIPItemRequest\x12\x1a\n" +
	"\bipItemId\x18\x01 \x01(\x03R\bipItemId\x12\x14\n" +
	"\x05value\x18\b \x01(\tR\x05value\x12\x16\n" +
	"\x06ipFrom\x18\x02 \x01(\tR\x06ipFrom\x12\x12\n" +
	"\x04ipTo\x18\x03 \x01(\tR\x04ipTo\x12\x1c\n" +
	"\texpiredAt\x18\x04 \x01(\x03R\texpiredAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\a \x01(\tR\n" +
	"eventLevel\"\x8f\x01\n" +
	"\x13DeleteIPItemRequest\x12\x1a\n" +
	"\bipItemId\x18\x01 \x01(\x03R\bipItemId\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x16\n" +
	"\x06ipFrom\x18\x02 \x01(\tR\x06ipFrom\x12\x12\n" +
	"\x04ipTo\x18\x03 \x01(\tR\x04ipTo\x12\x1a\n" +
	"\bipListId\x18\x04 \x01(\x03R\bipListId\"4\n" +
	"\x14DeleteIPItemsRequest\x12\x1c\n" +
	"\tipItemIds\x18\x01 \x03(\x03R\tipItemIds\"\xa1\x01\n" +
	"\x1dCountIPItemsWithListIdRequest\x12\x1a\n" +
	"\bipListId\x18\x01 \x01(\x03R\bipListId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x16\n" +
	"\x06ipFrom\x18\x03 \x01(\tR\x06ipFrom\x12\x12\n" +
	"\x04ipTo\x18\x04 \x01(\tR\x04ipTo\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\x05 \x01(\tR\n" +
	"eventLevel\"\xcc\x01\n" +
	"\x1cListIPItemsWithListIdRequest\x12\x1a\n" +
	"\bipListId\x18\x01 \x01(\x03R\bipListId\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x16\n" +
	"\x06ipFrom\x18\x05 \x01(\tR\x06ipFrom\x12\x12\n" +
	"\x04ipTo\x18\x06 \x01(\tR\x04ipTo\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\a \x01(\tR\n" +
	"eventLevel\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"E\n" +
	"\x1dListIPItemsWithListIdResponse\x12$\n" +
	"\aipItems\x18\x01 \x03(\v2\n" +
	".pb.IPItemR\aipItems\"6\n" +
	"\x18FindEnabledIPItemRequest\x12\x1a\n" +
	"\bipItemId\x18\x01 \x01(\x03R\bipItemId\"?\n" +
	"\x19FindEnabledIPItemResponse\x12\"\n" +
	"\x06ipItem\x18\x01 \x01(\v2\n" +
	".pb.IPItemR\x06ipItem\"N\n" +
	"\x1eListIPItemsAfterVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"a\n" +
	"\x1fListIPItemsAfterVersionResponse\x12$\n" +
	"\aipItems\x18\x01 \x03(\v2\n" +
	".pb.IPItemR\aipItems\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"F\n" +
	"\x18CheckIPItemStatusRequest\x12\x1a\n" +
	"\bipListId\x18\x01 \x01(\x03R\bipListId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\xa1\x01\n" +
	"\x19CheckIPItemStatusResponse\x12\x12\n" +
	"\x04isOk\x18\x01 \x01(\bR\x04isOk\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aisFound\x18\x03 \x01(\bR\aisFound\x12\x1c\n" +
	"\tisAllowed\x18\x04 \x01(\bR\tisAllowed\x12\"\n" +
	"\x06ipItem\x18\x05 \x01(\v2\n" +
	".pb.IPItemR\x06ipItem\"8\n" +
	"\x1aExistsEnabledIPItemRequest\x12\x1a\n" +
	"\bipItemId\x18\x01 \x01(\x03R\bipItemId\"5\n" +
	"\x1bExistsEnabledIPItemResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xd5\x01\n" +
	"\x1dCountAllEnabledIPItemsRequest\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1e\n" +
	"\n" +
	"globalOnly\x18\x02 \x01(\bR\n" +
	"globalOnly\x12\x16\n" +
	"\x06unread\x18\x03 \x01(\bR\x06unread\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\x04 \x01(\tR\n" +
	"eventLevel\x12\x1a\n" +
	"\blistType\x18\x05 \x01(\tR\blistType\x12\x16\n" +
	"\x06userId\x18\a \x01(\x03R\x06userId\"\x80\x02\n" +
	"\x1cListAllEnabledIPItemsRequest\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1e\n" +
	"\n" +
	"globalOnly\x18\x02 \x01(\bR\n" +
	"globalOnly\x12\x16\n" +
	"\x06unread\x18\x05 \x01(\bR\x06unread\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\x06 \x01(\tR\n" +
	"eventLevel\x12\x1a\n" +
	"\blistType\x18\a \x01(\tR\blistType\x12\x16\n" +
	"\x06userId\x18\t \x01(\x03R\x06userId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\xa2\x02\n" +
	"\x1dListAllEnabledIPItemsResponse\x12B\n" +
	"\aresults\x18\x01 \x03(\v2(.pb.ListAllEnabledIPItemsResponse.ResultR\aresults\x1a\xbc\x01\n" +
	"\x06Result\x12\"\n" +
	"\x06ipList\x18\x01 \x01(\v2\n" +
	".pb.IPListR\x06ipList\x12\"\n" +
	"\x06ipItem\x18\x02 \x01(\v2\n" +
	".pb.IPItemR\x06ipItem\x12\"\n" +
	"\x06server\x18\x03 \x01(\v2\n" +
	".pb.ServerR\x06server\x12F\n" +
	"\x12httpFirewallPolicy\x18\x04 \x01(\v2\x16.pb.HTTPFirewallPolicyR\x12httpFirewallPolicy\"\xfb\x01\n" +
	"\x17ListAllIPItemIdsRequest\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1e\n" +
	"\n" +
	"globalOnly\x18\x02 \x01(\bR\n" +
	"globalOnly\x12\x16\n" +
	"\x06unread\x18\x05 \x01(\bR\x06unread\x12\x1e\n" +
	"\n" +
	"eventLevel\x18\x06 \x01(\tR\n" +
	"eventLevel\x12\x1a\n" +
	"\blistType\x18\a \x01(\tR\blistType\x12\x16\n" +
	"\x06userId\x18\t \x01(\x03R\x06userId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"8\n" +
	"\x18ListAllIPItemIdsResponse\x12\x1c\n" +
	"\tipItemIds\x18\x01 \x03(\x03R\tipItemIds\"\x1a\n" +
	"\x18UpdateIPItemsReadRequest\"=\n" +
	"\x1fFindServerIdWithIPItemIdRequest\x12\x1a\n" +
	"\bipItemId\x18\x01 \x01(\x03R\bipItemId\">\n" +
	" FindServerIdWithIPItemIdResponse\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\x03R\bserverId2\x80\n" +
	"\n" +
	"\rIPItemService\x12A\n" +
	"\fcreateIPItem\x12\x17.pb.CreateIPItemRequest\x1a\x18.pb.CreateIPItemResponse\x12D\n" +
	"\rcreateIPItems\x12\x18.pb.CreateIPItemsRequest\x1a\x19.pb.CreateIPItemsResponse\x127\n" +
	"\fupdateIPItem\x12\x17.pb.UpdateIPItemRequest\x1a\x0e.pb.RPCSuccess\x127\n" +
	"\fdeleteIPItem\x12\x17.pb.DeleteIPItemRequest\x1a\x0e.pb.RPCSuccess\x129\n" +
	"\rdeleteIPItems\x12\x18.pb.DeleteIPItemsRequest\x1a\x0e.pb.RPCSuccess\x12Q\n" +
	"\x16countIPItemsWithListId\x12!.pb.CountIPItemsWithListIdRequest\x1a\x14.pb.RPCCountResponse\x12\\\n" +
	"\x15listIPItemsWithListId\x12 .pb.ListIPItemsWithListIdRequest\x1a!.pb.ListIPItemsWithListIdResponse\x12P\n" +
	"\x11findEnabledIPItem\x12\x1c.pb.FindEnabledIPItemRequest\x1a\x1d.pb.FindEnabledIPItemResponse\x12b\n" +
	"\x17listIPItemsAfterVersion\x12\".pb.ListIPItemsAfterVersionRequest\x1a#.pb.ListIPItemsAfterVersionResponse\x12P\n" +
	"\x11checkIPItemStatus\x12\x1c.pb.CheckIPItemStatusRequest\x1a\x1d.pb.CheckIPItemStatusResponse\x12V\n" +
	"\x13existsEnabledIPItem\x12\x1e.pb.ExistsEnabledIPItemRequest\x1a\x1f.pb.ExistsEnabledIPItemResponse\x12Q\n" +
	"\x16countAllEnabledIPItems\x12!.pb.CountAllEnabledIPItemsRequest\x1a\x14.pb.RPCCountResponse\x12\\\n" +
	"\x15listAllEnabledIPItems\x12 .pb.ListAllEnabledIPItemsRequest\x1a!.pb.ListAllEnabledIPItemsResponse\x12M\n" +
	"\x10listAllIPItemIds\x12\x1b.pb.ListAllIPItemIdsRequest\x1a\x1c.pb.ListAllIPItemIdsResponse\x12A\n" +
	"\x11updateIPItemsRead\x12\x1c.pb.UpdateIPItemsReadRequest\x1a\x0e.pb.RPCSuccess\x12e\n" +
	"\x18findServerIdWithIPItemId\x12#.pb.FindServerIdWithIPItemIdRequest\x1a$.pb.FindServerIdWithIPItemIdResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_ip_item_proto_rawDescOnce sync.Once
	file_service_ip_item_proto_rawDescData []byte
)

func file_service_ip_item_proto_rawDescGZIP() []byte {
	file_service_ip_item_proto_rawDescOnce.Do(func() {
		file_service_ip_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_ip_item_proto_rawDesc), len(file_service_ip_item_proto_rawDesc)))
	})
	return file_service_ip_item_proto_rawDescData
}

var file_service_ip_item_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_service_ip_item_proto_goTypes = []any{
	(*CreateIPItemRequest)(nil),                  // 0: pb.CreateIPItemRequest
	(*CreateIPItemResponse)(nil),                 // 1: pb.CreateIPItemResponse
	(*CreateIPItemsRequest)(nil),                 // 2: pb.CreateIPItemsRequest
	(*CreateIPItemsResponse)(nil),                // 3: pb.CreateIPItemsResponse
	(*UpdateIPItemRequest)(nil),                  // 4: pb.UpdateIPItemRequest
	(*DeleteIPItemRequest)(nil),                  // 5: pb.DeleteIPItemRequest
	(*DeleteIPItemsRequest)(nil),                 // 6: pb.DeleteIPItemsRequest
	(*CountIPItemsWithListIdRequest)(nil),        // 7: pb.CountIPItemsWithListIdRequest
	(*ListIPItemsWithListIdRequest)(nil),         // 8: pb.ListIPItemsWithListIdRequest
	(*ListIPItemsWithListIdResponse)(nil),        // 9: pb.ListIPItemsWithListIdResponse
	(*FindEnabledIPItemRequest)(nil),             // 10: pb.FindEnabledIPItemRequest
	(*FindEnabledIPItemResponse)(nil),            // 11: pb.FindEnabledIPItemResponse
	(*ListIPItemsAfterVersionRequest)(nil),       // 12: pb.ListIPItemsAfterVersionRequest
	(*ListIPItemsAfterVersionResponse)(nil),      // 13: pb.ListIPItemsAfterVersionResponse
	(*CheckIPItemStatusRequest)(nil),             // 14: pb.CheckIPItemStatusRequest
	(*CheckIPItemStatusResponse)(nil),            // 15: pb.CheckIPItemStatusResponse
	(*ExistsEnabledIPItemRequest)(nil),           // 16: pb.ExistsEnabledIPItemRequest
	(*ExistsEnabledIPItemResponse)(nil),          // 17: pb.ExistsEnabledIPItemResponse
	(*CountAllEnabledIPItemsRequest)(nil),        // 18: pb.CountAllEnabledIPItemsRequest
	(*ListAllEnabledIPItemsRequest)(nil),         // 19: pb.ListAllEnabledIPItemsRequest
	(*ListAllEnabledIPItemsResponse)(nil),        // 20: pb.ListAllEnabledIPItemsResponse
	(*ListAllIPItemIdsRequest)(nil),              // 21: pb.ListAllIPItemIdsRequest
	(*ListAllIPItemIdsResponse)(nil),             // 22: pb.ListAllIPItemIdsResponse
	(*UpdateIPItemsReadRequest)(nil),             // 23: pb.UpdateIPItemsReadRequest
	(*FindServerIdWithIPItemIdRequest)(nil),      // 24: pb.FindServerIdWithIPItemIdRequest
	(*FindServerIdWithIPItemIdResponse)(nil),     // 25: pb.FindServerIdWithIPItemIdResponse
	(*CreateIPItemsRequest_IPItem)(nil),          // 26: pb.CreateIPItemsRequest.IPItem
	(*ListAllEnabledIPItemsResponse_Result)(nil), // 27: pb.ListAllEnabledIPItemsResponse.Result
	(*IPItem)(nil),                               // 28: pb.IPItem
	(*IPList)(nil),                               // 29: pb.IPList
	(*Server)(nil),                               // 30: pb.Server
	(*HTTPFirewallPolicy)(nil),                   // 31: pb.HTTPFirewallPolicy
	(*RPCSuccess)(nil),                           // 32: pb.RPCSuccess
	(*RPCCountResponse)(nil),                     // 33: pb.RPCCountResponse
}
var file_service_ip_item_proto_depIdxs = []int32{
	26, // 0: pb.CreateIPItemsRequest.ipItems:type_name -> pb.CreateIPItemsRequest.IPItem
	28, // 1: pb.ListIPItemsWithListIdResponse.ipItems:type_name -> pb.IPItem
	28, // 2: pb.FindEnabledIPItemResponse.ipItem:type_name -> pb.IPItem
	28, // 3: pb.ListIPItemsAfterVersionResponse.ipItems:type_name -> pb.IPItem
	28, // 4: pb.CheckIPItemStatusResponse.ipItem:type_name -> pb.IPItem
	27, // 5: pb.ListAllEnabledIPItemsResponse.results:type_name -> pb.ListAllEnabledIPItemsResponse.Result
	29, // 6: pb.ListAllEnabledIPItemsResponse.Result.ipList:type_name -> pb.IPList
	28, // 7: pb.ListAllEnabledIPItemsResponse.Result.ipItem:type_name -> pb.IPItem
	30, // 8: pb.ListAllEnabledIPItemsResponse.Result.server:type_name -> pb.Server
	31, // 9: pb.ListAllEnabledIPItemsResponse.Result.httpFirewallPolicy:type_name -> pb.HTTPFirewallPolicy
	0,  // 10: pb.IPItemService.createIPItem:input_type -> pb.CreateIPItemRequest
	2,  // 11: pb.IPItemService.createIPItems:input_type -> pb.CreateIPItemsRequest
	4,  // 12: pb.IPItemService.updateIPItem:input_type -> pb.UpdateIPItemRequest
	5,  // 13: pb.IPItemService.deleteIPItem:input_type -> pb.DeleteIPItemRequest
	6,  // 14: pb.IPItemService.deleteIPItems:input_type -> pb.DeleteIPItemsRequest
	7,  // 15: pb.IPItemService.countIPItemsWithListId:input_type -> pb.CountIPItemsWithListIdRequest
	8,  // 16: pb.IPItemService.listIPItemsWithListId:input_type -> pb.ListIPItemsWithListIdRequest
	10, // 17: pb.IPItemService.findEnabledIPItem:input_type -> pb.FindEnabledIPItemRequest
	12, // 18: pb.IPItemService.listIPItemsAfterVersion:input_type -> pb.ListIPItemsAfterVersionRequest
	14, // 19: pb.IPItemService.checkIPItemStatus:input_type -> pb.CheckIPItemStatusRequest
	16, // 20: pb.IPItemService.existsEnabledIPItem:input_type -> pb.ExistsEnabledIPItemRequest
	18, // 21: pb.IPItemService.countAllEnabledIPItems:input_type -> pb.CountAllEnabledIPItemsRequest
	19, // 22: pb.IPItemService.listAllEnabledIPItems:input_type -> pb.ListAllEnabledIPItemsRequest
	21, // 23: pb.IPItemService.listAllIPItemIds:input_type -> pb.ListAllIPItemIdsRequest
	23, // 24: pb.IPItemService.updateIPItemsRead:input_type -> pb.UpdateIPItemsReadRequest
	24, // 25: pb.IPItemService.findServerIdWithIPItemId:input_type -> pb.FindServerIdWithIPItemIdRequest
	1,  // 26: pb.IPItemService.createIPItem:output_type -> pb.CreateIPItemResponse
	3,  // 27: pb.IPItemService.createIPItems:output_type -> pb.CreateIPItemsResponse
	32, // 28: pb.IPItemService.updateIPItem:output_type -> pb.RPCSuccess
	32, // 29: pb.IPItemService.deleteIPItem:output_type -> pb.RPCSuccess
	32, // 30: pb.IPItemService.deleteIPItems:output_type -> pb.RPCSuccess
	33, // 31: pb.IPItemService.countIPItemsWithListId:output_type -> pb.RPCCountResponse
	9,  // 32: pb.IPItemService.listIPItemsWithListId:output_type -> pb.ListIPItemsWithListIdResponse
	11, // 33: pb.IPItemService.findEnabledIPItem:output_type -> pb.FindEnabledIPItemResponse
	13, // 34: pb.IPItemService.listIPItemsAfterVersion:output_type -> pb.ListIPItemsAfterVersionResponse
	15, // 35: pb.IPItemService.checkIPItemStatus:output_type -> pb.CheckIPItemStatusResponse
	17, // 36: pb.IPItemService.existsEnabledIPItem:output_type -> pb.ExistsEnabledIPItemResponse
	33, // 37: pb.IPItemService.countAllEnabledIPItems:output_type -> pb.RPCCountResponse
	20, // 38: pb.IPItemService.listAllEnabledIPItems:output_type -> pb.ListAllEnabledIPItemsResponse
	22, // 39: pb.IPItemService.listAllIPItemIds:output_type -> pb.ListAllIPItemIdsResponse
	32, // 40: pb.IPItemService.updateIPItemsRead:output_type -> pb.RPCSuccess
	25, // 41: pb.IPItemService.findServerIdWithIPItemId:output_type -> pb.FindServerIdWithIPItemIdResponse
	26, // [26:42] is the sub-list for method output_type
	10, // [10:26] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_service_ip_item_proto_init() }
func file_service_ip_item_proto_init() {
	if File_service_ip_item_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	file_models_model_ip_item_proto_init()
	file_models_model_ip_list_proto_init()
	file_models_model_server_proto_init()
	file_models_model_http_firewall_policy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_ip_item_proto_rawDesc), len(file_service_ip_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_ip_item_proto_goTypes,
		DependencyIndexes: file_service_ip_item_proto_depIdxs,
		MessageInfos:      file_service_ip_item_proto_msgTypes,
	}.Build()
	File_service_ip_item_proto = out.File
	file_service_ip_item_proto_goTypes = nil
	file_service_ip_item_proto_depIdxs = nil
}
