// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_http_fastcgi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建Fastcgi服务
type CreateHTTPFastcgiRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsOn            bool                   `protobuf:"varint,1,opt,name=isOn,proto3" json:"isOn,omitempty"`
	Address         string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ParamsJSON      []byte                 `protobuf:"bytes,3,opt,name=paramsJSON,proto3" json:"paramsJSON,omitempty"`
	ReadTimeoutJSON []byte                 `protobuf:"bytes,4,opt,name=readTimeoutJSON,proto3" json:"readTimeoutJSON,omitempty"`
	ConnTimeoutJSON []byte                 `protobuf:"bytes,5,opt,name=connTimeoutJSON,proto3" json:"connTimeoutJSON,omitempty"`
	PoolSize        int32                  `protobuf:"varint,6,opt,name=poolSize,proto3" json:"poolSize,omitempty"`
	PathInfoPattern string                 `protobuf:"bytes,7,opt,name=pathInfoPattern,proto3" json:"pathInfoPattern,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateHTTPFastcgiRequest) Reset() {
	*x = CreateHTTPFastcgiRequest{}
	mi := &file_service_http_fastcgi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHTTPFastcgiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHTTPFastcgiRequest) ProtoMessage() {}

func (x *CreateHTTPFastcgiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHTTPFastcgiRequest.ProtoReflect.Descriptor instead.
func (*CreateHTTPFastcgiRequest) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHTTPFastcgiRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *CreateHTTPFastcgiRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateHTTPFastcgiRequest) GetParamsJSON() []byte {
	if x != nil {
		return x.ParamsJSON
	}
	return nil
}

func (x *CreateHTTPFastcgiRequest) GetReadTimeoutJSON() []byte {
	if x != nil {
		return x.ReadTimeoutJSON
	}
	return nil
}

func (x *CreateHTTPFastcgiRequest) GetConnTimeoutJSON() []byte {
	if x != nil {
		return x.ConnTimeoutJSON
	}
	return nil
}

func (x *CreateHTTPFastcgiRequest) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *CreateHTTPFastcgiRequest) GetPathInfoPattern() string {
	if x != nil {
		return x.PathInfoPattern
	}
	return ""
}

type CreateHTTPFastcgiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpFastcgiId int64                  `protobuf:"varint,1,opt,name=httpFastcgiId,proto3" json:"httpFastcgiId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHTTPFastcgiResponse) Reset() {
	*x = CreateHTTPFastcgiResponse{}
	mi := &file_service_http_fastcgi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHTTPFastcgiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHTTPFastcgiResponse) ProtoMessage() {}

func (x *CreateHTTPFastcgiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHTTPFastcgiResponse.ProtoReflect.Descriptor instead.
func (*CreateHTTPFastcgiResponse) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHTTPFastcgiResponse) GetHttpFastcgiId() int64 {
	if x != nil {
		return x.HttpFastcgiId
	}
	return 0
}

// 修改Fastcgi服务
type UpdateHTTPFastcgiRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HttpFastcgiId   int64                  `protobuf:"varint,1,opt,name=httpFastcgiId,proto3" json:"httpFastcgiId,omitempty"`
	IsOn            bool                   `protobuf:"varint,2,opt,name=isOn,proto3" json:"isOn,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ParamsJSON      []byte                 `protobuf:"bytes,4,opt,name=paramsJSON,proto3" json:"paramsJSON,omitempty"`
	ReadTimeoutJSON []byte                 `protobuf:"bytes,5,opt,name=readTimeoutJSON,proto3" json:"readTimeoutJSON,omitempty"`
	ConnTimeoutJSON []byte                 `protobuf:"bytes,6,opt,name=connTimeoutJSON,proto3" json:"connTimeoutJSON,omitempty"`
	PoolSize        int32                  `protobuf:"varint,7,opt,name=poolSize,proto3" json:"poolSize,omitempty"`
	PathInfoPattern string                 `protobuf:"bytes,8,opt,name=pathInfoPattern,proto3" json:"pathInfoPattern,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateHTTPFastcgiRequest) Reset() {
	*x = UpdateHTTPFastcgiRequest{}
	mi := &file_service_http_fastcgi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHTTPFastcgiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHTTPFastcgiRequest) ProtoMessage() {}

func (x *UpdateHTTPFastcgiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHTTPFastcgiRequest.ProtoReflect.Descriptor instead.
func (*UpdateHTTPFastcgiRequest) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateHTTPFastcgiRequest) GetHttpFastcgiId() int64 {
	if x != nil {
		return x.HttpFastcgiId
	}
	return 0
}

func (x *UpdateHTTPFastcgiRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *UpdateHTTPFastcgiRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateHTTPFastcgiRequest) GetParamsJSON() []byte {
	if x != nil {
		return x.ParamsJSON
	}
	return nil
}

func (x *UpdateHTTPFastcgiRequest) GetReadTimeoutJSON() []byte {
	if x != nil {
		return x.ReadTimeoutJSON
	}
	return nil
}

func (x *UpdateHTTPFastcgiRequest) GetConnTimeoutJSON() []byte {
	if x != nil {
		return x.ConnTimeoutJSON
	}
	return nil
}

func (x *UpdateHTTPFastcgiRequest) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *UpdateHTTPFastcgiRequest) GetPathInfoPattern() string {
	if x != nil {
		return x.PathInfoPattern
	}
	return ""
}

// 获取Fastcgi详情
type FindEnabledHTTPFastcgiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpFastcgiId int64                  `protobuf:"varint,1,opt,name=httpFastcgiId,proto3" json:"httpFastcgiId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledHTTPFastcgiRequest) Reset() {
	*x = FindEnabledHTTPFastcgiRequest{}
	mi := &file_service_http_fastcgi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledHTTPFastcgiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledHTTPFastcgiRequest) ProtoMessage() {}

func (x *FindEnabledHTTPFastcgiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledHTTPFastcgiRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledHTTPFastcgiRequest) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{3}
}

func (x *FindEnabledHTTPFastcgiRequest) GetHttpFastcgiId() int64 {
	if x != nil {
		return x.HttpFastcgiId
	}
	return 0
}

type FindEnabledHTTPFastcgiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpFastcgi   *HTTPFastcgi           `protobuf:"bytes,1,opt,name=httpFastcgi,proto3" json:"httpFastcgi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledHTTPFastcgiResponse) Reset() {
	*x = FindEnabledHTTPFastcgiResponse{}
	mi := &file_service_http_fastcgi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledHTTPFastcgiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledHTTPFastcgiResponse) ProtoMessage() {}

func (x *FindEnabledHTTPFastcgiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledHTTPFastcgiResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledHTTPFastcgiResponse) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{4}
}

func (x *FindEnabledHTTPFastcgiResponse) GetHttpFastcgi() *HTTPFastcgi {
	if x != nil {
		return x.HttpFastcgi
	}
	return nil
}

// 获取Fastcgi配置
type FindEnabledHTTPFastcgiConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpFastcgiId int64                  `protobuf:"varint,1,opt,name=httpFastcgiId,proto3" json:"httpFastcgiId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledHTTPFastcgiConfigRequest) Reset() {
	*x = FindEnabledHTTPFastcgiConfigRequest{}
	mi := &file_service_http_fastcgi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledHTTPFastcgiConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledHTTPFastcgiConfigRequest) ProtoMessage() {}

func (x *FindEnabledHTTPFastcgiConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledHTTPFastcgiConfigRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledHTTPFastcgiConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{5}
}

func (x *FindEnabledHTTPFastcgiConfigRequest) GetHttpFastcgiId() int64 {
	if x != nil {
		return x.HttpFastcgiId
	}
	return 0
}

type FindEnabledHTTPFastcgiConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HttpFastcgiJSON []byte                 `protobuf:"bytes,1,opt,name=httpFastcgiJSON,proto3" json:"httpFastcgiJSON,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindEnabledHTTPFastcgiConfigResponse) Reset() {
	*x = FindEnabledHTTPFastcgiConfigResponse{}
	mi := &file_service_http_fastcgi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledHTTPFastcgiConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledHTTPFastcgiConfigResponse) ProtoMessage() {}

func (x *FindEnabledHTTPFastcgiConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_fastcgi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledHTTPFastcgiConfigResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledHTTPFastcgiConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_http_fastcgi_proto_rawDescGZIP(), []int{6}
}

func (x *FindEnabledHTTPFastcgiConfigResponse) GetHttpFastcgiJSON() []byte {
	if x != nil {
		return x.HttpFastcgiJSON
	}
	return nil
}

var File_service_http_fastcgi_proto protoreflect.FileDescriptor

const file_service_http_fastcgi_proto_rawDesc = "" +
	"\n" +
	"\x1aservice_http_fastcgi.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\x1a\x1fmodels/model_http_fastcgi.proto\"\x82\x02\n" +
	"\x18CreateHTTPFastcgiRequest\x12\x12\n" +
	"\x04isOn\x18\x01 \x01(\bR\x04isOn\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"paramsJSON\x18\x03 \x01(\fR\n" +
	"paramsJSON\x12(\n" +
	"\x0freadTimeoutJSON\x18\x04 \x01(\fR\x0freadTimeoutJSON\x12(\n" +
	"\x0fconnTimeoutJSON\x18\x05 \x01(\fR\x0fconnTimeoutJSON\x12\x1a\n" +
	"\bpoolSize\x18\x06 \x01(\x05R\bpoolSize\x12(\n" +
	"\x0fpathInfoPattern\x18\a \x01(\tR\x0fpathInfoPattern\"A\n" +
	"\x19CreateHTTPFastcgiResponse\x12$\n" +
	"\rhttpFastcgiId\x18\x01 \x01(\x03R\rhttpFastcgiId\"\xa8\x02\n" +
	"\x18UpdateHTTPFastcgiRequest\x12$\n" +
	"\rhttpFastcgiId\x18\x01 \x01(\x03R\rhttpFastcgiId\x12\x12\n" +
	"\x04isOn\x18\x02 \x01(\bR\x04isOn\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"paramsJSON\x18\x04 \x01(\fR\n" +
	"paramsJSON\x12(\n" +
	"\x0freadTimeoutJSON\x18\x05 \x01(\fR\x0freadTimeoutJSON\x12(\n" +
	"\x0fconnTimeoutJSON\x18\x06 \x01(\fR\x0fconnTimeoutJSON\x12\x1a\n" +
	"\bpoolSize\x18\a \x01(\x05R\bpoolSize\x12(\n" +
	"\x0fpathInfoPattern\x18\b \x01(\tR\x0fpathInfoPattern\"E\n" +
	"\x1dFindEnabledHTTPFastcgiRequest\x12$\n" +
	"\rhttpFastcgiId\x18\x01 \x01(\x03R\rhttpFastcgiId\"S\n" +
	"\x1eFindEnabledHTTPFastcgiResponse\x121\n" +
	"\vhttpFastcgi\x18\x01 \x01(\v2\x0f.pb.HTTPFastcgiR\vhttpFastcgi\"K\n" +
	"#FindEnabledHTTPFastcgiConfigRequest\x12$\n" +
	"\rhttpFastcgiId\x18\x01 \x01(\x03R\rhttpFastcgiId\"P\n" +
	"$FindEnabledHTTPFastcgiConfigResponse\x12(\n" +
	"\x0fhttpFastcgiJSON\x18\x01 \x01(\fR\x0fhttpFastcgiJSON2\xfd\x02\n" +
	"\x12HTTPFastcgiService\x12P\n" +
	"\x11createHTTPFastcgi\x12\x1c.pb.CreateHTTPFastcgiRequest\x1a\x1d.pb.CreateHTTPFastcgiResponse\x12A\n" +
	"\x11updateHTTPFastcgi\x12\x1c.pb.UpdateHTTPFastcgiRequest\x1a\x0e.pb.RPCSuccess\x12_\n" +
	"\x16findEnabledHTTPFastcgi\x12!.pb.FindEnabledHTTPFastcgiRequest\x1a\".pb.FindEnabledHTTPFastcgiResponse\x12q\n" +
	"\x1cfindEnabledHTTPFastcgiConfig\x12'.pb.FindEnabledHTTPFastcgiConfigRequest\x1a(.pb.FindEnabledHTTPFastcgiConfigResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_http_fastcgi_proto_rawDescOnce sync.Once
	file_service_http_fastcgi_proto_rawDescData []byte
)

func file_service_http_fastcgi_proto_rawDescGZIP() []byte {
	file_service_http_fastcgi_proto_rawDescOnce.Do(func() {
		file_service_http_fastcgi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_http_fastcgi_proto_rawDesc), len(file_service_http_fastcgi_proto_rawDesc)))
	})
	return file_service_http_fastcgi_proto_rawDescData
}

var file_service_http_fastcgi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_http_fastcgi_proto_goTypes = []any{
	(*CreateHTTPFastcgiRequest)(nil),             // 0: pb.CreateHTTPFastcgiRequest
	(*CreateHTTPFastcgiResponse)(nil),            // 1: pb.CreateHTTPFastcgiResponse
	(*UpdateHTTPFastcgiRequest)(nil),             // 2: pb.UpdateHTTPFastcgiRequest
	(*FindEnabledHTTPFastcgiRequest)(nil),        // 3: pb.FindEnabledHTTPFastcgiRequest
	(*FindEnabledHTTPFastcgiResponse)(nil),       // 4: pb.FindEnabledHTTPFastcgiResponse
	(*FindEnabledHTTPFastcgiConfigRequest)(nil),  // 5: pb.FindEnabledHTTPFastcgiConfigRequest
	(*FindEnabledHTTPFastcgiConfigResponse)(nil), // 6: pb.FindEnabledHTTPFastcgiConfigResponse
	(*HTTPFastcgi)(nil),                          // 7: pb.HTTPFastcgi
	(*RPCSuccess)(nil),                           // 8: pb.RPCSuccess
}
var file_service_http_fastcgi_proto_depIdxs = []int32{
	7, // 0: pb.FindEnabledHTTPFastcgiResponse.httpFastcgi:type_name -> pb.HTTPFastcgi
	0, // 1: pb.HTTPFastcgiService.createHTTPFastcgi:input_type -> pb.CreateHTTPFastcgiRequest
	2, // 2: pb.HTTPFastcgiService.updateHTTPFastcgi:input_type -> pb.UpdateHTTPFastcgiRequest
	3, // 3: pb.HTTPFastcgiService.findEnabledHTTPFastcgi:input_type -> pb.FindEnabledHTTPFastcgiRequest
	5, // 4: pb.HTTPFastcgiService.findEnabledHTTPFastcgiConfig:input_type -> pb.FindEnabledHTTPFastcgiConfigRequest
	1, // 5: pb.HTTPFastcgiService.createHTTPFastcgi:output_type -> pb.CreateHTTPFastcgiResponse
	8, // 6: pb.HTTPFastcgiService.updateHTTPFastcgi:output_type -> pb.RPCSuccess
	4, // 7: pb.HTTPFastcgiService.findEnabledHTTPFastcgi:output_type -> pb.FindEnabledHTTPFastcgiResponse
	6, // 8: pb.HTTPFastcgiService.findEnabledHTTPFastcgiConfig:output_type -> pb.FindEnabledHTTPFastcgiConfigResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_http_fastcgi_proto_init() }
func file_service_http_fastcgi_proto_init() {
	if File_service_http_fastcgi_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	file_models_model_http_fastcgi_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_http_fastcgi_proto_rawDesc), len(file_service_http_fastcgi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_http_fastcgi_proto_goTypes,
		DependencyIndexes: file_service_http_fastcgi_proto_depIdxs,
		MessageInfos:      file_service_http_fastcgi_proto_msgTypes,
	}.Build()
	File_service_http_fastcgi_proto = out.File
	file_service_http_fastcgi_proto_goTypes = nil
	file_service_http_fastcgi_proto_depIdxs = nil
}
