// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_user_account_daily_stat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 列出按天统计
type ListUserAccountDailyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayFrom       string                 `protobuf:"bytes,1,opt,name=dayFrom,proto3" json:"dayFrom,omitempty"`
	DayTo         string                 `protobuf:"bytes,2,opt,name=dayTo,proto3" json:"dayTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountDailyStatsRequest) Reset() {
	*x = ListUserAccountDailyStatsRequest{}
	mi := &file_service_user_account_daily_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountDailyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountDailyStatsRequest) ProtoMessage() {}

func (x *ListUserAccountDailyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_account_daily_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountDailyStatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserAccountDailyStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_user_account_daily_stat_proto_rawDescGZIP(), []int{0}
}

func (x *ListUserAccountDailyStatsRequest) GetDayFrom() string {
	if x != nil {
		return x.DayFrom
	}
	return ""
}

func (x *ListUserAccountDailyStatsRequest) GetDayTo() string {
	if x != nil {
		return x.DayTo
	}
	return ""
}

type ListUserAccountDailyStatsResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Stats         []*ListUserAccountDailyStatsResponse_Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountDailyStatsResponse) Reset() {
	*x = ListUserAccountDailyStatsResponse{}
	mi := &file_service_user_account_daily_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountDailyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountDailyStatsResponse) ProtoMessage() {}

func (x *ListUserAccountDailyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_account_daily_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountDailyStatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserAccountDailyStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_user_account_daily_stat_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserAccountDailyStatsResponse) GetStats() []*ListUserAccountDailyStatsResponse_Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 列出按月统计
type ListUserAccountMonthlyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayFrom       string                 `protobuf:"bytes,1,opt,name=dayFrom,proto3" json:"dayFrom,omitempty"`
	DayTo         string                 `protobuf:"bytes,2,opt,name=dayTo,proto3" json:"dayTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountMonthlyStatsRequest) Reset() {
	*x = ListUserAccountMonthlyStatsRequest{}
	mi := &file_service_user_account_daily_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountMonthlyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountMonthlyStatsRequest) ProtoMessage() {}

func (x *ListUserAccountMonthlyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_account_daily_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountMonthlyStatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserAccountMonthlyStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_user_account_daily_stat_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserAccountMonthlyStatsRequest) GetDayFrom() string {
	if x != nil {
		return x.DayFrom
	}
	return ""
}

func (x *ListUserAccountMonthlyStatsRequest) GetDayTo() string {
	if x != nil {
		return x.DayTo
	}
	return ""
}

type ListUserAccountMonthlyStatsResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Stats         []*ListUserAccountMonthlyStatsResponse_Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountMonthlyStatsResponse) Reset() {
	*x = ListUserAccountMonthlyStatsResponse{}
	mi := &file_service_user_account_daily_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountMonthlyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountMonthlyStatsResponse) ProtoMessage() {}

func (x *ListUserAccountMonthlyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_account_daily_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountMonthlyStatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserAccountMonthlyStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_user_account_daily_stat_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserAccountMonthlyStatsResponse) GetStats() []*ListUserAccountMonthlyStatsResponse_Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ListUserAccountDailyStatsResponse_Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"` // YYYYMMDD
	Income        float32                `protobuf:"fixed32,2,opt,name=income,proto3" json:"income,omitempty"`
	Expense       float32                `protobuf:"fixed32,3,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountDailyStatsResponse_Stat) Reset() {
	*x = ListUserAccountDailyStatsResponse_Stat{}
	mi := &file_service_user_account_daily_stat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountDailyStatsResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountDailyStatsResponse_Stat) ProtoMessage() {}

func (x *ListUserAccountDailyStatsResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_account_daily_stat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountDailyStatsResponse_Stat.ProtoReflect.Descriptor instead.
func (*ListUserAccountDailyStatsResponse_Stat) Descriptor() ([]byte, []int) {
	return file_service_user_account_daily_stat_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListUserAccountDailyStatsResponse_Stat) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *ListUserAccountDailyStatsResponse_Stat) GetIncome() float32 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *ListUserAccountDailyStatsResponse_Stat) GetExpense() float32 {
	if x != nil {
		return x.Expense
	}
	return 0
}

type ListUserAccountMonthlyStatsResponse_Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // YYYYMM
	Income        float32                `protobuf:"fixed32,2,opt,name=income,proto3" json:"income,omitempty"`
	Expense       float32                `protobuf:"fixed32,3,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountMonthlyStatsResponse_Stat) Reset() {
	*x = ListUserAccountMonthlyStatsResponse_Stat{}
	mi := &file_service_user_account_daily_stat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountMonthlyStatsResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountMonthlyStatsResponse_Stat) ProtoMessage() {}

func (x *ListUserAccountMonthlyStatsResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_account_daily_stat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountMonthlyStatsResponse_Stat.ProtoReflect.Descriptor instead.
func (*ListUserAccountMonthlyStatsResponse_Stat) Descriptor() ([]byte, []int) {
	return file_service_user_account_daily_stat_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListUserAccountMonthlyStatsResponse_Stat) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *ListUserAccountMonthlyStatsResponse_Stat) GetIncome() float32 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *ListUserAccountMonthlyStatsResponse_Stat) GetExpense() float32 {
	if x != nil {
		return x.Expense
	}
	return 0
}

var File_service_user_account_daily_stat_proto protoreflect.FileDescriptor

const file_service_user_account_daily_stat_proto_rawDesc = "" +
	"\n" +
	"%service_user_account_daily_stat.proto\x12\x02pb\"R\n" +
	" ListUserAccountDailyStatsRequest\x12\x18\n" +
	"\adayFrom\x18\x01 \x01(\tR\adayFrom\x12\x14\n" +
	"\x05dayTo\x18\x02 \x01(\tR\x05dayTo\"\xb1\x01\n" +
	"!ListUserAccountDailyStatsResponse\x12@\n" +
	"\x05stats\x18\x01 \x03(\v2*.pb.ListUserAccountDailyStatsResponse.StatR\x05stats\x1aJ\n" +
	"\x04Stat\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x02R\x06income\x12\x18\n" +
	"\aexpense\x18\x03 \x01(\x02R\aexpense\"T\n" +
	"\"ListUserAccountMonthlyStatsRequest\x12\x18\n" +
	"\adayFrom\x18\x01 \x01(\tR\adayFrom\x12\x14\n" +
	"\x05dayTo\x18\x02 \x01(\tR\x05dayTo\"\xb9\x01\n" +
	"#ListUserAccountMonthlyStatsResponse\x12B\n" +
	"\x05stats\x18\x01 \x03(\v2,.pb.ListUserAccountMonthlyStatsResponse.StatR\x05stats\x1aN\n" +
	"\x04Stat\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x02R\x06income\x12\x18\n" +
	"\aexpense\x18\x03 \x01(\x02R\aexpense2\xf7\x01\n" +
	"\x1bUserAccountDailyStatService\x12h\n" +
	"\x19listUserAccountDailyStats\x12$.pb.ListUserAccountDailyStatsRequest\x1a%.pb.ListUserAccountDailyStatsResponse\x12n\n" +
	"\x1blistUserAccountMonthlyStats\x12&.pb.ListUserAccountMonthlyStatsRequest\x1a'.pb.ListUserAccountMonthlyStatsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_user_account_daily_stat_proto_rawDescOnce sync.Once
	file_service_user_account_daily_stat_proto_rawDescData []byte
)

func file_service_user_account_daily_stat_proto_rawDescGZIP() []byte {
	file_service_user_account_daily_stat_proto_rawDescOnce.Do(func() {
		file_service_user_account_daily_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_user_account_daily_stat_proto_rawDesc), len(file_service_user_account_daily_stat_proto_rawDesc)))
	})
	return file_service_user_account_daily_stat_proto_rawDescData
}

var file_service_user_account_daily_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_user_account_daily_stat_proto_goTypes = []any{
	(*ListUserAccountDailyStatsRequest)(nil),         // 0: pb.ListUserAccountDailyStatsRequest
	(*ListUserAccountDailyStatsResponse)(nil),        // 1: pb.ListUserAccountDailyStatsResponse
	(*ListUserAccountMonthlyStatsRequest)(nil),       // 2: pb.ListUserAccountMonthlyStatsRequest
	(*ListUserAccountMonthlyStatsResponse)(nil),      // 3: pb.ListUserAccountMonthlyStatsResponse
	(*ListUserAccountDailyStatsResponse_Stat)(nil),   // 4: pb.ListUserAccountDailyStatsResponse.Stat
	(*ListUserAccountMonthlyStatsResponse_Stat)(nil), // 5: pb.ListUserAccountMonthlyStatsResponse.Stat
}
var file_service_user_account_daily_stat_proto_depIdxs = []int32{
	4, // 0: pb.ListUserAccountDailyStatsResponse.stats:type_name -> pb.ListUserAccountDailyStatsResponse.Stat
	5, // 1: pb.ListUserAccountMonthlyStatsResponse.stats:type_name -> pb.ListUserAccountMonthlyStatsResponse.Stat
	0, // 2: pb.UserAccountDailyStatService.listUserAccountDailyStats:input_type -> pb.ListUserAccountDailyStatsRequest
	2, // 3: pb.UserAccountDailyStatService.listUserAccountMonthlyStats:input_type -> pb.ListUserAccountMonthlyStatsRequest
	1, // 4: pb.UserAccountDailyStatService.listUserAccountDailyStats:output_type -> pb.ListUserAccountDailyStatsResponse
	3, // 5: pb.UserAccountDailyStatService.listUserAccountMonthlyStats:output_type -> pb.ListUserAccountMonthlyStatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_user_account_daily_stat_proto_init() }
func file_service_user_account_daily_stat_proto_init() {
	if File_service_user_account_daily_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_user_account_daily_stat_proto_rawDesc), len(file_service_user_account_daily_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_account_daily_stat_proto_goTypes,
		DependencyIndexes: file_service_user_account_daily_stat_proto_depIdxs,
		MessageInfos:      file_service_user_account_daily_stat_proto_msgTypes,
	}.Build()
	File_service_user_account_daily_stat_proto = out.File
	file_service_user_account_daily_stat_proto_goTypes = nil
	file_service_user_account_daily_stat_proto_depIdxs = nil
}
