// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_http_header.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建Header
type CreateHTTPHeaderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value             string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Status            []int32                `protobuf:"varint,3,rep,packed,name=status,proto3" json:"status,omitempty"`
	DisableRedirect   bool                   `protobuf:"varint,4,opt,name=disableRedirect,proto3" json:"disableRedirect,omitempty"`
	ShouldAppend      bool                   `protobuf:"varint,5,opt,name=shouldAppend,proto3" json:"shouldAppend,omitempty"`
	ShouldReplace     bool                   `protobuf:"varint,6,opt,name=shouldReplace,proto3" json:"shouldReplace,omitempty"`
	ReplaceValuesJSON []byte                 `protobuf:"bytes,7,opt,name=replaceValuesJSON,proto3" json:"replaceValuesJSON,omitempty"`
	Methods           []string               `protobuf:"bytes,8,rep,name=methods,proto3" json:"methods,omitempty"`
	Domains           []string               `protobuf:"bytes,9,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateHTTPHeaderRequest) Reset() {
	*x = CreateHTTPHeaderRequest{}
	mi := &file_service_http_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHTTPHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHTTPHeaderRequest) ProtoMessage() {}

func (x *CreateHTTPHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHTTPHeaderRequest.ProtoReflect.Descriptor instead.
func (*CreateHTTPHeaderRequest) Descriptor() ([]byte, []int) {
	return file_service_http_header_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHTTPHeaderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHTTPHeaderRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateHTTPHeaderRequest) GetStatus() []int32 {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateHTTPHeaderRequest) GetDisableRedirect() bool {
	if x != nil {
		return x.DisableRedirect
	}
	return false
}

func (x *CreateHTTPHeaderRequest) GetShouldAppend() bool {
	if x != nil {
		return x.ShouldAppend
	}
	return false
}

func (x *CreateHTTPHeaderRequest) GetShouldReplace() bool {
	if x != nil {
		return x.ShouldReplace
	}
	return false
}

func (x *CreateHTTPHeaderRequest) GetReplaceValuesJSON() []byte {
	if x != nil {
		return x.ReplaceValuesJSON
	}
	return nil
}

func (x *CreateHTTPHeaderRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *CreateHTTPHeaderRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type CreateHTTPHeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderId      int64                  `protobuf:"varint,1,opt,name=headerId,proto3" json:"headerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHTTPHeaderResponse) Reset() {
	*x = CreateHTTPHeaderResponse{}
	mi := &file_service_http_header_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHTTPHeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHTTPHeaderResponse) ProtoMessage() {}

func (x *CreateHTTPHeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_header_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHTTPHeaderResponse.ProtoReflect.Descriptor instead.
func (*CreateHTTPHeaderResponse) Descriptor() ([]byte, []int) {
	return file_service_http_header_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHTTPHeaderResponse) GetHeaderId() int64 {
	if x != nil {
		return x.HeaderId
	}
	return 0
}

// 修改Header
type UpdateHTTPHeaderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeaderId          int64                  `protobuf:"varint,1,opt,name=headerId,proto3" json:"headerId,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value             string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Status            []int32                `protobuf:"varint,4,rep,packed,name=status,proto3" json:"status,omitempty"`
	DisableRedirect   bool                   `protobuf:"varint,5,opt,name=disableRedirect,proto3" json:"disableRedirect,omitempty"`
	ShouldAppend      bool                   `protobuf:"varint,6,opt,name=shouldAppend,proto3" json:"shouldAppend,omitempty"`
	ShouldReplace     bool                   `protobuf:"varint,7,opt,name=shouldReplace,proto3" json:"shouldReplace,omitempty"`
	ReplaceValuesJSON []byte                 `protobuf:"bytes,8,opt,name=replaceValuesJSON,proto3" json:"replaceValuesJSON,omitempty"`
	Methods           []string               `protobuf:"bytes,9,rep,name=methods,proto3" json:"methods,omitempty"`
	Domains           []string               `protobuf:"bytes,10,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateHTTPHeaderRequest) Reset() {
	*x = UpdateHTTPHeaderRequest{}
	mi := &file_service_http_header_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHTTPHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHTTPHeaderRequest) ProtoMessage() {}

func (x *UpdateHTTPHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_header_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHTTPHeaderRequest.ProtoReflect.Descriptor instead.
func (*UpdateHTTPHeaderRequest) Descriptor() ([]byte, []int) {
	return file_service_http_header_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateHTTPHeaderRequest) GetHeaderId() int64 {
	if x != nil {
		return x.HeaderId
	}
	return 0
}

func (x *UpdateHTTPHeaderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateHTTPHeaderRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateHTTPHeaderRequest) GetStatus() []int32 {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateHTTPHeaderRequest) GetDisableRedirect() bool {
	if x != nil {
		return x.DisableRedirect
	}
	return false
}

func (x *UpdateHTTPHeaderRequest) GetShouldAppend() bool {
	if x != nil {
		return x.ShouldAppend
	}
	return false
}

func (x *UpdateHTTPHeaderRequest) GetShouldReplace() bool {
	if x != nil {
		return x.ShouldReplace
	}
	return false
}

func (x *UpdateHTTPHeaderRequest) GetReplaceValuesJSON() []byte {
	if x != nil {
		return x.ReplaceValuesJSON
	}
	return nil
}

func (x *UpdateHTTPHeaderRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *UpdateHTTPHeaderRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

// 查找配置
type FindEnabledHTTPHeaderConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderId      int64                  `protobuf:"varint,1,opt,name=headerId,proto3" json:"headerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledHTTPHeaderConfigRequest) Reset() {
	*x = FindEnabledHTTPHeaderConfigRequest{}
	mi := &file_service_http_header_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledHTTPHeaderConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledHTTPHeaderConfigRequest) ProtoMessage() {}

func (x *FindEnabledHTTPHeaderConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_header_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledHTTPHeaderConfigRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledHTTPHeaderConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_http_header_proto_rawDescGZIP(), []int{3}
}

func (x *FindEnabledHTTPHeaderConfigRequest) GetHeaderId() int64 {
	if x != nil {
		return x.HeaderId
	}
	return 0
}

type FindEnabledHTTPHeaderConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderJSON    []byte                 `protobuf:"bytes,1,opt,name=headerJSON,proto3" json:"headerJSON,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledHTTPHeaderConfigResponse) Reset() {
	*x = FindEnabledHTTPHeaderConfigResponse{}
	mi := &file_service_http_header_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledHTTPHeaderConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledHTTPHeaderConfigResponse) ProtoMessage() {}

func (x *FindEnabledHTTPHeaderConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_header_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledHTTPHeaderConfigResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledHTTPHeaderConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_http_header_proto_rawDescGZIP(), []int{4}
}

func (x *FindEnabledHTTPHeaderConfigResponse) GetHeaderJSON() []byte {
	if x != nil {
		return x.HeaderJSON
	}
	return nil
}

var File_service_http_header_proto protoreflect.FileDescriptor

const file_service_http_header_proto_rawDesc = "" +
	"\n" +
	"\x19service_http_header.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\"\xb1\x02\n" +
	"\x17CreateHTTPHeaderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06status\x18\x03 \x03(\x05R\x06status\x12(\n" +
	"\x0fdisableRedirect\x18\x04 \x01(\bR\x0fdisableRedirect\x12\"\n" +
	"\fshouldAppend\x18\x05 \x01(\bR\fshouldAppend\x12$\n" +
	"\rshouldReplace\x18\x06 \x01(\bR\rshouldReplace\x12,\n" +
	"\x11replaceValuesJSON\x18\a \x01(\fR\x11replaceValuesJSON\x12\x18\n" +
	"\amethods\x18\b \x03(\tR\amethods\x12\x18\n" +
	"\adomains\x18\t \x03(\tR\adomains\"6\n" +
	"\x18CreateHTTPHeaderResponse\x12\x1a\n" +
	"\bheaderId\x18\x01 \x01(\x03R\bheaderId\"\xcd\x02\n" +
	"\x17UpdateHTTPHeaderRequest\x12\x1a\n" +
	"\bheaderId\x18\x01 \x01(\x03R\bheaderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06status\x18\x04 \x03(\x05R\x06status\x12(\n" +
	"\x0fdisableRedirect\x18\x05 \x01(\bR\x0fdisableRedirect\x12\"\n" +
	"\fshouldAppend\x18\x06 \x01(\bR\fshouldAppend\x12$\n" +
	"\rshouldReplace\x18\a \x01(\bR\rshouldReplace\x12,\n" +
	"\x11replaceValuesJSON\x18\b \x01(\fR\x11replaceValuesJSON\x12\x18\n" +
	"\amethods\x18\t \x03(\tR\amethods\x12\x18\n" +
	"\adomains\x18\n" +
	" \x03(\tR\adomains\"@\n" +
	"\"FindEnabledHTTPHeaderConfigRequest\x12\x1a\n" +
	"\bheaderId\x18\x01 \x01(\x03R\bheaderId\"E\n" +
	"#FindEnabledHTTPHeaderConfigResponse\x12\x1e\n" +
	"\n" +
	"headerJSON\x18\x01 \x01(\fR\n" +
	"headerJSON2\x93\x02\n" +
	"\x11HTTPHeaderService\x12M\n" +
	"\x10createHTTPHeader\x12\x1b.pb.CreateHTTPHeaderRequest\x1a\x1c.pb.CreateHTTPHeaderResponse\x12?\n" +
	"\x10updateHTTPHeader\x12\x1b.pb.UpdateHTTPHeaderRequest\x1a\x0e.pb.RPCSuccess\x12n\n" +
	"\x1bfindEnabledHTTPHeaderConfig\x12&.pb.FindEnabledHTTPHeaderConfigRequest\x1a'.pb.FindEnabledHTTPHeaderConfigResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_http_header_proto_rawDescOnce sync.Once
	file_service_http_header_proto_rawDescData []byte
)

func file_service_http_header_proto_rawDescGZIP() []byte {
	file_service_http_header_proto_rawDescOnce.Do(func() {
		file_service_http_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_http_header_proto_rawDesc), len(file_service_http_header_proto_rawDesc)))
	})
	return file_service_http_header_proto_rawDescData
}

var file_service_http_header_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_service_http_header_proto_goTypes = []any{
	(*CreateHTTPHeaderRequest)(nil),             // 0: pb.CreateHTTPHeaderRequest
	(*CreateHTTPHeaderResponse)(nil),            // 1: pb.CreateHTTPHeaderResponse
	(*UpdateHTTPHeaderRequest)(nil),             // 2: pb.UpdateHTTPHeaderRequest
	(*FindEnabledHTTPHeaderConfigRequest)(nil),  // 3: pb.FindEnabledHTTPHeaderConfigRequest
	(*FindEnabledHTTPHeaderConfigResponse)(nil), // 4: pb.FindEnabledHTTPHeaderConfigResponse
	(*RPCSuccess)(nil),                          // 5: pb.RPCSuccess
}
var file_service_http_header_proto_depIdxs = []int32{
	0, // 0: pb.HTTPHeaderService.createHTTPHeader:input_type -> pb.CreateHTTPHeaderRequest
	2, // 1: pb.HTTPHeaderService.updateHTTPHeader:input_type -> pb.UpdateHTTPHeaderRequest
	3, // 2: pb.HTTPHeaderService.findEnabledHTTPHeaderConfig:input_type -> pb.FindEnabledHTTPHeaderConfigRequest
	1, // 3: pb.HTTPHeaderService.createHTTPHeader:output_type -> pb.CreateHTTPHeaderResponse
	5, // 4: pb.HTTPHeaderService.updateHTTPHeader:output_type -> pb.RPCSuccess
	4, // 5: pb.HTTPHeaderService.findEnabledHTTPHeaderConfig:output_type -> pb.FindEnabledHTTPHeaderConfigResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_http_header_proto_init() }
func file_service_http_header_proto_init() {
	if File_service_http_header_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_http_header_proto_rawDesc), len(file_service_http_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_http_header_proto_goTypes,
		DependencyIndexes: file_service_http_header_proto_depIdxs,
		MessageInfos:      file_service_http_header_proto_msgTypes,
	}.Build()
	File_service_http_header_proto = out.File
	file_service_http_header_proto_goTypes = nil
	file_service_http_header_proto_depIdxs = nil
}
