// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_region_town.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查找所有区县
type FindAllRegionTownsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IncludeRegionCity bool                   `protobuf:"varint,1,opt,name=includeRegionCity,proto3" json:"includeRegionCity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindAllRegionTownsRequest) Reset() {
	*x = FindAllRegionTownsRequest{}
	mi := &file_service_region_town_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRegionTownsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRegionTownsRequest) ProtoMessage() {}

func (x *FindAllRegionTownsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRegionTownsRequest.ProtoReflect.Descriptor instead.
func (*FindAllRegionTownsRequest) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllRegionTownsRequest) GetIncludeRegionCity() bool {
	if x != nil {
		return x.IncludeRegionCity
	}
	return false
}

type FindAllRegionTownsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionTowns   []*RegionTown          `protobuf:"bytes,1,rep,name=regionTowns,proto3" json:"regionTowns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRegionTownsResponse) Reset() {
	*x = FindAllRegionTownsResponse{}
	mi := &file_service_region_town_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRegionTownsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRegionTownsResponse) ProtoMessage() {}

func (x *FindAllRegionTownsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRegionTownsResponse.ProtoReflect.Descriptor instead.
func (*FindAllRegionTownsResponse) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllRegionTownsResponse) GetRegionTowns() []*RegionTown {
	if x != nil {
		return x.RegionTowns
	}
	return nil
}

// 查找某个城市的所有区县
type FindAllRegionTownsWithRegionCityIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionCityId  int64                  `protobuf:"varint,1,opt,name=regionCityId,proto3" json:"regionCityId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRegionTownsWithRegionCityIdRequest) Reset() {
	*x = FindAllRegionTownsWithRegionCityIdRequest{}
	mi := &file_service_region_town_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRegionTownsWithRegionCityIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRegionTownsWithRegionCityIdRequest) ProtoMessage() {}

func (x *FindAllRegionTownsWithRegionCityIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRegionTownsWithRegionCityIdRequest.ProtoReflect.Descriptor instead.
func (*FindAllRegionTownsWithRegionCityIdRequest) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllRegionTownsWithRegionCityIdRequest) GetRegionCityId() int64 {
	if x != nil {
		return x.RegionCityId
	}
	return 0
}

type FindAllRegionTownsWithRegionCityIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionTowns   []*RegionTown          `protobuf:"bytes,1,rep,name=regionTowns,proto3" json:"regionTowns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRegionTownsWithRegionCityIdResponse) Reset() {
	*x = FindAllRegionTownsWithRegionCityIdResponse{}
	mi := &file_service_region_town_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRegionTownsWithRegionCityIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRegionTownsWithRegionCityIdResponse) ProtoMessage() {}

func (x *FindAllRegionTownsWithRegionCityIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRegionTownsWithRegionCityIdResponse.ProtoReflect.Descriptor instead.
func (*FindAllRegionTownsWithRegionCityIdResponse) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllRegionTownsWithRegionCityIdResponse) GetRegionTowns() []*RegionTown {
	if x != nil {
		return x.RegionTowns
	}
	return nil
}

// 查找单个区县信息
type FindRegionTownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionTownId  int64                  `protobuf:"varint,1,opt,name=regionTownId,proto3" json:"regionTownId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRegionTownRequest) Reset() {
	*x = FindRegionTownRequest{}
	mi := &file_service_region_town_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRegionTownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRegionTownRequest) ProtoMessage() {}

func (x *FindRegionTownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRegionTownRequest.ProtoReflect.Descriptor instead.
func (*FindRegionTownRequest) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{4}
}

func (x *FindRegionTownRequest) GetRegionTownId() int64 {
	if x != nil {
		return x.RegionTownId
	}
	return 0
}

type FindRegionTownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionTown    *RegionTown            `protobuf:"bytes,1,opt,name=regionTown,proto3" json:"regionTown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRegionTownResponse) Reset() {
	*x = FindRegionTownResponse{}
	mi := &file_service_region_town_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRegionTownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRegionTownResponse) ProtoMessage() {}

func (x *FindRegionTownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRegionTownResponse.ProtoReflect.Descriptor instead.
func (*FindRegionTownResponse) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{5}
}

func (x *FindRegionTownResponse) GetRegionTown() *RegionTown {
	if x != nil {
		return x.RegionTown
	}
	return nil
}

// 修改区县定制信息
type UpdateRegionTownCustomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionTownId  int64                  `protobuf:"varint,1,opt,name=regionTownId,proto3" json:"regionTownId,omitempty"`
	CustomName    string                 `protobuf:"bytes,2,opt,name=customName,proto3" json:"customName,omitempty"`
	CustomCodes   []string               `protobuf:"bytes,3,rep,name=customCodes,proto3" json:"customCodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegionTownCustomRequest) Reset() {
	*x = UpdateRegionTownCustomRequest{}
	mi := &file_service_region_town_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegionTownCustomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegionTownCustomRequest) ProtoMessage() {}

func (x *UpdateRegionTownCustomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_region_town_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegionTownCustomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegionTownCustomRequest) Descriptor() ([]byte, []int) {
	return file_service_region_town_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRegionTownCustomRequest) GetRegionTownId() int64 {
	if x != nil {
		return x.RegionTownId
	}
	return 0
}

func (x *UpdateRegionTownCustomRequest) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

func (x *UpdateRegionTownCustomRequest) GetCustomCodes() []string {
	if x != nil {
		return x.CustomCodes
	}
	return nil
}

var File_service_region_town_proto protoreflect.FileDescriptor

const file_service_region_town_proto_rawDesc = "" +
	"\n" +
	"\x19service_region_town.proto\x12\x02pb\x1a\x1emodels/model_region_town.proto\x1a\x19models/rpc_messages.proto\"I\n" +
	"\x19FindAllRegionTownsRequest\x12,\n" +
	"\x11includeRegionCity\x18\x01 \x01(\bR\x11includeRegionCity\"N\n" +
	"\x1aFindAllRegionTownsResponse\x120\n" +
	"\vregionTowns\x18\x01 \x03(\v2\x0e.pb.RegionTownR\vregionTowns\"O\n" +
	")FindAllRegionTownsWithRegionCityIdRequest\x12\"\n" +
	"\fregionCityId\x18\x01 \x01(\x03R\fregionCityId\"^\n" +
	"*FindAllRegionTownsWithRegionCityIdResponse\x120\n" +
	"\vregionTowns\x18\x01 \x03(\v2\x0e.pb.RegionTownR\vregionTowns\";\n" +
	"\x15FindRegionTownRequest\x12\"\n" +
	"\fregionTownId\x18\x01 \x01(\x03R\fregionTownId\"H\n" +
	"\x16FindRegionTownResponse\x12.\n" +
	"\n" +
	"regionTown\x18\x01 \x01(\v2\x0e.pb.RegionTownR\n" +
	"regionTown\"\x85\x01\n" +
	"\x1dUpdateRegionTownCustomRequest\x12\"\n" +
	"\fregionTownId\x18\x01 \x01(\x03R\fregionTownId\x12\x1e\n" +
	"\n" +
	"customName\x18\x02 \x01(\tR\n" +
	"customName\x12 \n" +
	"\vcustomCodes\x18\x03 \x03(\tR\vcustomCodes2\x84\x03\n" +
	"\x11RegionTownService\x12S\n" +
	"\x12findAllRegionTowns\x12\x1d.pb.FindAllRegionTownsRequest\x1a\x1e.pb.FindAllRegionTownsResponse\x12\x83\x01\n" +
	"\"findAllRegionTownsWithRegionCityId\x12-.pb.FindAllRegionTownsWithRegionCityIdRequest\x1a..pb.FindAllRegionTownsWithRegionCityIdResponse\x12G\n" +
	"\x0efindRegionTown\x12\x19.pb.FindRegionTownRequest\x1a\x1a.pb.FindRegionTownResponse\x12K\n" +
	"\x16updateRegionTownCustom\x12!.pb.UpdateRegionTownCustomRequest\x1a\x0e.pb.RPCSuccessB\x06Z\x04./pbb\x06proto3"

var (
	file_service_region_town_proto_rawDescOnce sync.Once
	file_service_region_town_proto_rawDescData []byte
)

func file_service_region_town_proto_rawDescGZIP() []byte {
	file_service_region_town_proto_rawDescOnce.Do(func() {
		file_service_region_town_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_region_town_proto_rawDesc), len(file_service_region_town_proto_rawDesc)))
	})
	return file_service_region_town_proto_rawDescData
}

var file_service_region_town_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_region_town_proto_goTypes = []any{
	(*FindAllRegionTownsRequest)(nil),                  // 0: pb.FindAllRegionTownsRequest
	(*FindAllRegionTownsResponse)(nil),                 // 1: pb.FindAllRegionTownsResponse
	(*FindAllRegionTownsWithRegionCityIdRequest)(nil),  // 2: pb.FindAllRegionTownsWithRegionCityIdRequest
	(*FindAllRegionTownsWithRegionCityIdResponse)(nil), // 3: pb.FindAllRegionTownsWithRegionCityIdResponse
	(*FindRegionTownRequest)(nil),                      // 4: pb.FindRegionTownRequest
	(*FindRegionTownResponse)(nil),                     // 5: pb.FindRegionTownResponse
	(*UpdateRegionTownCustomRequest)(nil),              // 6: pb.UpdateRegionTownCustomRequest
	(*RegionTown)(nil),                                 // 7: pb.RegionTown
	(*RPCSuccess)(nil),                                 // 8: pb.RPCSuccess
}
var file_service_region_town_proto_depIdxs = []int32{
	7, // 0: pb.FindAllRegionTownsResponse.regionTowns:type_name -> pb.RegionTown
	7, // 1: pb.FindAllRegionTownsWithRegionCityIdResponse.regionTowns:type_name -> pb.RegionTown
	7, // 2: pb.FindRegionTownResponse.regionTown:type_name -> pb.RegionTown
	0, // 3: pb.RegionTownService.findAllRegionTowns:input_type -> pb.FindAllRegionTownsRequest
	2, // 4: pb.RegionTownService.findAllRegionTownsWithRegionCityId:input_type -> pb.FindAllRegionTownsWithRegionCityIdRequest
	4, // 5: pb.RegionTownService.findRegionTown:input_type -> pb.FindRegionTownRequest
	6, // 6: pb.RegionTownService.updateRegionTownCustom:input_type -> pb.UpdateRegionTownCustomRequest
	1, // 7: pb.RegionTownService.findAllRegionTowns:output_type -> pb.FindAllRegionTownsResponse
	3, // 8: pb.RegionTownService.findAllRegionTownsWithRegionCityId:output_type -> pb.FindAllRegionTownsWithRegionCityIdResponse
	5, // 9: pb.RegionTownService.findRegionTown:output_type -> pb.FindRegionTownResponse
	8, // 10: pb.RegionTownService.updateRegionTownCustom:output_type -> pb.RPCSuccess
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_region_town_proto_init() }
func file_service_region_town_proto_init() {
	if File_service_region_town_proto != nil {
		return
	}
	file_models_model_region_town_proto_init()
	file_models_rpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_region_town_proto_rawDesc), len(file_service_region_town_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_region_town_proto_goTypes,
		DependencyIndexes: file_service_region_town_proto_depIdxs,
		MessageInfos:      file_service_region_town_proto_msgTypes,
	}.Build()
	File_service_region_town_proto = out.File
	file_service_region_town_proto_goTypes = nil
	file_service_region_town_proto_depIdxs = nil
}
