// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_node_region.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建区域
type CreateNodeRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRegionRequest) Reset() {
	*x = CreateNodeRegionRequest{}
	mi := &file_service_node_region_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRegionRequest) ProtoMessage() {}

func (x *CreateNodeRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRegionRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeRegionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRegionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateNodeRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegionId  int64                  `protobuf:"varint,1,opt,name=nodeRegionId,proto3" json:"nodeRegionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRegionResponse) Reset() {
	*x = CreateNodeRegionResponse{}
	mi := &file_service_node_region_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRegionResponse) ProtoMessage() {}

func (x *CreateNodeRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRegionResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeRegionResponse) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeRegionResponse) GetNodeRegionId() int64 {
	if x != nil {
		return x.NodeRegionId
	}
	return 0
}

// 修改区域
type UpdateNodeRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegionId  int64                  `protobuf:"varint,1,opt,name=nodeRegionId,proto3" json:"nodeRegionId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsOn          bool                   `protobuf:"varint,4,opt,name=isOn,proto3" json:"isOn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRegionRequest) Reset() {
	*x = UpdateNodeRegionRequest{}
	mi := &file_service_node_region_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRegionRequest) ProtoMessage() {}

func (x *UpdateNodeRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRegionRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRegionRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNodeRegionRequest) GetNodeRegionId() int64 {
	if x != nil {
		return x.NodeRegionId
	}
	return 0
}

func (x *UpdateNodeRegionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNodeRegionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateNodeRegionRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

// 删除区域
type DeleteNodeRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegionId  int64                  `protobuf:"varint,1,opt,name=nodeRegionId,proto3" json:"nodeRegionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRegionRequest) Reset() {
	*x = DeleteNodeRegionRequest{}
	mi := &file_service_node_region_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRegionRequest) ProtoMessage() {}

func (x *DeleteNodeRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRegionRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRegionRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNodeRegionRequest) GetNodeRegionId() int64 {
	if x != nil {
		return x.NodeRegionId
	}
	return 0
}

// 查找所有区域
type FindAllEnabledNodeRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEnabledNodeRegionsRequest) Reset() {
	*x = FindAllEnabledNodeRegionsRequest{}
	mi := &file_service_node_region_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEnabledNodeRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEnabledNodeRegionsRequest) ProtoMessage() {}

func (x *FindAllEnabledNodeRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEnabledNodeRegionsRequest.ProtoReflect.Descriptor instead.
func (*FindAllEnabledNodeRegionsRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{4}
}

type FindAllEnabledNodeRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegions   []*NodeRegion          `protobuf:"bytes,1,rep,name=nodeRegions,proto3" json:"nodeRegions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEnabledNodeRegionsResponse) Reset() {
	*x = FindAllEnabledNodeRegionsResponse{}
	mi := &file_service_node_region_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEnabledNodeRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEnabledNodeRegionsResponse) ProtoMessage() {}

func (x *FindAllEnabledNodeRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEnabledNodeRegionsResponse.ProtoReflect.Descriptor instead.
func (*FindAllEnabledNodeRegionsResponse) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllEnabledNodeRegionsResponse) GetNodeRegions() []*NodeRegion {
	if x != nil {
		return x.NodeRegions
	}
	return nil
}

// 查找所有启用的区域
type FindAllAvailableNodeRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllAvailableNodeRegionsRequest) Reset() {
	*x = FindAllAvailableNodeRegionsRequest{}
	mi := &file_service_node_region_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllAvailableNodeRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAvailableNodeRegionsRequest) ProtoMessage() {}

func (x *FindAllAvailableNodeRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAvailableNodeRegionsRequest.ProtoReflect.Descriptor instead.
func (*FindAllAvailableNodeRegionsRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{6}
}

type FindAllAvailableNodeRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegions   []*NodeRegion          `protobuf:"bytes,1,rep,name=nodeRegions,proto3" json:"nodeRegions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllAvailableNodeRegionsResponse) Reset() {
	*x = FindAllAvailableNodeRegionsResponse{}
	mi := &file_service_node_region_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllAvailableNodeRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAvailableNodeRegionsResponse) ProtoMessage() {}

func (x *FindAllAvailableNodeRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAvailableNodeRegionsResponse.ProtoReflect.Descriptor instead.
func (*FindAllAvailableNodeRegionsResponse) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllAvailableNodeRegionsResponse) GetNodeRegions() []*NodeRegion {
	if x != nil {
		return x.NodeRegions
	}
	return nil
}

// 排序
type UpdateNodeRegionOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegionIds []int64                `protobuf:"varint,1,rep,packed,name=nodeRegionIds,proto3" json:"nodeRegionIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRegionOrdersRequest) Reset() {
	*x = UpdateNodeRegionOrdersRequest{}
	mi := &file_service_node_region_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRegionOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRegionOrdersRequest) ProtoMessage() {}

func (x *UpdateNodeRegionOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRegionOrdersRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRegionOrdersRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNodeRegionOrdersRequest) GetNodeRegionIds() []int64 {
	if x != nil {
		return x.NodeRegionIds
	}
	return nil
}

// 查找单个区域信息
type FindEnabledNodeRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegionId  int64                  `protobuf:"varint,1,opt,name=nodeRegionId,proto3" json:"nodeRegionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledNodeRegionRequest) Reset() {
	*x = FindEnabledNodeRegionRequest{}
	mi := &file_service_node_region_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledNodeRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledNodeRegionRequest) ProtoMessage() {}

func (x *FindEnabledNodeRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledNodeRegionRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledNodeRegionRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{9}
}

func (x *FindEnabledNodeRegionRequest) GetNodeRegionId() int64 {
	if x != nil {
		return x.NodeRegionId
	}
	return 0
}

type FindEnabledNodeRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegion    *NodeRegion            `protobuf:"bytes,1,opt,name=nodeRegion,proto3" json:"nodeRegion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledNodeRegionResponse) Reset() {
	*x = FindEnabledNodeRegionResponse{}
	mi := &file_service_node_region_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledNodeRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledNodeRegionResponse) ProtoMessage() {}

func (x *FindEnabledNodeRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledNodeRegionResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledNodeRegionResponse) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{10}
}

func (x *FindEnabledNodeRegionResponse) GetNodeRegion() *NodeRegion {
	if x != nil {
		return x.NodeRegion
	}
	return nil
}

// 修改价格项价格
type UpdateNodeRegionPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRegionId  int64                  `protobuf:"varint,1,opt,name=nodeRegionId,proto3" json:"nodeRegionId,omitempty"`
	NodeItemId    int64                  `protobuf:"varint,2,opt,name=nodeItemId,proto3" json:"nodeItemId,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRegionPriceRequest) Reset() {
	*x = UpdateNodeRegionPriceRequest{}
	mi := &file_service_node_region_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRegionPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRegionPriceRequest) ProtoMessage() {}

func (x *UpdateNodeRegionPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_node_region_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRegionPriceRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRegionPriceRequest) Descriptor() ([]byte, []int) {
	return file_service_node_region_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNodeRegionPriceRequest) GetNodeRegionId() int64 {
	if x != nil {
		return x.NodeRegionId
	}
	return 0
}

func (x *UpdateNodeRegionPriceRequest) GetNodeItemId() int64 {
	if x != nil {
		return x.NodeItemId
	}
	return 0
}

func (x *UpdateNodeRegionPriceRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_service_node_region_proto protoreflect.FileDescriptor

const file_service_node_region_proto_rawDesc = "" +
	"\n" +
	"\x19service_node_region.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\x1a\x1emodels/model_node_region.proto\"O\n" +
	"\x17CreateNodeRegionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\">\n" +
	"\x18CreateNodeRegionResponse\x12\"\n" +
	"\fnodeRegionId\x18\x01 \x01(\x03R\fnodeRegionId\"\x87\x01\n" +
	"\x17UpdateNodeRegionRequest\x12\"\n" +
	"\fnodeRegionId\x18\x01 \x01(\x03R\fnodeRegionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04isOn\x18\x04 \x01(\bR\x04isOn\"=\n" +
	"\x17DeleteNodeRegionRequest\x12\"\n" +
	"\fnodeRegionId\x18\x01 \x01(\x03R\fnodeRegionId\"\"\n" +
	" FindAllEnabledNodeRegionsRequest\"U\n" +
	"!FindAllEnabledNodeRegionsResponse\x120\n" +
	"\vnodeRegions\x18\x01 \x03(\v2\x0e.pb.NodeRegionR\vnodeRegions\"$\n" +
	"\"FindAllAvailableNodeRegionsRequest\"W\n" +
	"#FindAllAvailableNodeRegionsResponse\x120\n" +
	"\vnodeRegions\x18\x01 \x03(\v2\x0e.pb.NodeRegionR\vnodeRegions\"E\n" +
	"\x1dUpdateNodeRegionOrdersRequest\x12$\n" +
	"\rnodeRegionIds\x18\x01 \x03(\x03R\rnodeRegionIds\"B\n" +
	"\x1cFindEnabledNodeRegionRequest\x12\"\n" +
	"\fnodeRegionId\x18\x01 \x01(\x03R\fnodeRegionId\"O\n" +
	"\x1dFindEnabledNodeRegionResponse\x12.\n" +
	"\n" +
	"nodeRegion\x18\x01 \x01(\v2\x0e.pb.NodeRegionR\n" +
	"nodeRegion\"x\n" +
	"\x1cUpdateNodeRegionPriceRequest\x12\"\n" +
	"\fnodeRegionId\x18\x01 \x01(\x03R\fnodeRegionId\x12\x1e\n" +
	"\n" +
	"nodeItemId\x18\x02 \x01(\x03R\n" +
	"nodeItemId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price2\xb4\x05\n" +
	"\x11NodeRegionService\x12M\n" +
	"\x10createNodeRegion\x12\x1b.pb.CreateNodeRegionRequest\x1a\x1c.pb.CreateNodeRegionResponse\x12?\n" +
	"\x10updateNodeRegion\x12\x1b.pb.UpdateNodeRegionRequest\x1a\x0e.pb.RPCSuccess\x12?\n" +
	"\x10deleteNodeRegion\x12\x1b.pb.DeleteNodeRegionRequest\x1a\x0e.pb.RPCSuccess\x12h\n" +
	"\x19findAllEnabledNodeRegions\x12$.pb.FindAllEnabledNodeRegionsRequest\x1a%.pb.FindAllEnabledNodeRegionsResponse\x12n\n" +
	"\x1bfindAllAvailableNodeRegions\x12&.pb.FindAllAvailableNodeRegionsRequest\x1a'.pb.FindAllAvailableNodeRegionsResponse\x12K\n" +
	"\x16updateNodeRegionOrders\x12!.pb.UpdateNodeRegionOrdersRequest\x1a\x0e.pb.RPCSuccess\x12\\\n" +
	"\x15findEnabledNodeRegion\x12 .pb.FindEnabledNodeRegionRequest\x1a!.pb.FindEnabledNodeRegionResponse\x12I\n" +
	"\x15updateNodeRegionPrice\x12 .pb.UpdateNodeRegionPriceRequest\x1a\x0e.pb.RPCSuccessB\x06Z\x04./pbb\x06proto3"

var (
	file_service_node_region_proto_rawDescOnce sync.Once
	file_service_node_region_proto_rawDescData []byte
)

func file_service_node_region_proto_rawDescGZIP() []byte {
	file_service_node_region_proto_rawDescOnce.Do(func() {
		file_service_node_region_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_node_region_proto_rawDesc), len(file_service_node_region_proto_rawDesc)))
	})
	return file_service_node_region_proto_rawDescData
}

var file_service_node_region_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_service_node_region_proto_goTypes = []any{
	(*CreateNodeRegionRequest)(nil),             // 0: pb.CreateNodeRegionRequest
	(*CreateNodeRegionResponse)(nil),            // 1: pb.CreateNodeRegionResponse
	(*UpdateNodeRegionRequest)(nil),             // 2: pb.UpdateNodeRegionRequest
	(*DeleteNodeRegionRequest)(nil),             // 3: pb.DeleteNodeRegionRequest
	(*FindAllEnabledNodeRegionsRequest)(nil),    // 4: pb.FindAllEnabledNodeRegionsRequest
	(*FindAllEnabledNodeRegionsResponse)(nil),   // 5: pb.FindAllEnabledNodeRegionsResponse
	(*FindAllAvailableNodeRegionsRequest)(nil),  // 6: pb.FindAllAvailableNodeRegionsRequest
	(*FindAllAvailableNodeRegionsResponse)(nil), // 7: pb.FindAllAvailableNodeRegionsResponse
	(*UpdateNodeRegionOrdersRequest)(nil),       // 8: pb.UpdateNodeRegionOrdersRequest
	(*FindEnabledNodeRegionRequest)(nil),        // 9: pb.FindEnabledNodeRegionRequest
	(*FindEnabledNodeRegionResponse)(nil),       // 10: pb.FindEnabledNodeRegionResponse
	(*UpdateNodeRegionPriceRequest)(nil),        // 11: pb.UpdateNodeRegionPriceRequest
	(*NodeRegion)(nil),                          // 12: pb.NodeRegion
	(*RPCSuccess)(nil),                          // 13: pb.RPCSuccess
}
var file_service_node_region_proto_depIdxs = []int32{
	12, // 0: pb.FindAllEnabledNodeRegionsResponse.nodeRegions:type_name -> pb.NodeRegion
	12, // 1: pb.FindAllAvailableNodeRegionsResponse.nodeRegions:type_name -> pb.NodeRegion
	12, // 2: pb.FindEnabledNodeRegionResponse.nodeRegion:type_name -> pb.NodeRegion
	0,  // 3: pb.NodeRegionService.createNodeRegion:input_type -> pb.CreateNodeRegionRequest
	2,  // 4: pb.NodeRegionService.updateNodeRegion:input_type -> pb.UpdateNodeRegionRequest
	3,  // 5: pb.NodeRegionService.deleteNodeRegion:input_type -> pb.DeleteNodeRegionRequest
	4,  // 6: pb.NodeRegionService.findAllEnabledNodeRegions:input_type -> pb.FindAllEnabledNodeRegionsRequest
	6,  // 7: pb.NodeRegionService.findAllAvailableNodeRegions:input_type -> pb.FindAllAvailableNodeRegionsRequest
	8,  // 8: pb.NodeRegionService.updateNodeRegionOrders:input_type -> pb.UpdateNodeRegionOrdersRequest
	9,  // 9: pb.NodeRegionService.findEnabledNodeRegion:input_type -> pb.FindEnabledNodeRegionRequest
	11, // 10: pb.NodeRegionService.updateNodeRegionPrice:input_type -> pb.UpdateNodeRegionPriceRequest
	1,  // 11: pb.NodeRegionService.createNodeRegion:output_type -> pb.CreateNodeRegionResponse
	13, // 12: pb.NodeRegionService.updateNodeRegion:output_type -> pb.RPCSuccess
	13, // 13: pb.NodeRegionService.deleteNodeRegion:output_type -> pb.RPCSuccess
	5,  // 14: pb.NodeRegionService.findAllEnabledNodeRegions:output_type -> pb.FindAllEnabledNodeRegionsResponse
	7,  // 15: pb.NodeRegionService.findAllAvailableNodeRegions:output_type -> pb.FindAllAvailableNodeRegionsResponse
	13, // 16: pb.NodeRegionService.updateNodeRegionOrders:output_type -> pb.RPCSuccess
	10, // 17: pb.NodeRegionService.findEnabledNodeRegion:output_type -> pb.FindEnabledNodeRegionResponse
	13, // 18: pb.NodeRegionService.updateNodeRegionPrice:output_type -> pb.RPCSuccess
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_node_region_proto_init() }
func file_service_node_region_proto_init() {
	if File_service_node_region_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	file_models_model_node_region_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_node_region_proto_rawDesc), len(file_service_node_region_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_node_region_proto_goTypes,
		DependencyIndexes: file_service_node_region_proto_depIdxs,
		MessageInfos:      file_service_node_region_proto_msgTypes,
	}.Build()
	File_service_node_region_proto = out.File
	file_service_node_region_proto_goTypes = nil
	file_service_node_region_proto_depIdxs = nil
}
