// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_server_group.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建分组
type CreateServerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerGroupRequest) Reset() {
	*x = CreateServerGroupRequest{}
	mi := &file_service_server_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerGroupRequest) ProtoMessage() {}

func (x *CreateServerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateServerGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateServerGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateServerGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerGroupResponse) Reset() {
	*x = CreateServerGroupResponse{}
	mi := &file_service_server_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerGroupResponse) ProtoMessage() {}

func (x *CreateServerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateServerGroupResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServerGroupResponse) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

// 修改分组
type UpdateServerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerGroupRequest) Reset() {
	*x = UpdateServerGroupRequest{}
	mi := &file_service_server_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerGroupRequest) ProtoMessage() {}

func (x *UpdateServerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateServerGroupRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

func (x *UpdateServerGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 删除分组
type DeleteServerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerGroupRequest) Reset() {
	*x = DeleteServerGroupRequest{}
	mi := &file_service_server_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerGroupRequest) ProtoMessage() {}

func (x *DeleteServerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteServerGroupRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

// 查询所有分组
type FindAllEnabledServerGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 可选项，用户ID，只有管理员才可以指定用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEnabledServerGroupsRequest) Reset() {
	*x = FindAllEnabledServerGroupsRequest{}
	mi := &file_service_server_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEnabledServerGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEnabledServerGroupsRequest) ProtoMessage() {}

func (x *FindAllEnabledServerGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEnabledServerGroupsRequest.ProtoReflect.Descriptor instead.
func (*FindAllEnabledServerGroupsRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllEnabledServerGroupsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FindAllEnabledServerGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroups  []*ServerGroup         `protobuf:"bytes,1,rep,name=serverGroups,proto3" json:"serverGroups,omitempty"` // 分组列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEnabledServerGroupsResponse) Reset() {
	*x = FindAllEnabledServerGroupsResponse{}
	mi := &file_service_server_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEnabledServerGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEnabledServerGroupsResponse) ProtoMessage() {}

func (x *FindAllEnabledServerGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEnabledServerGroupsResponse.ProtoReflect.Descriptor instead.
func (*FindAllEnabledServerGroupsResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllEnabledServerGroupsResponse) GetServerGroups() []*ServerGroup {
	if x != nil {
		return x.ServerGroups
	}
	return nil
}

// 修改分组排序
type UpdateServerGroupOrdersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupIds []int64                `protobuf:"varint,1,rep,packed,name=serverGroupIds,proto3" json:"serverGroupIds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateServerGroupOrdersRequest) Reset() {
	*x = UpdateServerGroupOrdersRequest{}
	mi := &file_service_server_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerGroupOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerGroupOrdersRequest) ProtoMessage() {}

func (x *UpdateServerGroupOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerGroupOrdersRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerGroupOrdersRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateServerGroupOrdersRequest) GetServerGroupIds() []int64 {
	if x != nil {
		return x.ServerGroupIds
	}
	return nil
}

// 查找单个分组信息
type FindEnabledServerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledServerGroupRequest) Reset() {
	*x = FindEnabledServerGroupRequest{}
	mi := &file_service_server_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledServerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledServerGroupRequest) ProtoMessage() {}

func (x *FindEnabledServerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledServerGroupRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledServerGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{7}
}

func (x *FindEnabledServerGroupRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

type FindEnabledServerGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroup   *ServerGroup           `protobuf:"bytes,1,opt,name=serverGroup,proto3" json:"serverGroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledServerGroupResponse) Reset() {
	*x = FindEnabledServerGroupResponse{}
	mi := &file_service_server_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledServerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledServerGroupResponse) ProtoMessage() {}

func (x *FindEnabledServerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledServerGroupResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledServerGroupResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{8}
}

func (x *FindEnabledServerGroupResponse) GetServerGroup() *ServerGroup {
	if x != nil {
		return x.ServerGroup
	}
	return nil
}

// 查找HTTP反向代理设置
type FindAndInitServerGroupHTTPReverseProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigRequest) Reset() {
	*x = FindAndInitServerGroupHTTPReverseProxyConfigRequest{}
	mi := &file_service_server_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupHTTPReverseProxyConfigRequest) ProtoMessage() {}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupHTTPReverseProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupHTTPReverseProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{9}
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

type FindAndInitServerGroupHTTPReverseProxyConfigResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReverseProxyJSON    []byte                 `protobuf:"bytes,1,opt,name=reverseProxyJSON,proto3" json:"reverseProxyJSON,omitempty"`
	ReverseProxyRefJSON []byte                 `protobuf:"bytes,2,opt,name=reverseProxyRefJSON,proto3" json:"reverseProxyRefJSON,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigResponse) Reset() {
	*x = FindAndInitServerGroupHTTPReverseProxyConfigResponse{}
	mi := &file_service_server_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupHTTPReverseProxyConfigResponse) ProtoMessage() {}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupHTTPReverseProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupHTTPReverseProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{10}
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigResponse) GetReverseProxyJSON() []byte {
	if x != nil {
		return x.ReverseProxyJSON
	}
	return nil
}

func (x *FindAndInitServerGroupHTTPReverseProxyConfigResponse) GetReverseProxyRefJSON() []byte {
	if x != nil {
		return x.ReverseProxyRefJSON
	}
	return nil
}

// 查找TCP反向代理设置
type FindAndInitServerGroupTCPReverseProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigRequest) Reset() {
	*x = FindAndInitServerGroupTCPReverseProxyConfigRequest{}
	mi := &file_service_server_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupTCPReverseProxyConfigRequest) ProtoMessage() {}

func (x *FindAndInitServerGroupTCPReverseProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupTCPReverseProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupTCPReverseProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{11}
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

type FindAndInitServerGroupTCPReverseProxyConfigResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReverseProxyJSON    []byte                 `protobuf:"bytes,1,opt,name=reverseProxyJSON,proto3" json:"reverseProxyJSON,omitempty"`
	ReverseProxyRefJSON []byte                 `protobuf:"bytes,2,opt,name=reverseProxyRefJSON,proto3" json:"reverseProxyRefJSON,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigResponse) Reset() {
	*x = FindAndInitServerGroupTCPReverseProxyConfigResponse{}
	mi := &file_service_server_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupTCPReverseProxyConfigResponse) ProtoMessage() {}

func (x *FindAndInitServerGroupTCPReverseProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupTCPReverseProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupTCPReverseProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{12}
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigResponse) GetReverseProxyJSON() []byte {
	if x != nil {
		return x.ReverseProxyJSON
	}
	return nil
}

func (x *FindAndInitServerGroupTCPReverseProxyConfigResponse) GetReverseProxyRefJSON() []byte {
	if x != nil {
		return x.ReverseProxyRefJSON
	}
	return nil
}

// 查找UDP反向代理设置
type FindAndInitServerGroupUDPReverseProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigRequest) Reset() {
	*x = FindAndInitServerGroupUDPReverseProxyConfigRequest{}
	mi := &file_service_server_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupUDPReverseProxyConfigRequest) ProtoMessage() {}

func (x *FindAndInitServerGroupUDPReverseProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupUDPReverseProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupUDPReverseProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{13}
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

type FindAndInitServerGroupUDPReverseProxyConfigResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReverseProxyJSON    []byte                 `protobuf:"bytes,1,opt,name=reverseProxyJSON,proto3" json:"reverseProxyJSON,omitempty"`
	ReverseProxyRefJSON []byte                 `protobuf:"bytes,2,opt,name=reverseProxyRefJSON,proto3" json:"reverseProxyRefJSON,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigResponse) Reset() {
	*x = FindAndInitServerGroupUDPReverseProxyConfigResponse{}
	mi := &file_service_server_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupUDPReverseProxyConfigResponse) ProtoMessage() {}

func (x *FindAndInitServerGroupUDPReverseProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupUDPReverseProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupUDPReverseProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{14}
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigResponse) GetReverseProxyJSON() []byte {
	if x != nil {
		return x.ReverseProxyJSON
	}
	return nil
}

func (x *FindAndInitServerGroupUDPReverseProxyConfigResponse) GetReverseProxyRefJSON() []byte {
	if x != nil {
		return x.ReverseProxyRefJSON
	}
	return nil
}

// 修改分组的HTTP反向代理设置
type UpdateServerGroupHTTPReverseProxyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId    int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	ReverseProxyJSON []byte                 `protobuf:"bytes,2,opt,name=reverseProxyJSON,proto3" json:"reverseProxyJSON,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServerGroupHTTPReverseProxyRequest) Reset() {
	*x = UpdateServerGroupHTTPReverseProxyRequest{}
	mi := &file_service_server_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerGroupHTTPReverseProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerGroupHTTPReverseProxyRequest) ProtoMessage() {}

func (x *UpdateServerGroupHTTPReverseProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerGroupHTTPReverseProxyRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerGroupHTTPReverseProxyRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateServerGroupHTTPReverseProxyRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

func (x *UpdateServerGroupHTTPReverseProxyRequest) GetReverseProxyJSON() []byte {
	if x != nil {
		return x.ReverseProxyJSON
	}
	return nil
}

// 修改分组的TCP反向代理设置
type UpdateServerGroupTCPReverseProxyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId    int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	ReverseProxyJSON []byte                 `protobuf:"bytes,2,opt,name=reverseProxyJSON,proto3" json:"reverseProxyJSON,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServerGroupTCPReverseProxyRequest) Reset() {
	*x = UpdateServerGroupTCPReverseProxyRequest{}
	mi := &file_service_server_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerGroupTCPReverseProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerGroupTCPReverseProxyRequest) ProtoMessage() {}

func (x *UpdateServerGroupTCPReverseProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerGroupTCPReverseProxyRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerGroupTCPReverseProxyRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateServerGroupTCPReverseProxyRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

func (x *UpdateServerGroupTCPReverseProxyRequest) GetReverseProxyJSON() []byte {
	if x != nil {
		return x.ReverseProxyJSON
	}
	return nil
}

// 修改分组的UDP反向代理设置
type UpdateServerGroupUDPReverseProxyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId    int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	ReverseProxyJSON []byte                 `protobuf:"bytes,2,opt,name=reverseProxyJSON,proto3" json:"reverseProxyJSON,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServerGroupUDPReverseProxyRequest) Reset() {
	*x = UpdateServerGroupUDPReverseProxyRequest{}
	mi := &file_service_server_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerGroupUDPReverseProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerGroupUDPReverseProxyRequest) ProtoMessage() {}

func (x *UpdateServerGroupUDPReverseProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerGroupUDPReverseProxyRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerGroupUDPReverseProxyRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateServerGroupUDPReverseProxyRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

func (x *UpdateServerGroupUDPReverseProxyRequest) GetReverseProxyJSON() []byte {
	if x != nil {
		return x.ReverseProxyJSON
	}
	return nil
}

// 取得分组的配置概要信息
type FindEnabledServerGroupConfigInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	ServerId      int64                  `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEnabledServerGroupConfigInfoRequest) Reset() {
	*x = FindEnabledServerGroupConfigInfoRequest{}
	mi := &file_service_server_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledServerGroupConfigInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledServerGroupConfigInfoRequest) ProtoMessage() {}

func (x *FindEnabledServerGroupConfigInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledServerGroupConfigInfoRequest.ProtoReflect.Descriptor instead.
func (*FindEnabledServerGroupConfigInfoRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{18}
}

func (x *FindEnabledServerGroupConfigInfoRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

func (x *FindEnabledServerGroupConfigInfoRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type FindEnabledServerGroupConfigInfoResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HasHTTPReverseProxy      bool                   `protobuf:"varint,1,opt,name=hasHTTPReverseProxy,proto3" json:"hasHTTPReverseProxy,omitempty"`
	HasTCPReverseProxy       bool                   `protobuf:"varint,2,opt,name=hasTCPReverseProxy,proto3" json:"hasTCPReverseProxy,omitempty"`
	HasUDPReverseProxy       bool                   `protobuf:"varint,3,opt,name=hasUDPReverseProxy,proto3" json:"hasUDPReverseProxy,omitempty"`
	ServerGroupId            int64                  `protobuf:"varint,4,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	HasRootConfig            bool                   `protobuf:"varint,5,opt,name=hasRootConfig,proto3" json:"hasRootConfig,omitempty"`
	HasWAFConfig             bool                   `protobuf:"varint,6,opt,name=hasWAFConfig,proto3" json:"hasWAFConfig,omitempty"`
	HasCacheConfig           bool                   `protobuf:"varint,7,opt,name=hasCacheConfig,proto3" json:"hasCacheConfig,omitempty"`
	HasCharsetConfig         bool                   `protobuf:"varint,8,opt,name=hasCharsetConfig,proto3" json:"hasCharsetConfig,omitempty"`
	HasStatConfig            bool                   `protobuf:"varint,9,opt,name=hasStatConfig,proto3" json:"hasStatConfig,omitempty"`
	HasCompressionConfig     bool                   `protobuf:"varint,10,opt,name=hasCompressionConfig,proto3" json:"hasCompressionConfig,omitempty"`
	HasOptimizationConfig    bool                   `protobuf:"varint,20,opt,name=hasOptimizationConfig,proto3" json:"hasOptimizationConfig,omitempty"`
	HasRequestHeadersConfig  bool                   `protobuf:"varint,11,opt,name=hasRequestHeadersConfig,proto3" json:"hasRequestHeadersConfig,omitempty"`
	HasResponseHeadersConfig bool                   `protobuf:"varint,12,opt,name=hasResponseHeadersConfig,proto3" json:"hasResponseHeadersConfig,omitempty"`
	HasWebsocketConfig       bool                   `protobuf:"varint,13,opt,name=hasWebsocketConfig,proto3" json:"hasWebsocketConfig,omitempty"`
	HasWebPConfig            bool                   `protobuf:"varint,14,opt,name=hasWebPConfig,proto3" json:"hasWebPConfig,omitempty"`
	HasAccessLogConfig       bool                   `protobuf:"varint,15,opt,name=hasAccessLogConfig,proto3" json:"hasAccessLogConfig,omitempty"`
	HasRemoteAddrConfig      bool                   `protobuf:"varint,16,opt,name=hasRemoteAddrConfig,proto3" json:"hasRemoteAddrConfig,omitempty"`
	HasPagesConfig           bool                   `protobuf:"varint,17,opt,name=hasPagesConfig,proto3" json:"hasPagesConfig,omitempty"`
	HasRequestLimitConfig    bool                   `protobuf:"varint,18,opt,name=hasRequestLimitConfig,proto3" json:"hasRequestLimitConfig,omitempty"`
	HasRequestScriptsConfig  bool                   `protobuf:"varint,19,opt,name=hasRequestScriptsConfig,proto3" json:"hasRequestScriptsConfig,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *FindEnabledServerGroupConfigInfoResponse) Reset() {
	*x = FindEnabledServerGroupConfigInfoResponse{}
	mi := &file_service_server_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEnabledServerGroupConfigInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEnabledServerGroupConfigInfoResponse) ProtoMessage() {}

func (x *FindEnabledServerGroupConfigInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEnabledServerGroupConfigInfoResponse.ProtoReflect.Descriptor instead.
func (*FindEnabledServerGroupConfigInfoResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{19}
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasHTTPReverseProxy() bool {
	if x != nil {
		return x.HasHTTPReverseProxy
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasTCPReverseProxy() bool {
	if x != nil {
		return x.HasTCPReverseProxy
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasUDPReverseProxy() bool {
	if x != nil {
		return x.HasUDPReverseProxy
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasRootConfig() bool {
	if x != nil {
		return x.HasRootConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasWAFConfig() bool {
	if x != nil {
		return x.HasWAFConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasCacheConfig() bool {
	if x != nil {
		return x.HasCacheConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasCharsetConfig() bool {
	if x != nil {
		return x.HasCharsetConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasStatConfig() bool {
	if x != nil {
		return x.HasStatConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasCompressionConfig() bool {
	if x != nil {
		return x.HasCompressionConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasOptimizationConfig() bool {
	if x != nil {
		return x.HasOptimizationConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasRequestHeadersConfig() bool {
	if x != nil {
		return x.HasRequestHeadersConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasResponseHeadersConfig() bool {
	if x != nil {
		return x.HasResponseHeadersConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasWebsocketConfig() bool {
	if x != nil {
		return x.HasWebsocketConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasWebPConfig() bool {
	if x != nil {
		return x.HasWebPConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasAccessLogConfig() bool {
	if x != nil {
		return x.HasAccessLogConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasRemoteAddrConfig() bool {
	if x != nil {
		return x.HasRemoteAddrConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasPagesConfig() bool {
	if x != nil {
		return x.HasPagesConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasRequestLimitConfig() bool {
	if x != nil {
		return x.HasRequestLimitConfig
	}
	return false
}

func (x *FindEnabledServerGroupConfigInfoResponse) GetHasRequestScriptsConfig() bool {
	if x != nil {
		return x.HasRequestScriptsConfig
	}
	return false
}

// 初始化Web设置
type FindAndInitServerGroupWebConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerGroupId int64                  `protobuf:"varint,1,opt,name=serverGroupId,proto3" json:"serverGroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndInitServerGroupWebConfigRequest) Reset() {
	*x = FindAndInitServerGroupWebConfigRequest{}
	mi := &file_service_server_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupWebConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupWebConfigRequest) ProtoMessage() {}

func (x *FindAndInitServerGroupWebConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupWebConfigRequest.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupWebConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{20}
}

func (x *FindAndInitServerGroupWebConfigRequest) GetServerGroupId() int64 {
	if x != nil {
		return x.ServerGroupId
	}
	return 0
}

type FindAndInitServerGroupWebConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebJSON       []byte                 `protobuf:"bytes,1,opt,name=webJSON,proto3" json:"webJSON,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndInitServerGroupWebConfigResponse) Reset() {
	*x = FindAndInitServerGroupWebConfigResponse{}
	mi := &file_service_server_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndInitServerGroupWebConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndInitServerGroupWebConfigResponse) ProtoMessage() {}

func (x *FindAndInitServerGroupWebConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_server_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndInitServerGroupWebConfigResponse.ProtoReflect.Descriptor instead.
func (*FindAndInitServerGroupWebConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_server_group_proto_rawDescGZIP(), []int{21}
}

func (x *FindAndInitServerGroupWebConfigResponse) GetWebJSON() []byte {
	if x != nil {
		return x.WebJSON
	}
	return nil
}

var File_service_server_group_proto protoreflect.FileDescriptor

const file_service_server_group_proto_rawDesc = "" +
	"\n" +
	"\x1aservice_server_group.proto\x12\x02pb\x1a\x1fmodels/model_server_group.proto\x1a\x19models/rpc_messages.proto\".\n" +
	"\x18CreateServerGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x19CreateServerGroupResponse\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\"T\n" +
	"\x18UpdateServerGroupRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x18DeleteServerGroupRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\";\n" +
	"!FindAllEnabledServerGroupsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"Y\n" +
	"\"FindAllEnabledServerGroupsResponse\x123\n" +
	"\fserverGroups\x18\x01 \x03(\v2\x0f.pb.ServerGroupR\fserverGroups\"H\n" +
	"\x1eUpdateServerGroupOrdersRequest\x12&\n" +
	"\x0eserverGroupIds\x18\x01 \x03(\x03R\x0eserverGroupIds\"E\n" +
	"\x1dFindEnabledServerGroupRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\"S\n" +
	"\x1eFindEnabledServerGroupResponse\x121\n" +
	"\vserverGroup\x18\x01 \x01(\v2\x0f.pb.ServerGroupR\vserverGroup\"[\n" +
	"3FindAndInitServerGroupHTTPReverseProxyConfigRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\"\x94\x01\n" +
	"4FindAndInitServerGroupHTTPReverseProxyConfigResponse\x12*\n" +
	"\x10reverseProxyJSON\x18\x01 \x01(\fR\x10reverseProxyJSON\x120\n" +
	"\x13reverseProxyRefJSON\x18\x02 \x01(\fR\x13reverseProxyRefJSON\"Z\n" +
	"2FindAndInitServerGroupTCPReverseProxyConfigRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\"\x93\x01\n" +
	"3FindAndInitServerGroupTCPReverseProxyConfigResponse\x12*\n" +
	"\x10reverseProxyJSON\x18\x01 \x01(\fR\x10reverseProxyJSON\x120\n" +
	"\x13reverseProxyRefJSON\x18\x02 \x01(\fR\x13reverseProxyRefJSON\"Z\n" +
	"2FindAndInitServerGroupUDPReverseProxyConfigRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\"\x93\x01\n" +
	"3FindAndInitServerGroupUDPReverseProxyConfigResponse\x12*\n" +
	"\x10reverseProxyJSON\x18\x01 \x01(\fR\x10reverseProxyJSON\x120\n" +
	"\x13reverseProxyRefJSON\x18\x02 \x01(\fR\x13reverseProxyRefJSON\"|\n" +
	"(UpdateServerGroupHTTPReverseProxyRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\x12*\n" +
	"\x10reverseProxyJSON\x18\x02 \x01(\fR\x10reverseProxyJSON\"{\n" +
	"'UpdateServerGroupTCPReverseProxyRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\x12*\n" +
	"\x10reverseProxyJSON\x18\x02 \x01(\fR\x10reverseProxyJSON\"{\n" +
	"'UpdateServerGroupUDPReverseProxyRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\x12*\n" +
	"\x10reverseProxyJSON\x18\x02 \x01(\fR\x10reverseProxyJSON\"k\n" +
	"'FindEnabledServerGroupConfigInfoRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\x12\x1a\n" +
	"\bserverId\x18\x02 \x01(\x03R\bserverId\"\xd6\a\n" +
	"(FindEnabledServerGroupConfigInfoResponse\x120\n" +
	"\x13hasHTTPReverseProxy\x18\x01 \x01(\bR\x13hasHTTPReverseProxy\x12.\n" +
	"\x12hasTCPReverseProxy\x18\x02 \x01(\bR\x12hasTCPReverseProxy\x12.\n" +
	"\x12hasUDPReverseProxy\x18\x03 \x01(\bR\x12hasUDPReverseProxy\x12$\n" +
	"\rserverGroupId\x18\x04 \x01(\x03R\rserverGroupId\x12$\n" +
	"\rhasRootConfig\x18\x05 \x01(\bR\rhasRootConfig\x12\"\n" +
	"\fhasWAFConfig\x18\x06 \x01(\bR\fhasWAFConfig\x12&\n" +
	"\x0ehasCacheConfig\x18\a \x01(\bR\x0ehasCacheConfig\x12*\n" +
	"\x10hasCharsetConfig\x18\b \x01(\bR\x10hasCharsetConfig\x12$\n" +
	"\rhasStatConfig\x18\t \x01(\bR\rhasStatConfig\x122\n" +
	"\x14hasCompressionConfig\x18\n" +
	" \x01(\bR\x14hasCompressionConfig\x124\n" +
	"\x15hasOptimizationConfig\x18\x14 \x01(\bR\x15hasOptimizationConfig\x128\n" +
	"\x17hasRequestHeadersConfig\x18\v \x01(\bR\x17hasRequestHeadersConfig\x12:\n" +
	"\x18hasResponseHeadersConfig\x18\f \x01(\bR\x18hasResponseHeadersConfig\x12.\n" +
	"\x12hasWebsocketConfig\x18\r \x01(\bR\x12hasWebsocketConfig\x12$\n" +
	"\rhasWebPConfig\x18\x0e \x01(\bR\rhasWebPConfig\x12.\n" +
	"\x12hasAccessLogConfig\x18\x0f \x01(\bR\x12hasAccessLogConfig\x120\n" +
	"\x13hasRemoteAddrConfig\x18\x10 \x01(\bR\x13hasRemoteAddrConfig\x12&\n" +
	"\x0ehasPagesConfig\x18\x11 \x01(\bR\x0ehasPagesConfig\x124\n" +
	"\x15hasRequestLimitConfig\x18\x12 \x01(\bR\x15hasRequestLimitConfig\x128\n" +
	"\x17hasRequestScriptsConfig\x18\x13 \x01(\bR\x17hasRequestScriptsConfig\"N\n" +
	"&FindAndInitServerGroupWebConfigRequest\x12$\n" +
	"\rserverGroupId\x18\x01 \x01(\x03R\rserverGroupId\"C\n" +
	"'FindAndInitServerGroupWebConfigResponse\x12\x18\n" +
	"\awebJSON\x18\x01 \x01(\fR\awebJSON2\x8f\f\n" +
	"\x12ServerGroupService\x12P\n" +
	"\x11createServerGroup\x12\x1c.pb.CreateServerGroupRequest\x1a\x1d.pb.CreateServerGroupResponse\x12A\n" +
	"\x11updateServerGroup\x12\x1c.pb.UpdateServerGroupRequest\x1a\x0e.pb.RPCSuccess\x12A\n" +
	"\x11deleteServerGroup\x12\x1c.pb.DeleteServerGroupRequest\x1a\x0e.pb.RPCSuccess\x12k\n" +
	"\x1afindAllEnabledServerGroups\x12%.pb.FindAllEnabledServerGroupsRequest\x1a&.pb.FindAllEnabledServerGroupsResponse\x12M\n" +
	"\x17updateServerGroupOrders\x12\".pb.UpdateServerGroupOrdersRequest\x1a\x0e.pb.RPCSuccess\x12_\n" +
	"\x16findEnabledServerGroup\x12!.pb.FindEnabledServerGroupRequest\x1a\".pb.FindEnabledServerGroupResponse\x12\xa1\x01\n" +
	",findAndInitServerGroupHTTPReverseProxyConfig\x127.pb.FindAndInitServerGroupHTTPReverseProxyConfigRequest\x1a8.pb.FindAndInitServerGroupHTTPReverseProxyConfigResponse\x12\x9e\x01\n" +
	"+findAndInitServerGroupTCPReverseProxyConfig\x126.pb.FindAndInitServerGroupTCPReverseProxyConfigRequest\x1a7.pb.FindAndInitServerGroupTCPReverseProxyConfigResponse\x12\x9e\x01\n" +
	"+findAndInitServerGroupUDPReverseProxyConfig\x126.pb.FindAndInitServerGroupUDPReverseProxyConfigRequest\x1a7.pb.FindAndInitServerGroupUDPReverseProxyConfigResponse\x12a\n" +
	"!updateServerGroupHTTPReverseProxy\x12,.pb.UpdateServerGroupHTTPReverseProxyRequest\x1a\x0e.pb.RPCSuccess\x12_\n" +
	" updateServerGroupTCPReverseProxy\x12+.pb.UpdateServerGroupTCPReverseProxyRequest\x1a\x0e.pb.RPCSuccess\x12_\n" +
	" updateServerGroupUDPReverseProxy\x12+.pb.UpdateServerGroupUDPReverseProxyRequest\x1a\x0e.pb.RPCSuccess\x12}\n" +
	" findEnabledServerGroupConfigInfo\x12+.pb.FindEnabledServerGroupConfigInfoRequest\x1a,.pb.FindEnabledServerGroupConfigInfoResponse\x12z\n" +
	"\x1ffindAndInitServerGroupWebConfig\x12*.pb.FindAndInitServerGroupWebConfigRequest\x1a+.pb.FindAndInitServerGroupWebConfigResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_server_group_proto_rawDescOnce sync.Once
	file_service_server_group_proto_rawDescData []byte
)

func file_service_server_group_proto_rawDescGZIP() []byte {
	file_service_server_group_proto_rawDescOnce.Do(func() {
		file_service_server_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_server_group_proto_rawDesc), len(file_service_server_group_proto_rawDesc)))
	})
	return file_service_server_group_proto_rawDescData
}

var file_service_server_group_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_service_server_group_proto_goTypes = []any{
	(*CreateServerGroupRequest)(nil),                             // 0: pb.CreateServerGroupRequest
	(*CreateServerGroupResponse)(nil),                            // 1: pb.CreateServerGroupResponse
	(*UpdateServerGroupRequest)(nil),                             // 2: pb.UpdateServerGroupRequest
	(*DeleteServerGroupRequest)(nil),                             // 3: pb.DeleteServerGroupRequest
	(*FindAllEnabledServerGroupsRequest)(nil),                    // 4: pb.FindAllEnabledServerGroupsRequest
	(*FindAllEnabledServerGroupsResponse)(nil),                   // 5: pb.FindAllEnabledServerGroupsResponse
	(*UpdateServerGroupOrdersRequest)(nil),                       // 6: pb.UpdateServerGroupOrdersRequest
	(*FindEnabledServerGroupRequest)(nil),                        // 7: pb.FindEnabledServerGroupRequest
	(*FindEnabledServerGroupResponse)(nil),                       // 8: pb.FindEnabledServerGroupResponse
	(*FindAndInitServerGroupHTTPReverseProxyConfigRequest)(nil),  // 9: pb.FindAndInitServerGroupHTTPReverseProxyConfigRequest
	(*FindAndInitServerGroupHTTPReverseProxyConfigResponse)(nil), // 10: pb.FindAndInitServerGroupHTTPReverseProxyConfigResponse
	(*FindAndInitServerGroupTCPReverseProxyConfigRequest)(nil),   // 11: pb.FindAndInitServerGroupTCPReverseProxyConfigRequest
	(*FindAndInitServerGroupTCPReverseProxyConfigResponse)(nil),  // 12: pb.FindAndInitServerGroupTCPReverseProxyConfigResponse
	(*FindAndInitServerGroupUDPReverseProxyConfigRequest)(nil),   // 13: pb.FindAndInitServerGroupUDPReverseProxyConfigRequest
	(*FindAndInitServerGroupUDPReverseProxyConfigResponse)(nil),  // 14: pb.FindAndInitServerGroupUDPReverseProxyConfigResponse
	(*UpdateServerGroupHTTPReverseProxyRequest)(nil),             // 15: pb.UpdateServerGroupHTTPReverseProxyRequest
	(*UpdateServerGroupTCPReverseProxyRequest)(nil),              // 16: pb.UpdateServerGroupTCPReverseProxyRequest
	(*UpdateServerGroupUDPReverseProxyRequest)(nil),              // 17: pb.UpdateServerGroupUDPReverseProxyRequest
	(*FindEnabledServerGroupConfigInfoRequest)(nil),              // 18: pb.FindEnabledServerGroupConfigInfoRequest
	(*FindEnabledServerGroupConfigInfoResponse)(nil),             // 19: pb.FindEnabledServerGroupConfigInfoResponse
	(*FindAndInitServerGroupWebConfigRequest)(nil),               // 20: pb.FindAndInitServerGroupWebConfigRequest
	(*FindAndInitServerGroupWebConfigResponse)(nil),              // 21: pb.FindAndInitServerGroupWebConfigResponse
	(*ServerGroup)(nil),                                          // 22: pb.ServerGroup
	(*RPCSuccess)(nil),                                           // 23: pb.RPCSuccess
}
var file_service_server_group_proto_depIdxs = []int32{
	22, // 0: pb.FindAllEnabledServerGroupsResponse.serverGroups:type_name -> pb.ServerGroup
	22, // 1: pb.FindEnabledServerGroupResponse.serverGroup:type_name -> pb.ServerGroup
	0,  // 2: pb.ServerGroupService.createServerGroup:input_type -> pb.CreateServerGroupRequest
	2,  // 3: pb.ServerGroupService.updateServerGroup:input_type -> pb.UpdateServerGroupRequest
	3,  // 4: pb.ServerGroupService.deleteServerGroup:input_type -> pb.DeleteServerGroupRequest
	4,  // 5: pb.ServerGroupService.findAllEnabledServerGroups:input_type -> pb.FindAllEnabledServerGroupsRequest
	6,  // 6: pb.ServerGroupService.updateServerGroupOrders:input_type -> pb.UpdateServerGroupOrdersRequest
	7,  // 7: pb.ServerGroupService.findEnabledServerGroup:input_type -> pb.FindEnabledServerGroupRequest
	9,  // 8: pb.ServerGroupService.findAndInitServerGroupHTTPReverseProxyConfig:input_type -> pb.FindAndInitServerGroupHTTPReverseProxyConfigRequest
	11, // 9: pb.ServerGroupService.findAndInitServerGroupTCPReverseProxyConfig:input_type -> pb.FindAndInitServerGroupTCPReverseProxyConfigRequest
	13, // 10: pb.ServerGroupService.findAndInitServerGroupUDPReverseProxyConfig:input_type -> pb.FindAndInitServerGroupUDPReverseProxyConfigRequest
	15, // 11: pb.ServerGroupService.updateServerGroupHTTPReverseProxy:input_type -> pb.UpdateServerGroupHTTPReverseProxyRequest
	16, // 12: pb.ServerGroupService.updateServerGroupTCPReverseProxy:input_type -> pb.UpdateServerGroupTCPReverseProxyRequest
	17, // 13: pb.ServerGroupService.updateServerGroupUDPReverseProxy:input_type -> pb.UpdateServerGroupUDPReverseProxyRequest
	18, // 14: pb.ServerGroupService.findEnabledServerGroupConfigInfo:input_type -> pb.FindEnabledServerGroupConfigInfoRequest
	20, // 15: pb.ServerGroupService.findAndInitServerGroupWebConfig:input_type -> pb.FindAndInitServerGroupWebConfigRequest
	1,  // 16: pb.ServerGroupService.createServerGroup:output_type -> pb.CreateServerGroupResponse
	23, // 17: pb.ServerGroupService.updateServerGroup:output_type -> pb.RPCSuccess
	23, // 18: pb.ServerGroupService.deleteServerGroup:output_type -> pb.RPCSuccess
	5,  // 19: pb.ServerGroupService.findAllEnabledServerGroups:output_type -> pb.FindAllEnabledServerGroupsResponse
	23, // 20: pb.ServerGroupService.updateServerGroupOrders:output_type -> pb.RPCSuccess
	8,  // 21: pb.ServerGroupService.findEnabledServerGroup:output_type -> pb.FindEnabledServerGroupResponse
	10, // 22: pb.ServerGroupService.findAndInitServerGroupHTTPReverseProxyConfig:output_type -> pb.FindAndInitServerGroupHTTPReverseProxyConfigResponse
	12, // 23: pb.ServerGroupService.findAndInitServerGroupTCPReverseProxyConfig:output_type -> pb.FindAndInitServerGroupTCPReverseProxyConfigResponse
	14, // 24: pb.ServerGroupService.findAndInitServerGroupUDPReverseProxyConfig:output_type -> pb.FindAndInitServerGroupUDPReverseProxyConfigResponse
	23, // 25: pb.ServerGroupService.updateServerGroupHTTPReverseProxy:output_type -> pb.RPCSuccess
	23, // 26: pb.ServerGroupService.updateServerGroupTCPReverseProxy:output_type -> pb.RPCSuccess
	23, // 27: pb.ServerGroupService.updateServerGroupUDPReverseProxy:output_type -> pb.RPCSuccess
	19, // 28: pb.ServerGroupService.findEnabledServerGroupConfigInfo:output_type -> pb.FindEnabledServerGroupConfigInfoResponse
	21, // 29: pb.ServerGroupService.findAndInitServerGroupWebConfig:output_type -> pb.FindAndInitServerGroupWebConfigResponse
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_service_server_group_proto_init() }
func file_service_server_group_proto_init() {
	if File_service_server_group_proto != nil {
		return
	}
	file_models_model_server_group_proto_init()
	file_models_rpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_server_group_proto_rawDesc), len(file_service_server_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_server_group_proto_goTypes,
		DependencyIndexes: file_service_server_group_proto_depIdxs,
		MessageInfos:      file_service_server_group_proto_msgTypes,
	}.Build()
	File_service_server_group_proto = out.File
	file_service_server_group_proto_goTypes = nil
	file_service_server_group_proto_depIdxs = nil
}
