// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: service_formal_client_browser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建浏览器信息
type CreateFormalClientBrowserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Codes         []string               `protobuf:"bytes,2,rep,name=codes,proto3" json:"codes,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=dataId,proto3" json:"dataId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormalClientBrowserRequest) Reset() {
	*x = CreateFormalClientBrowserRequest{}
	mi := &file_service_formal_client_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormalClientBrowserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormalClientBrowserRequest) ProtoMessage() {}

func (x *CreateFormalClientBrowserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormalClientBrowserRequest.ProtoReflect.Descriptor instead.
func (*CreateFormalClientBrowserRequest) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFormalClientBrowserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFormalClientBrowserRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *CreateFormalClientBrowserRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type CreateFormalClientBrowserResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FormalClientBrowserId int64                  `protobuf:"varint,1,opt,name=formalClientBrowserId,proto3" json:"formalClientBrowserId,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateFormalClientBrowserResponse) Reset() {
	*x = CreateFormalClientBrowserResponse{}
	mi := &file_service_formal_client_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormalClientBrowserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormalClientBrowserResponse) ProtoMessage() {}

func (x *CreateFormalClientBrowserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormalClientBrowserResponse.ProtoReflect.Descriptor instead.
func (*CreateFormalClientBrowserResponse) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFormalClientBrowserResponse) GetFormalClientBrowserId() int64 {
	if x != nil {
		return x.FormalClientBrowserId
	}
	return 0
}

// 计算浏览器信息数量
type CountFormalClientBrowsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // 可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountFormalClientBrowsersRequest) Reset() {
	*x = CountFormalClientBrowsersRequest{}
	mi := &file_service_formal_client_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountFormalClientBrowsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountFormalClientBrowsersRequest) ProtoMessage() {}

func (x *CountFormalClientBrowsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountFormalClientBrowsersRequest.ProtoReflect.Descriptor instead.
func (*CountFormalClientBrowsersRequest) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{2}
}

func (x *CountFormalClientBrowsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 列出单页浏览器信息
type ListFormalClientBrowsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // 可选
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormalClientBrowsersRequest) Reset() {
	*x = ListFormalClientBrowsersRequest{}
	mi := &file_service_formal_client_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormalClientBrowsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormalClientBrowsersRequest) ProtoMessage() {}

func (x *ListFormalClientBrowsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormalClientBrowsersRequest.ProtoReflect.Descriptor instead.
func (*ListFormalClientBrowsersRequest) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{3}
}

func (x *ListFormalClientBrowsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListFormalClientBrowsersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListFormalClientBrowsersRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFormalClientBrowsersResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FormalClientBrowsers []*FormalClientBrowser `protobuf:"bytes,1,rep,name=formalClientBrowsers,proto3" json:"formalClientBrowsers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListFormalClientBrowsersResponse) Reset() {
	*x = ListFormalClientBrowsersResponse{}
	mi := &file_service_formal_client_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormalClientBrowsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormalClientBrowsersResponse) ProtoMessage() {}

func (x *ListFormalClientBrowsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormalClientBrowsersResponse.ProtoReflect.Descriptor instead.
func (*ListFormalClientBrowsersResponse) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{4}
}

func (x *ListFormalClientBrowsersResponse) GetFormalClientBrowsers() []*FormalClientBrowser {
	if x != nil {
		return x.FormalClientBrowsers
	}
	return nil
}

// 修改浏览器信息
type UpdateFormalClientBrowserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FormalClientBrowserId int64                  `protobuf:"varint,1,opt,name=formalClientBrowserId,proto3" json:"formalClientBrowserId,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Codes                 []string               `protobuf:"bytes,3,rep,name=codes,proto3" json:"codes,omitempty"`
	DataId                string                 `protobuf:"bytes,4,opt,name=dataId,proto3" json:"dataId,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateFormalClientBrowserRequest) Reset() {
	*x = UpdateFormalClientBrowserRequest{}
	mi := &file_service_formal_client_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormalClientBrowserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormalClientBrowserRequest) ProtoMessage() {}

func (x *UpdateFormalClientBrowserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormalClientBrowserRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormalClientBrowserRequest) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFormalClientBrowserRequest) GetFormalClientBrowserId() int64 {
	if x != nil {
		return x.FormalClientBrowserId
	}
	return 0
}

func (x *UpdateFormalClientBrowserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFormalClientBrowserRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *UpdateFormalClientBrowserRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

// 通过dataId查询浏览器信息
type FindFormalClientBrowserWithDataIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=dataId,proto3" json:"dataId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFormalClientBrowserWithDataIdRequest) Reset() {
	*x = FindFormalClientBrowserWithDataIdRequest{}
	mi := &file_service_formal_client_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFormalClientBrowserWithDataIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFormalClientBrowserWithDataIdRequest) ProtoMessage() {}

func (x *FindFormalClientBrowserWithDataIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFormalClientBrowserWithDataIdRequest.ProtoReflect.Descriptor instead.
func (*FindFormalClientBrowserWithDataIdRequest) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{6}
}

func (x *FindFormalClientBrowserWithDataIdRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type FindFormalClientBrowserWithDataIdResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FormalClientBrowser *FormalClientBrowser   `protobuf:"bytes,1,opt,name=formalClientBrowser,proto3" json:"formalClientBrowser,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindFormalClientBrowserWithDataIdResponse) Reset() {
	*x = FindFormalClientBrowserWithDataIdResponse{}
	mi := &file_service_formal_client_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFormalClientBrowserWithDataIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFormalClientBrowserWithDataIdResponse) ProtoMessage() {}

func (x *FindFormalClientBrowserWithDataIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_formal_client_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFormalClientBrowserWithDataIdResponse.ProtoReflect.Descriptor instead.
func (*FindFormalClientBrowserWithDataIdResponse) Descriptor() ([]byte, []int) {
	return file_service_formal_client_browser_proto_rawDescGZIP(), []int{7}
}

func (x *FindFormalClientBrowserWithDataIdResponse) GetFormalClientBrowser() *FormalClientBrowser {
	if x != nil {
		return x.FormalClientBrowser
	}
	return nil
}

var File_service_formal_client_browser_proto protoreflect.FileDescriptor

const file_service_formal_client_browser_proto_rawDesc = "" +
	"\n" +
	"#service_formal_client_browser.proto\x12\x02pb\x1a\x19models/rpc_messages.proto\x1a(models/model_formal_client_browser.proto\"d\n" +
	" CreateFormalClientBrowserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05codes\x18\x02 \x03(\tR\x05codes\x12\x16\n" +
	"\x06dataId\x18\x03 \x01(\tR\x06dataId\"Y\n" +
	"!CreateFormalClientBrowserResponse\x124\n" +
	"\x15formalClientBrowserId\x18\x01 \x01(\x03R\x15formalClientBrowserId\"<\n" +
	" CountFormalClientBrowsersRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"g\n" +
	"\x1fListFormalClientBrowsersRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"o\n" +
	" ListFormalClientBrowsersResponse\x12K\n" +
	"\x14formalClientBrowsers\x18\x01 \x03(\v2\x17.pb.FormalClientBrowserR\x14formalClientBrowsers\"\x9a\x01\n" +
	" UpdateFormalClientBrowserRequest\x124\n" +
	"\x15formalClientBrowserId\x18\x01 \x01(\x03R\x15formalClientBrowserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05codes\x18\x03 \x03(\tR\x05codes\x12\x16\n" +
	"\x06dataId\x18\x04 \x01(\tR\x06dataId\"B\n" +
	"(FindFormalClientBrowserWithDataIdRequest\x12\x16\n" +
	"\x06dataId\x18\x01 \x01(\tR\x06dataId\"v\n" +
	")FindFormalClientBrowserWithDataIdResponse\x12I\n" +
	"\x13formalClientBrowser\x18\x01 \x01(\v2\x17.pb.FormalClientBrowserR\x13formalClientBrowser2\x9c\x04\n" +
	"\x1aFormalClientBrowserService\x12h\n" +
	"\x19createFormalClientBrowser\x12$.pb.CreateFormalClientBrowserRequest\x1a%.pb.CreateFormalClientBrowserResponse\x12W\n" +
	"\x19countFormalClientBrowsers\x12$.pb.CountFormalClientBrowsersRequest\x1a\x14.pb.RPCCountResponse\x12e\n" +
	"\x18listFormalClientBrowsers\x12#.pb.ListFormalClientBrowsersRequest\x1a$.pb.ListFormalClientBrowsersResponse\x12Q\n" +
	"\x19updateFormalClientBrowser\x12$.pb.UpdateFormalClientBrowserRequest\x1a\x0e.pb.RPCSuccess\x12\x80\x01\n" +
	"!findFormalClientBrowserWithDataId\x12,.pb.FindFormalClientBrowserWithDataIdRequest\x1a-.pb.FindFormalClientBrowserWithDataIdResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_service_formal_client_browser_proto_rawDescOnce sync.Once
	file_service_formal_client_browser_proto_rawDescData []byte
)

func file_service_formal_client_browser_proto_rawDescGZIP() []byte {
	file_service_formal_client_browser_proto_rawDescOnce.Do(func() {
		file_service_formal_client_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_formal_client_browser_proto_rawDesc), len(file_service_formal_client_browser_proto_rawDesc)))
	})
	return file_service_formal_client_browser_proto_rawDescData
}

var file_service_formal_client_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_formal_client_browser_proto_goTypes = []any{
	(*CreateFormalClientBrowserRequest)(nil),          // 0: pb.CreateFormalClientBrowserRequest
	(*CreateFormalClientBrowserResponse)(nil),         // 1: pb.CreateFormalClientBrowserResponse
	(*CountFormalClientBrowsersRequest)(nil),          // 2: pb.CountFormalClientBrowsersRequest
	(*ListFormalClientBrowsersRequest)(nil),           // 3: pb.ListFormalClientBrowsersRequest
	(*ListFormalClientBrowsersResponse)(nil),          // 4: pb.ListFormalClientBrowsersResponse
	(*UpdateFormalClientBrowserRequest)(nil),          // 5: pb.UpdateFormalClientBrowserRequest
	(*FindFormalClientBrowserWithDataIdRequest)(nil),  // 6: pb.FindFormalClientBrowserWithDataIdRequest
	(*FindFormalClientBrowserWithDataIdResponse)(nil), // 7: pb.FindFormalClientBrowserWithDataIdResponse
	(*FormalClientBrowser)(nil),                       // 8: pb.FormalClientBrowser
	(*RPCCountResponse)(nil),                          // 9: pb.RPCCountResponse
	(*RPCSuccess)(nil),                                // 10: pb.RPCSuccess
}
var file_service_formal_client_browser_proto_depIdxs = []int32{
	8,  // 0: pb.ListFormalClientBrowsersResponse.formalClientBrowsers:type_name -> pb.FormalClientBrowser
	8,  // 1: pb.FindFormalClientBrowserWithDataIdResponse.formalClientBrowser:type_name -> pb.FormalClientBrowser
	0,  // 2: pb.FormalClientBrowserService.createFormalClientBrowser:input_type -> pb.CreateFormalClientBrowserRequest
	2,  // 3: pb.FormalClientBrowserService.countFormalClientBrowsers:input_type -> pb.CountFormalClientBrowsersRequest
	3,  // 4: pb.FormalClientBrowserService.listFormalClientBrowsers:input_type -> pb.ListFormalClientBrowsersRequest
	5,  // 5: pb.FormalClientBrowserService.updateFormalClientBrowser:input_type -> pb.UpdateFormalClientBrowserRequest
	6,  // 6: pb.FormalClientBrowserService.findFormalClientBrowserWithDataId:input_type -> pb.FindFormalClientBrowserWithDataIdRequest
	1,  // 7: pb.FormalClientBrowserService.createFormalClientBrowser:output_type -> pb.CreateFormalClientBrowserResponse
	9,  // 8: pb.FormalClientBrowserService.countFormalClientBrowsers:output_type -> pb.RPCCountResponse
	4,  // 9: pb.FormalClientBrowserService.listFormalClientBrowsers:output_type -> pb.ListFormalClientBrowsersResponse
	10, // 10: pb.FormalClientBrowserService.updateFormalClientBrowser:output_type -> pb.RPCSuccess
	7,  // 11: pb.FormalClientBrowserService.findFormalClientBrowserWithDataId:output_type -> pb.FindFormalClientBrowserWithDataIdResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_service_formal_client_browser_proto_init() }
func file_service_formal_client_browser_proto_init() {
	if File_service_formal_client_browser_proto != nil {
		return
	}
	file_models_rpc_messages_proto_init()
	file_models_model_formal_client_browser_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_formal_client_browser_proto_rawDesc), len(file_service_formal_client_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_formal_client_browser_proto_goTypes,
		DependencyIndexes: file_service_formal_client_browser_proto_depIdxs,
		MessageInfos:      file_service_formal_client_browser_proto_msgTypes,
	}.Build()
	File_service_formal_client_browser_proto = out.File
	file_service_formal_client_browser_proto_goTypes = nil
	file_service_formal_client_browser_proto_depIdxs = nil
}
